### PR TITLE
Only run stack label addition step on pull requests

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

Small fix/follow up to #786, this prevents the "Add stack label" action from running on anything that isn't a pull request. See a failed run which occurred on the "push" action here: https://github.com/WordPress/openverse/actions/runs/4369574126/jobs/7643514186

## Testing Instructions

Merge :slightly_smiling_face:

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Let's test it 😄

**Review by dhruvkb — COMMENTED** [review]
Also add the condition to not run it on PRs from forks because it fails.

**Comment by dhruvkb** [comment]
I have to ask why the job is a part of the `ci_cd.yml` workflow? Wouldn't the `label_new_pr.yml` workflow, which calls the `label_pr.yml` workflow, which runs the `label_pr.py` script apply the label to the PRs automatically?

**Comment by zackkrida** [comment]
@dhruvkb I think that question is best answered by @AetherUnbound and we should probably get clarification on that before moving forward here.

**Comment by AetherUnbound** [comment]
I added this note in the description of #786:

> The PR adds the auto-stack-adding action to the `ci_cd` workflow; I was initially going to add it to the `label_pr` since I'm concerned about race conditions happening between the `label_pr` action and the stack-labeling step.

I'm not sure that assumption/issue still holds, and in fact we no longer need to call the `label_new_pr` workflow using a remote dispatch since they coexist in the same repo (@dhruvkb has helpfully made #897 for covering this effort). Let me take another look at this and see if those race conditions are a real concern. If anything we can merge this (plus the suggested fork fix) for now and rework this down the road so at least merges to main no longer fail on this step.

**Review by dhruvkb — APPROVED** [review]
Thanks @AetherUnbound for looking into it again. I should've been more careful reviewing #786. I'll approve and unblock this for now because it's a positive change nonetheless.

**Comment by AetherUnbound** [comment]
Okay I had some time to look into this today and I'm not sure how we could change this without making it overly complicated. The "add stack label" step currently in `ci_cd.yml` relies on `get-changes`, which is specific to the monorepo. The `label_pr.yml` workflow which is dispatched from all of our repos is agnostic to which repo it's working on. Thus it would be harder for us to add the stack labeling to the label PR step because `get-changes` wouldn't always be available. We _could_ allow it as a parameter to the script similar to `PR_URL`, but then we'd need to add logic to the script to be able to process that input and add the necessary label. So I think keeping this in `ci_cd.yml` is easiest _for now_, since this is a monorepo-specific action and the `ci_cd.yml` workflow is monorepo-specific.

**Pull request merged**
