### PR TITLE
Add django-migration-git-conflict to prevent divergent migration merges

### LINKED ISSUE #687: Prevent divergent migrations from being merged by concurrent, not-rebased PRs
## Problem

See https://github.com/WordPress/openverse-api/pull/810 and the description for the issue.

## Description

We need some way to prevent this.

Here are some suggestions I left in this comment, copied below: https://github.com/WordPress/openverse-api/pull/810#issuecomment-1191503799

> How can we prevent this? Is there any way we can ensure PRs with migrations are always rebased before merging? Could we run an action triggered by pushes that introduce new migrations using https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files and the iterate through all open, non-draft PRs and request changes on them if there is a migration in them?
> 
> We'd also need a similar job in the CI + CD workflow to check for migration conflicts against main any time the PR is pushed to.

Marked as high due to the risk it introduces.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #687 by @sarayourfriend

## Description

Adds `django-migration-git-conflict` recommended [in this comment](https://github.com/WordPress/openverse/issues/687#issuecomment-2040480372) by @tylerlaprade (thanks!).

Check out the plugin's repository for information on how it works: https://github.com/crux-lab/django-migrations-git-conflicts?tab=readme-ov-file#how-it-works

To summarise: the latest migration files for each app will get updated when a new migration is added. When that file is merged, any other branches with divergent latest migrations will conflict, and need a rebase to fix.

Existing CI checks should all continue to work, and we can leave in the PR comment requesting a rebase for migrations anyway, as an additional helpful reminder. Ideally PRs with migrations are always rebased even without a conflict so that the migrated code is tested against main, in case there are issues with new code unaware of the migration changes (i.e., [a semantic conflict](https://martinfowler.com/bliki/SemanticConflict.html)). But we are always vulnerable to those, even outside the context of a migration, so I don't think we should consider them a special case with respect to the linked issue.

## Testing Instructions

Review the new files. Run `just api/dj makemigrations --check` locally and see that it works. Make a change to force a migration (change some help text on a model attribute, for example) and run makemigrations again, confirm that the latest migration is updated. All of that is really just showing how the plugin works, we don't need to test the plugin.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
LGTM, except that Pipenv has, once again, updated a ton of unrelated dependencies. Please see if it is possible to reduce the extent of the updates, but if not, I don't mind.

**Comment by sarayourfriend** [comment]
Oh gosh :facepalm: I thought I checked to make sure, but I think I forgot to re-do it when I had to re-install the dependency locally due to a misconfiguration thing on my end. I'll go through it again, thank you for catching it.

**Review by stacimc — APPROVED** [review]
TIL, very cool plugin. LGTM!

**Review by AetherUnbound — DISMISSED** [review]
Applying a change requested review just so we don't accidentally merge this PR which updates dependencies where we might affect production!

**Comment by dhruvkb** [comment]
I was not requesting changes because it seems like the package upgrades are OK now that #4032 was merged.

**Pull request merged**
