### PR TITLE
Conditional removal of changelogs

### LINKED ISSUE #4726: Sphinx/MYsT dev build is very slow
## Current Situation

The various Sphinx extensions we use combined with the very large number of files (particularly the changelogs) results in a huge overhead for starting up the Sphinx dev site (`ov just documentation/live`).

## Suggested Improvement

It would be nice to find a workaround for this so that most cases of building the dev site could be faster, with optional configuration available to enable a "full" build.

One approach could be to just ignore the changelog directory by default, changelogs account for close to 50% of the files in the documentation site, noticeable during the "Write output" step of the build.

I've tried disabling some extensions locally, like the two custom extensions we have (link issues and link usernames), but doing so does not noticeably speed up the build.

Ignoring the changelogs could be accomplished by conditionally adding them to the `exclude_patterns` list in `documentation/conf.py` based on an environment variable. Something like this could be a good start:

```python
import os

CI = os.getenv("CI") is not None
INCLUDE_CHANGELOGS = bool(os.getenv("INCLUDE_CHANGELOGS", CI))

_default_exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".venv", "README.md"]
exclude_patterns = _default_exclude_patterns + ([] if INCLUDE_CHANGELOGS else ["changelogs"])
```

Ideally we'd discover the source of the slowness and see whether there are official workarounds. We destroy the build cache in the `documentaiton/live` recipe. Perhaps this isn't always necessary, and we could be more judicious about when we do it, rather than doing it _every_ time.

## Benefit

Reduce the overhead of most documentation live site builds, speeding up work on documentation, encouraging proper local review of changes, make the documentation more pleasant to work with.

### PR DESCRIPTION
**Pull request by kb-0311**
## Fixes

Fixes #4726 by @sarayourfriend

## Description

Based on an environment variable conditionally removes the changelogs

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kb-0311** [comment]
@sarayourfriend I am not sure if this is the right approach for this issue. 

For some reason, while setting up the project locally for some reason, after following the general development guidelines , the local test runs keep failing, should I ask for a solution in the slack channel ?

**Comment by sarayourfriend** [comment]
@kb-0311 Can you confirm you have you set up `ov` for linting? It comes pre-loaded with pre-commit so shouldn't have that issue. The output of `cat .git/hooks/pre-commit` should be this, if you have:

```bash
#! /usr/bin/env bash

export TERM=xterm

./ov hook pre-commit "$@"
```

If not, please [follow the `ov` setup instructions on this documentation page, starting with `./ov init` from the repository root](https://docs.openverse.org/general/general_setup.html#up-and-running), and then committing again.

Let me know if you run into any issues with setting up `ov`.

**Comment by kb-0311** [comment]
Thanks a lot , fixed the env setup error : )

Coming to how the redirects are being handled here in my PR:

https://github.com/WordPress/openverse/blob/c95cc0777c53d76e0362a8f88d24eb5937d292f3/documentation/conf.py#L139-L144

I am not really sure if this is the right way to go about it. Also, I could not really find the "Page not found" file location so just added a temporary value for now.

**Comment by sarayourfriend** [comment]
This LGTM! I have two small requests, and then this will be good to go from my perspective.

First is to add the following to `documentation/conf.py` so that we don't see non-actionable warnings in local builds:

```py
nitpick_ignore_regex = () if INCLUDE_CHANGELOGS else (
    ("myst", ".*/changelogs/index.*"),
)
```

This uses the [Sphinx configuration option `nitpick_ignore_regex`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpick_ignore_regex) to ignore "nitpick" warnings about the invalid cross-reference [which is the only targeted method to ignore this error that MyST's documentation describes](https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#handling-invalid-references).

---

The other thing to do is address the redirect. I like the idea of using a redirect, and it simplifies things a lot to do so. However, it would be nice to redirect to a page that explains why the changelogs are missing, if someone happens to run across a link to the changelogs that doesn't resolve when they are working in docs locally. Here is a diff you can work from that does that, by adding an orphan page under `meta` to redirect to when `INCLUDE_CHANGELOGS` is false:

```diff
diff --git a/documentation/conf.py b/documentation/conf.py
index 86035b925..a4d5e33ac 100644
--- a/documentation/conf.py
+++ b/documentation/conf.py
@@ -137,9 +137,6 @@ redirects = {
 }
 
 if "changelogs" in exclude_patterns:
-    # temporary placeholder for now
-    redirects["changelogs/"] = (
-        "/general/contribution/github_contribution_practices.html"
-    )
+    redirects["changelogs/index"] = "/meta/missing_changelogs.html"
 
 myst_enable_extensions = ["linkify"]
diff --git a/documentation/meta/missing_changelogs.md b/documentation/meta/missing_changelogs.md
new file mode 100644
index 000000000..c98635e87
--- /dev/null
+++ b/documentation/meta/missing_changelogs.md
@@ -0,0 +1,13 @@
+---
+orphan: true
+---
+
+# Changelogs missing from local build
+
+The documentation build excludes changelogs unless it is in a CI environment or explicitly instructed to include changelogs. This significantly reduces the number of files processed for local preview builds, which cuts startup time of the documentation preview by half and improving the ergonomics of working with preview documentation locally.
+
+To force the inclusion of the changelogs, run the documentation build with `INCLUDE_CHANGELOGS=1` in your environment. For example, the following will run the preview build, including changelogs:
+
+```shell
+ov env INCLUDE_CHANGELOGS=1 just documentation/serve
+```
```

---

Let me know if these requests make sense, or if you would like help implementing them, and thanks as always for the contribution @kb-0311 :pray:

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
I meant to add that feedback to a request changes comment, sorry for the double ping.

**Comment by kb-0311** [comment]
@sarayourfriend Added the suggestions as well in the new commit, please do take a look when you are free. 

And thanks a lot for the help : )

**Review by sarayourfriend — APPROVED** [review]
LGTM! I was able to test this locally by building with `CI=1` and seeing the changelogs show up still and everything works perfectly. This is such a significant improvement, thanks again @kb-0311 :rocket:

**Pull request merged**
