### PR TITLE
Remove `body` from the index.update elasticsearch requests

### LINKED ISSUE #2776: The elasticsearch-py is deprecating `body` parameter in index.update calls in version 9
## Problem

There is a deprecation notice in the API test logs:
```
  /api/api/models/media.py:272: DeprecationWarning: The 'body' parameter is deprecated for the 'update' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
    getattr(es, method)(
```

## Description

`body` parameters should be moved to the top-level parameters of the request.

## Additional context

I opened this issue (and the related PR) because at first I thought this might be important before the final upgrade to ES 8 on staging, but then I realized that the deprecation was postponed to version 9.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2776 by @obulat

## Description

This PR updates the calls to es update to match what's expected in version 9 and remove the deprecation notice.

## Testing Instructions

Check the CI logs: there should be no deprecation notice as in the linked issue. The tests checking for the update calls were updated, and they should pass.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by krysal — APPROVED** [review]
Looks great!

**Review by sarayourfriend — COMMENTED** [review]
@obulat Can you confirm if this is compatible with ES 7? Production is still stuck on ES 7 until we can debug why the queries were taking so much longer on the ES 8 cluster.

**Comment by sarayourfriend** [comment]
Just doing one last test locally with ES7 because I've just realised that I think we don't have tests that _actually_ exercise the ES interaction: the calls are mocked out so they never hit ES directly.

**Review by sarayourfriend — APPROVED** [review]
Okay, I was able to test it locally by:

```
OPENVERSE_ES_VER=7.12.0 just api/init
```

And then creating a confirmed media report and checking that the document for the media object was updated with `mature=true` :+1:

**Comment by sarayourfriend** [comment]
The test failed due to the issues discussed in #800 :cry:

**Pull request merged**
