### PR TITLE
Remove MediaViewSet's lookup regex

### PR DESCRIPTION
**Pull request by krysal**
## Description

Since the upstream issue (encode/django-rest-framework#6789) is fixed, it's safe to remove this workaround to handle invalid UUID-like strings. This way, DRF handles better these requests and responses are consistent with the rest.

### Response in production

https://api.openverse.org/v1/images/000000000000000000000000000000000000/related/

Screenshot 2024-12-12 at 12-35-51 Not Found

### Response in this branch

http://localhost:50280/v1/images/000000000000000000000000000000000000/related/

Screenshot 2024-12-12 at 12-32-37 Related – Django REST framework

## Testing Instructions

Run the API, `just api/up`, and check other invalid UUIDs from the original issue (WordPress/openverse-api#729) if you wish.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog PRs) or the media properties generator (`ov just catalog/generate-docs media-props` for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
The change looks good. I couldn't find any preexisting tests for bad regexes in the path, should we add one to `api/test/unit/views/test_media_views.py`?

**Review by dhruvkb — APPROVED** [review]
_duplicate_

**Comment by krysal** [comment]
@dhruvkb There is a test for the detail view:

https://github.com/WordPress/openverse/blob/c4acdf8f0de7926c7a529efecfd95ad8e9c518dc/api/test/integration/test_media_integration.py#L312-L316

Of course, I can also add another one for the related endpoint. However, this starts to step into the realm of testing Django Rest Framework functionality.

I'll need some help with the error from the schemathesis tests, tho. It's failing because the content types are not matching, which makes sense, but I don't see where that can be fixed. Perhaps you or @obulat, who has more knowledge of these tests, can identify it more easily. Those docs tests have been highly inconsistent in my local environment, too.

> E       1. Undocumented Content-Type
> E       
> E           Received: text/html; charset=utf-8
> E           Documented: application/json

**Review by dhruvkb — APPROVED** [review]
The changes look good to me, thanks for monitoring `TODO`s and resolving them.

I found a few things missing, and a fix for schemathesis that I've  pushed to a follow up PR #5276. Please review that PR, merge it into this and then this into `main`.

**Pull request merged**
