### PR TITLE
Create `@openverse/eslint-plugin` package with inagural rule for analytics config

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes the same issue as https://github.com/WordPress/openverse/pull/1125 but using ESLint instead of TypeScript, which allows for much more descriptive and helpful error messages.

## Description

- Create new `@openverse/eslint-plugin` package and setup scaffolding necessary for local packages including testing, typescript, etc.
- Add `@openverse/eslint-plugin` to the base eslint configuration
- Create `@openverse/analytics-configuration` rule to lint the events configuration

TODO:
- Get frontend unit tests running locally. For some reason I can't run the frontend unit tests locally successfully at all, even after recloning the repository, clearing my pnpm cache to redownload all packages, running the tests on main.
- Setup scripts for continuously building packages to make development easier. This should be possible via tsc's watch: https://www.typescriptlang.org/docs/handbook/configuring-watch.html

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I still intend to work on this, I just haven't had time this week yet. I'll try to make some headway on it today if I can but it might have to wait until next week.

**Comment by sarayourfriend** [comment]
Unfortunately I still cannot run the frontend tests locally, not even on main :cry: That leaves me completely blocked on further work on this PR until I can resolve that, but I'm literally all out of ideas on how to do so. I spent a bit of time trying to quickly get the tests running inside of docker, just to see if it's an environment issue, but even that fails. When I run the tests inside Docker, they fail with the same exact errors.

I'm at a loss, at this point. I don't know why the tests pass on `main` anywhere else or why they would fail inside a docker image. I tried to think of what environmental issues might exist, but I can't think of any that shouldn't also affect CI, and CI doesn't do anything special as far as I can tell. At least not anything that I'm not also doing on my local.

**Comment by sarayourfriend** [comment]
Switching to ESLint FlatConfig would make this a lot easier: https://eslint.org/blog/2022/08/new-config-system-part-2/#from---rulesdir-to-runtime-plugins

Though it looks like this could have used `--rulesdir` to begin with, avoiding much of the complications.

In any case, it'll be a lot easier once #2224 is merged and the configuration is simplified, especially with respect to the pre-commit configuration, which was a pain!

**Comment by krysal** [comment]
@sarayourfriend Now that #2224 is this blocked onto something else?

**Comment by sarayourfriend** [comment]
Nope! I've just been working on high priority stuff right now.

This PR needs to be re-written, so I'm going to close this PR and open an issue to assign to myself for this.

**Pull request closed without merging**
