### PR TITLE
Allow runtime configuration of nginx listening port

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Related to https://github.com/WordPress/openverse-infrastructure/pull/648

## Description

ECS FARGATE requires that container and host ports match on a container definition. In the related PR we tried to map Nuxt to a different host port, in order to allow Nginx to listen on 8443 so that the target group port doesn't need to change. We did that by juggling the _host_ ports, but we can't have different host and container ports. Nuxt lets you override the port by passing `-p`, but we need to enable runtime configuration of the Nginx port by using an environment variable.

The net change in this PR is that you should be able to pass `OPENVERSE_NGINX_LISTEN_PORT` environment variable to the container and have Nginx listen on a port other than 8080. Proof that it works is in the fact that it still listens to 8080 now, as that is set as the default for that variable in the container build.

## Testing Instructions

Run `just build frontend_nginx && just frontend/up` and confirm you can still access the `frontend_nginx` service at `localhost:50290`. You also need to run the frontend locally on port `8443` using `just frontend/dev`

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
I tried changing the port from 8080 to something else locally, and saw that `docker-compose.yaml` port needs to change, too:

https://github.com/WordPress/openverse/blob/90396b2a0484658acc052009f7bd89d6fc66e380/docker-compose.yml#L333

Once this value is updated, the nginx listening port setting using the env variable works well.

**Comment by sarayourfriend** [comment]
> Can we set the env variable on the parent directory? Or do we need to add documentation saying that the port needs to be updated if the env variable inside frontend/ directory is set to something different than 8080?

We can, but it's just support for testing a feature that shouldn't need to be tested after this. I guess if we want it to be an end-to-end test, we can set the variable in `docker-compose.yml`.

**Comment by obulat** [comment]
> > Can we set the env variable on the parent directory? Or do we need to add documentation saying that the port needs to be updated if the env variable inside frontend/ directory is set to something different than 8080?
> 
> We can, but it's just support for testing a feature that shouldn't need to be tested after this. I guess if we want it to be an end-to-end test, we can set the variable in `docker-compose.yml`. What is your suggested change?

I guess we will not change the 8080 locally anyways, so I'm going to approve this PR. I'm not sure if we should add a comment in `docker-compose` saying that 8080 can be changed using an environment variable in the `frontend/.env`.

**Review by obulat — APPROVED** [review]

**Review by dhruvkb — APPROVED** [review]
LGTM!

**Pull request merged**
