### PR TITLE
generate-dag-docs recipe move DAGs.md to documentation folder

### LINKED ISSUE #1847: Include DAGs.md in documentation
## Description

The catalog emits a `DAGs.md` file that contains a lot of great information about the DAGs. This file is a very good candidate for inclusion in the documentation site.

## Implementation

It's unclear how a file that's written inside the `catalog/` dir (for Docker container bind mount reasons) could be included in the docs. One approach might be symlinks but I'm unaware of how good support for symlinks is in Git and on Windows.

### PR DESCRIPTION
**Pull request by ngken0995**
## Fixes

Fixes #1847  by @dhruvkb 
## Description

- Move the created DAGs.md to the top level documentation folder.
- Edit the generate-dag-docs recipe from [justfile](https://github.com/WordPress/openverse/blob/50005d1aec1dc37694fc128a44d3a7e008e4313f/catalog/justfile#L123) to move and lint DAGs.md.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [N/A] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@ngken0995 This is a great start and you're on the right track. These are the further steps that need to be taken.

- The existing `DAGs.md` file in `catalog/` must be deleted. Git should be able to recognise the delete+create action as a moved file.
- The `DAGs.md` file should not be in the root of the docs project. `documentation/catalog/reference/` would be more appropriate.
- The file will also need to be included in the table of contents else it will be dangling and the docs will fail to build.

**Comment by AetherUnbound** [comment]
Oh dang, it looks like the Myst parser is a little upset about the format of DAGs.md 😅 Let me see what changes might be necessary to make it compatible.

**Comment by AetherUnbound** [comment]
I've made two changes:

1. References to header titles are now appropriately using `-` instead of `_` to separate words
2. All headers have been increased by 1 level so that only "DAGs" shows in the TOC on the left (previously all 3 of the major headers were showing up as individual pages in the TOC when all linked back to the same page anyway).

Once the doc page builds successfully, we should be good to go!

**Comment by ngken0995** [comment]
Hello @AetherUnbound,

Thank you for making the commits. Where can I find the TOC? Is it in the GitHub repo?

**Comment by AetherUnbound** [comment]
The table of contents should show up on the rendered preview once that task succeeds in our CI. Apologies, it looks like I broke some tests! I'll fix those and then we should be able to see the preview 🙂

**Comment by AetherUnbound** [comment]
Ah okay, unfortunately the preview won't be generated for this PR since it's from a fork. You can preview this file locally by running `just documentation/install`, then `just documentation/build -W && just documentation/serve` and visiting the page http://localhost:50231/catalog/reference/DAGs.html locally! I've confirmed the file looks good 🙂

**Review by AetherUnbound — APPROVED** [review]
LGTM! Thanks for all your effort on this @ngken0995 😄

**Review by dhruvkb — APPROVED** [review]
LGTM, thanks for your contribution @ngken0995!

**Comment by AetherUnbound** [comment]
Page is now live 🙂 https://docs.openverse.org/catalog/reference/DAGs.html

**Comment by ngken0995** [comment]
Awesome!

**Pull request merged**
