### PR TITLE
Add a script to generate the media_properties.md

### LINKED ISSUE #2186: Create a script to automatically generate media properties
## Problem

This is the first part of the [Documenting Media Properties in the Catalog](https://docs.openverse.org/projects/proposals/document_all_media_properties/20230426-implementation_plan_documenting_media_properties.html) project.

## Description

Create the script that parses SQL DDLs and Python column definition files to generate the markdown file for the documentation site.

Doing steps 1 and 2 from the [implementation plan](https://docs.openverse.org/projects/proposals/document_all_media_properties/20230426-implementation_plan_documenting_media_properties.html#outlined-steps-parallelizable-workstreams) in the same PR will make testing this much easier: you would just invoke the just script to run the documentation generation.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2186 by @obulat

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
Based on the SQL requests results in https://github.com/WordPress/openverse/issues/244 and the table in [this PR preview](https://docs.openverse.org/_preview/2205/meta/media_properties.html), there are some inconsistencies.

## Data inconsistencies

### Nullable columns

The database fields that are `nullable` in DDLs but don't have any `NULL` values in the database
- `identifier` 
- `ingestion_type`
- `provider` (there is an index on it, in combination with `foreign_identifier)
- `source`
- `foreign_identifier` (there is an index on it, in combination with `provider`)
- `foreign_landing_url`
- `license` (no data in the linked issue, but there should be no row without a license)
- `license_version`

**Comment by sarayourfriend** [comment]
@obulat What is the status of this PR? Is it still being worked on or is it blocked? Do you need help with anything to get it ready for review or would pairing with someone help?

**Comment by obulat** [comment]
This PR is drafted until the Additional search views project is finished.

**Comment by obulat** [comment]
Closing this PR for now, will reopen when this project is restarted.

**Pull request closed without merging**
