### PR TITLE
Fix image and audio result focus rings

### LINKED ISSUE #3193: Wrong focus style in image components
## Description

Box and large variants of image component mirror the focus style of the small variant instead of having the ["bold filled" style](https://docs.openverse.org/storybook/?path=/story/meta-focus--bold-filled) applied. This creates a visual inconsistency in some breakpoints of Image results, and on all breakpoints of "All content" results.

On the other hand, small variant's focus style is correct, except for the radius value. It should be 2px instead of 4px.

Focus version of image component. Border radius is highlighted

### All content flow
1. Search anything and land on the All content results
2. Navigate through the results area with your keyboard
3. See how focus styles change between image and audio items.

https://github.com/WordPress/openverse/assets/895819/750ecf05-f4a9-4ccd-8966-1ce1df6b8db9

### Image flow
1. Search anything on a big device
2. Land on the All content results
3. See how the focus style is different than its [design](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4050-9023&mode=dev).

https://github.com/WordPress/openverse/assets/895819/48239842-252d-45ca-b76a-d06aca21ec68

### LINKED ISSUE #3525: Wrong focus style in image component
## Description

In "All content" and "Image" results, image components have the wrong focus style applied in its `large` variant. The correct styles are [documented](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4050-9020&mode=dev) in the Design Library. Screenshot attached below.

Design documentation of Image components in Openverse's Design Library

## Reproduction

1. From a laptop or a bigger screen go to Openverse
2. Search anything and land on "All content" results
3. Navigate with your keyboard and set the focus on an image result
4. See the error. Keep navigating until focus on an audio track for comparison of the focus ring.
5. Repite the process but on step 2 land on "Image" results instead

### Image component in "All content" results

Screenshot of All content results with image component focused

### Image component in "Images" results

Screenshot of Images results with image component focused

## Additional context

If I remember correctly, I started seeing this bug once #2891 was completed. But I might be wrong.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #3525 by @fcoveram
Fixes #3193 by @fcoveram 
Related to #4911 by @zackkrida 

## Description

This PR updates `focus-bold-filled` to set the inner ring to the color of the page background. It also updates the focus ring for the non-square image result.

The inner ring looks narrower in dark theme than it does in the light theme, ~~so I updated the width for the dark theme.~~ but I think it just seems so, and the ring is actually of the same width.

Initially, I tried to use `focus-slim-offset` class, but the way it creates the offset made the rounded corners look bad: they were wider than the ring itself. That's why I updated it to use `focus-slim-tx`, like the audio track uses, but also added padding and negative margin to add "offset".

Edited to add: with the current implementation of `focus` classes based on `*` selector, it is not possible to use `focus-bold-filled` with `sm:` prefixes, as required by the designs (style for image result grid is `focus-slim` on `xs` breakpoint, but `fold-filled` on larger breakpoints). I changed the `*focus-bold-filled` to `.focus-bold-filled` to match the class exactly. This class should only be used with `focus-visible:` prefix, to prevent css interference.

I had to fix the z-index to stop audio focus ring overlapping the audio instructions snackbar.

## Testing Instructions

Check the result focus rings for image, audio and all content results.
You can use the storybook to view [image cell](https://docs.openverse.org/_preview/4959/storybook/?path=/story/components-vimagecell--default&args=aspectRatio:square&globals=viewport:sm;theme:dark) and the [audio result](https://docs.openverse.org/_preview/4959/storybook/?path=/story/components-audio-track--box-small&globals=viewport:xs;theme:dark)s

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by fcoveram — COMMENTED** [review]
I see the storybook components correctly, but I don't see changes on any of the three search results when I run dev.

> The inner ring looks narrower in dark theme than it does in the light theme, so I updated the width for the dark theme.

Is this happening in the designs?

**Comment by obulat** [comment]
> I see the storybook components correctly, but I don't see changes on any of the three search results when I run dev.

I've updated the PR, and it should look correct in both places now.

> > The inner ring looks narrower in dark theme than it does in the light theme, so I updated the width for the dark theme.
> 
> Is this happening in the designs?

I think it's just that it seems narrow, but actually isn't. Could you check?

**Comment by fcoveram** [comment]
Everything looks good now

**Review by fcoveram — CHANGES_REQUESTED** [review]
I fully missed the instruction section describing how this PR involves the three types of results. Sorry. My previous reviews were only for the All content results.

That being said, the only error I see is the focus style in "Image" results on breakpoints from `sm` to above. Instead of being `slim`, it should be `bold`. Just like audio and image items on "All content" results.

Here is a table of the current and expected styles.

| Dev | Expected |
|:---|:---|
| CleanShot 2024-10-08 at 17 14 49@2x | CleanShot 2024-10-08 at 17 15 57@2x |

**Review by fcoveram — APPROVED** [review]
It looks great now 👏 ✨ 🚀

**Pull request merged**
