### PR TITLE
Prevent unnecessary post-process results recursion

### LINKED ISSUE #2415: `_post_process_results` does not check if any hits exist before making additional pagination requests
## Description

`_post_process_results` attempts to "fill the requested page". However, it never checks if the page can be filled based on the total number of hits available on the query reported by Elasticsearch.

## Reproduction

1.  Run the server locally on `main` and observe unnecessary recursive calls to `_post_process_results` when making this request: `http://0.0.0.0:50280/v1/images/?q=bird%20perched&page_size=20&page=3&filter_dead=True`

That particular request works because it has a half-filled page on the last page of live links. To get the recursive calls, `filter_dead` must be enabled and you must have a results set that does not fill the page size.

## Fix

In addition to checking that `start + end > ELASTICSEARCH_MAX_RESULT_WINDOW`, also check `start + end > search_results.hits.total.value`.

This diff fixed it for me locally, but I think there are some edge cases we need to consider for when `query_size == hits` :thinking: 

```diff
diff --git a/api/api/controllers/search_controller.py b/api/api/controllers/search_controller.py
index def66bb34..e18bf388e 100644
--- a/api/api/controllers/search_controller.py
+++ b/api/api/controllers/search_controller.py
@@ -206,7 +206,12 @@ def _post_process_results(
             ```
             """
             end += int(end / 2)
-            if start + end > ELASTICSEARCH_MAX_RESULT_WINDOW:
+            query_size = start + end
+            cannot_fulfill_query_size = (
+                query_size > ELASTICSEARCH_MAX_RESULT_WINDOW or
+                query_size > search_results.hits.total.value
+            )
+            if cannot_fulfill_query_size:
                 return results
 
             s = s[start:end]
```

After applying the fix, we should see a single call to `_post_process_results` for the example query.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #2415 by @sarayourfriend 

## Description

Stops `_post_process_results` recursion once the total available hits have been exhausted. Previously, if queries were unable to fill the page_size with live links, `_post_process_results` would continue to iterate until the ES max page depth was met.

For some reason the `Hit` `__repr__` was suddenly failing for me and causing tests to incorrectly fail (call argument mocks use `repr`, apparently). The fix for this was to ensure the document `_id` is a string. Here is the error I was seeing:

```
self = <[TypeError('sequence item 1: expected str instance, int found') raised in repr()] Hit object at 0x7f34bb326c90>

    def __repr__(self):
        return "<Hit({}): {}>".format(
>           "/".join(
                getattr(self.meta, key) for key in ("index", "id") if key in self.meta
            ),
            super(Hit, self).__repr__(),
        )
E       TypeError: sequence item 1: expected str instance, int found
```

`self.meta.id` was an `int`. Changing the factory to pass a string here (which does match ES's actual response type) fixed the issue.

## Testing Instructions

Make sure you understand how to reproduce the error on `main`, follow the reproduction instructions in the issue.

Once you've done that, check out this branch and try to reproduce the issue. You should not be able to. With the example in the issue, you should see a single call to `post_process_results`.

The unit test attempts to cover the case where additional calls to `post_process_results` are needed to fill the first or last page of a query. It becomes increasingly complex to test the more calls to `post_process_results` we want to assert, but I can try to add more unit tests if we want examples of recursion depth greater than 2 in the unit tests. The unit tests are also fairly complex, if reviewers have any ideas for how to simplify (and especially how to _clarify_ them), please share.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I'm not sure why the test fails in CI but passes locally. I'll try adding a more strict matcher on the request body in case something else is making the request and causing pook to use the wrong response, somehow. I cannot reproduce it locally, though :cry:

**Comment by sarayourfriend** [comment]
Re-running just to see if the test is flaky or always wrong. It's failed several times now so I suspect CI is doing something slightly different that I'm not expecting... just not sure how to anticipate it.

**Comment by sarayourfriend** [comment]
Aha! I'm able to reproduce it locally now by adding the redis fixture to the first test. Debugging now :slightly_smiling_face:

**Review by stacimc — COMMENTED** [review]
Noting that if you test with search terms including `bird` as suggested, you'll need to pass `mature=true` as well to get results.

I was able to reproduce the bug on main and verify the fix here -- I can see that there are no more recursive calls 💯  I wanted to verify that dead links are still filtered but was not able to get a test working yet as I've gone down a few ES rabbit holes.

I do not get the errors that I see in CI when running the tests locally, but I *do* get multiple errors of the form:

```
E           pook.exceptions.PookNoMatches: pook error!
E
E           => Cannot match any mock for the following request:
E           ==================================================
E           Method: POST
E           URL: http://es:9200/image-filtered/_search
```

I'm having trouble following the tests. Do you mind commenting them more extensively?

**Comment by sarayourfriend** [comment]
> I'm having trouble following the tests. Do you mind commenting them more extensively?

Can you share where you're losing track specifically? It's hard to know exactly what to comment without potentially over-complicating the explanation. Unfortunately this part of the code is complicated and the test complexity mirrors that. T

**Review by obulat — APPROVED** [review]
This is a really welcome change! From 11 to 1 requests 👍

**Review by stacimc — APPROVED** [review]
> I'm going to mock out SearchContext to remove at least that part of the test implementation details.

This honestly goes a long way to simplify the test setup and helps considerably -- thanks for humoring me :)

**Pull request merged**
