### PR TITLE
Remove `just` executions without arguments from CI

### LINKED ISSUE #3223: Remove `just` output from CI job
## Description

The CI job runs `just` without any arguments and prints a beautiful, albeit redundant, list of all available recipes. This should be removed.

## Reproduction

See [this log](https://github.com/WordPress/openverse/actions/runs/6570432186/job/17847941436).

### PR DESCRIPTION
**Pull request by bermr**
## Fixes #3223 

Fixes #3223 by @dhruvkb 

## Description

Removes `just` call from some jobs

## Testing Instructions

Run the ci

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — APPROVED** [review]
This LGTM, verified the unwanted output is now missing from the CI jobs. Adding @dhruvkb as second reviewer.

**Review by dhruvkb — COMMENTED** [review]
When `install_deps` is false, can you also remove the `install_recipe` param as that no longer has any effect? I can approve the PR after that.

An even better solution would be to not have the `install_deps` param at all and instead skip the installation step if `install_recipe` is a blank string. Would you like to do that @bermr? It's okay if you don't want to, the first part is also adequate.

**Comment by bermr** [comment]
Hey @dhruvkb, thanks for replying. Added commits with the changes requested.

**Review by dhruvkb — APPROVED** [review]
This is incredible, thank you so much @bermr! LGTM.

**Comment by bermr** [comment]
Thank you too!

**Pull request merged**
