### PR TITLE
Make `ov clean` work when a container, image or volume does not exist

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description

This PR
- adds `|| true` to clean commands to make them pass when a particular container, image or volume does not exist.
  - I needed this today to clean my volume but I had already removed the container.
- changes `kill` to `stop` to allow the commands to gracefully exit.
  - Use of `kill` lead to a stuck Git process on my computer.
- uses the full form of the commands.
  - This one is just personal preference but I find `docker image rm` clearer than `docker rmi`.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`./ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`./ov just catalog/generate-docs media-props`
      for the catalog or `./ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM! I had an issue where `stop` took forever for some reason. If I run into it again, I may open a PR to make it configurable (`ov clean --kill` or something to activate the hard "just do it" mode :sweat_smile:)

**Comment by dhruvkb** [comment]
@sarayourfriend please feel free to update this PR while we wait for a second approval. That seems like a good idea.

**Review by AetherUnbound — APPROVED** [review]
I ran into the exact issues you described, and this worked great for fixing it for me!

**Comment by sarayourfriend** [comment]
I'll do the `--kill` option as a separate PR to get this fix in :+1:

**Pull request merged**
