### PR TITLE
Focus the trigger when content setting modal is closed

### LINKED ISSUE #4337: The content settings button should be focused when the modal is hidden
## Description

On a narrow screen, when you close the content settings modal, the trigger (Content settings button) should be focused. Instead,  the body gets the focus.

## Reproduction

1. Go to https://openverse.org/search?q=cat, and narrow your screen.
2. Click on the content settings button inside the search bar.
3. Press <kbd>Tab</kbd>
4. See error: the content setting button is not focused. If you press <kbd>Tab</kbd> again, you'll see that "Skip to content" button is focused, which shows that the body was focused when the modal was hidden.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #4337 by @obulat

## Description

This PR adds the `triggerElement` prop to the `VInputModal`'s modal content to focus the trigger when modal is hidden.
In addition, it also fixes the search bar button: when they are focused, only the inner focus ring is visible instead of the current broken two rings:

Screenshot 2024-05-15 at 8 14 15 PM

## Testing Instructions

1. Go to http://localhost:8443/search?q=cat, and narrow your screen to mobile width.
2. Click on the content settings button inside the search bar.
3. Press <kbd>Tab</kbd>
4. The content setting button should be focused (with a pink ring around it).
5. Compare this with the production: on openverse.org/search?q=cat, follow the same steps. Nothing should look focused.  If you press <kbd>Tab</kbd> again, you'll see that "Skip to content" button is focused, which shows that the body was focused when the modal was hidden.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`just catalog/generate-docs media-props`
      for the catalog or `just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Do you mind adding testing instructions for this PR @obulat?

**Comment by obulat** [comment]
> Do you mind adding testing instructions for this PR @obulat?

Sorry, I've written the reproduction in the issue, and must have mixed that with the testing instructions :) Updated now.

**Review by zackkrida — APPROVED** [review]
Much better! #3195 was distracting while testing :laughing: but nice work.

**Review by AetherUnbound — APPROVED** [review]
Admittedly, I'm not able to see any difference between prod and my local copy when testing this 🤔 But the code looks good!

**Pull request merged**
