### PR TITLE
Use `add-to-project-and-label` action

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #818 by @obulat

## Description

This PR adds an external TypeScript action that adds an issue to the [Openverse project](https://github.com/orgs/WordPress/projects/75) and sets the Project's Priority custom field value based on the issue's label. The action is based on the `add-to-project` action.

You can see a successful run here: https://github.com/bulatt3/mobile_test/actions/runs/4620463360 (Please ignore the more than 40 unsuccessful runs 😆 )

I think it would be best to move the action to a /WordPress/ repository, but it would be nice to test it before the move.

## Testing Instructions

Merge and see

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
I was about to say that `bulatt3/add-to-project-and-label` seems to be on an unstable version, before I realised you're @bulatt3! Which led me to wonder if it's easier to build on top of #1130 and include this package inside the repo itself?

**Comment by obulat** [comment]
> I was about to say that `bulatt3/add-to-project-and-label` seems to be on an unstable version, before I realised you're @bulatt3! Which led me to wonder if it's easier to build on top of #1130 and include this package inside the repo itself?

Yes, I've created that organization some time ago :) 
That's a great approach, @dhruvkb,  I was looking for something similar before going with what I did here. 
I would love to move these changes on top of #1130. It seems that the changes there are at least a week away from being merged, and I would really love to try if this automation works before that...

**Review by dhruvkb — APPROVED** [review]
We can merge it into the monorepo later. Let's give it a go.

**Review by AetherUnbound — APPROVED** [review]
I dig it, let's give it a shot!

**Pull request merged**
