### PR TITLE
Update close buttons

### LINKED ISSUE #467: Part of the focus outline on the popover close button is cut off
## Description

If you focus the license explanation popover's close button using your keyboard, you will see a cut-off focus outline.

## Reproduction

1. Search for something on desktop. Make sure that the filters sidebar is open.
2. Navigate to the license explanation (the circular `?` button) using your keboard.
3. Click on the license explanation button.
4. See error: the focus outline is only visible on the left and bottom sides of the button, and the right and top sides are cut-off (for LTR layouts)

## Screenshots
Screenshot 2023-02-01 at 1 44 33 PM

## Additional context
First reported by @dhruvkb

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #467 by @obulat

## Description

This PR replaces `VCloseButton` with `VIconButton` for the close button in several components. This uses the updated button styles and removes the old button styles from the app.

### The license explanation popup
On desktop widths
Screenshot 2023-10-19 at 10 51 38 AM

### The report popup
Single result pages, both desktop and mobile widths
Screenshot 2023-10-19 at 11 21 23 AM

### The pages modal
Content pages, i.e. `/about`, on mobile widths
Screenshot 2023-10-19 at 11 22 07 AM

### The content settings modal
Search page on mobile widths
Screenshot 2023-10-19 at 11 23 05 AM

### Notification bar
Dark mode on homepage, light mode on the search page
Screenshot 2023-10-19 at 11 23 35 AM

Screenshot 2023-10-19 at 11 23 17 AM

### Modal content
External sources form, images search page
Screenshot 2023-10-19 at 11 31 11 AM

This is a part of the effort of replacing `VOldIconButton` that is used by `VCloseButton`. Now, the only component that uses `VCloseButton` is the global audio player, which will be updated in a separate PR since the design was changed recently.

## Testing Instructions

Run the app and open the search page (localhost:8443/search/?q=cat) on a desktop width. 

For the license explanation button, open the filters sidebar and click on a license explanation button `(?)`. Check that the close button's focus ring looks correct.
Check other buttons listed in the description of the PR.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by fcoveram — CHANGES_REQUESTED** [review]
The update looks great, I noticed some room for improvement to reach more consistency with other recent upgrades.

### The license explanation popup

The button should be `small / transparent / gray`, and the icon change to `close`

### The report popup

The button should be `small / transparent / gray`, and the icon change to `close`

### The pages modal

The change is correct

### The content settings modal

The size (`large`) is correct, but it needs to be `transparent / gray`, and the icon change to `close`

### Notification bar

The change is correct

### Modal content

The change is correct

**Comment by obulat** [comment]
Buttons updated

> ### The license explanation popup
> The button should be `small / transparent / gray`, and the icon change to `close`

Screenshot 2023-10-19 at 5 52 51 PM


> ### The report popup
> The button should be `small / transparent / gray`, and the icon change to `close`

Screenshot 2023-10-19 at 5 53 47 PM

> ### The content settings modal
> The size (`large`) is correct, but it needs to be `transparent / gray`, and the icon change to `close`

Screenshot 2023-10-19 at 5 54 20 PM

The snapshots changed for the content settings modal were updated.

**Review by fcoveram — APPROVED** [review]
It looks great ✨ 🚀

**Review by dhruvkb — APPROVED** [review]
Is the `VCloseButton` component being deprecated/removed?

Nothing against this PR, the changes LGTM but I have some objection to the design itself that I want to bring to @fcoveram's notice. The cross button is now much bigger than all other iconography in the app.

Screenshot 2023-10-27 at 3 44 40 PM

If need be, it can be tackled separately.

**Comment by obulat** [comment]
> Is the `VCloseButton` component being deprecated/removed?

Yes, it's being removed because it's using the old button underneath. There's one CloseButton left in the Global audio player, but that should be updated separately because the global audio player styles have changed.

> Nothing against this PR, the changes LGTM but I have some objection to the design itself that I want to bring to @fcoveram's notice. The cross button is now much bigger than all other iconography in the app.

@fcoveram, I'm going to merge this PR, but if you agree with @dhruvkb, we can update the size in a different PR.

**Comment by fcoveram** [comment]
I agree the icon variant looks bigger, but the idea is to be consistent with modal and dialogs hierarchy.

Modals (metasearch, settings drawer, and media details' designs) and popovers (report, and license explanation) use the big version, whereas messages use the small one.

**Pull request merged**
