### PR TITLE
Add `catalog/init` just command

### PR DESCRIPTION
**Pull request by krysal**
## Fixes
An inconvenience of having to turn up the whole stack for testing catalog-only changes.

## Description

This PR adapts the `load_sample_data.sh` script to accept an option for only loading the upstream DB data. Luckily the script was modular enough to make this a pretty easy change. Kudos to @dhruvkb here! This way the API command can continue working as usual.

## Testing Instructions

Run the new command and try querying the upstream DB to see it's filled. This process returns zero results in `main`.

```sh
just catalog/recreate
just catalog/pgcli
```

```sql
SELECT COUNT(*) FROM image;
```

```sql
-- Result must be:
+-------+
| count |
|-------|
| 5000  |
+-------+
SELECT 1
```

Also, confirms the `just recreate` and `just api/recreate` commands continue working as expected.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [n/a] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
I don't know about why the `catalog/DAGs.md` changes are a part of this PR but everything else looks great. It should save a lot of valuable CI time!

**Comment by AetherUnbound** [comment]
Agreed on the Flickr DAG changes, it might be best to have that as a separate PR since it's unrelated to the `just` changes. When I try and run this on its own without any other commands, I get the following:

```
$ j catalog/init
cd .. && ./load_sample_data.sh -c
Loading upstream DB data...
error: Recipe `init` failed on line 68 with exit code 1
```

Should the `init` recipe maybe define some dependencies so you can run `init` even if the containers are down?

Beyond that, the changes look good and I was able to test that `j catalog/recreate` succeeded locally!

**Comment by dhruvkb** [comment]
I agree with @AetherUnbound's note to have the `init` command depend on a recipe that brings up the containers. The API `init` has this:

https://github.com/WordPress/openverse/blob/21c17c8c6e7699afe48c5e155b8b83f8ef3e93cb/api/justfile#L45

**Comment by krysal** [comment]
There were some problems rebasing. Closing in favor of #2915. Sorry the trouble!

**Pull request closed without merging**
