### PR TITLE
Remove boto3 dependency

### LINKED ISSUE #2305: Remove `boto3` dependency and the s3 configuration from the API
## Problem

We are not using Amazon buckets from the API side and for the time being, it will not be necessary.

## Description

As the title says, remove this from the Pipfiles and the code related to S3 configs, including the environment variable(s) from template files.

## Alternatives

Find a use for this package 😀

## Additional context

#2301 and older dependabot updates.

### PR DESCRIPTION
**Pull request by ngken0995**
## Fixes

Fixes #2305  by @krysal 

## Description

Remove boto3 dependency from api folder because api doesn't use API bucket.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
You will also need to update the lockfile. The ideal way to uninstall a package (that updates both the `Pipfile` and `Pipfile.lock`) is to open a shell into the `web` container and use Pipenv to uninstall the deps.

```bash
[host]$ just api/exec bash
[docker]$ pipenv uninstall boto3
```

**Comment by ngken0995** [comment]
@dhruvkb I couldn't get the command running properly. I went on the docker desktop and locate the `openverse-web-1` container exec prompt and ran `pipenv uninstall boto3`. I believe this did the job to remove boto3 from `Pipfile `and `Pipfile.lock`

**Comment by ngken0995** [comment]
@dhruvkb Build Docker images for api and api_nginx is failing because my Pipfile.lock (466a7e) is out of date and expecting (4c22ae). How can I resolve for this to pass?

**Comment by dhruvkb** [comment]
`Pipfile.lock` records a checksum of the `Pipfile` to ensure that they're in sync. In this PR, this checksum is not matching and so the image refuses to build.

https://github.com/WordPress/openverse/actions/runs/6342392983/job/17228114541?pr=3073#step:7:381

To fix this, I would recommend hard resetting to `origin/main`, building a fresh image of the `web` service, exec-ing into the container and then removing Boto. This should look like these steps.

```bash
$ just dc build web
$ just api/up
$ just dc up -d --force-recreate web
$ just dc exec web bash
[docker]$ pipenv uninstall boto3
[docker]$ exit
$ git add Pipfile Pipfile.lock
```

Lmk how it goes.

**Comment by ngken0995** [comment]
once I run `pipenv uninstall boto3` There is an error which state `PermissionError: [Errno 13] Permission denied: '/api/.__atomic-writecd0k9b0a'`.

result traceback:

```
Traceback (most recent call last):
  File "/venv/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/cli/command.py", line 287, in uninstall
    retcode = do_uninstall(
              ^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/routines/uninstall.py", line 171, in do_uninstall
    do_lock(project, system=system, pypi_mirror=pypi_mirror)
  File "/venv/lib/python3.11/site-packages/pipenv/routines/lock.py", line 89, in do_lock
    project.write_lockfile(lockfile)
  File "/venv/lib/python3.11/site-packages/pipenv/project.py", line 1003, in write_lockfile
    with atomic_open_for_write(self.lockfile_location, **open_kwargs) as f:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pipenv/utils/locking.py", line 209, in atomic_open_for_write
    f = NamedTemporaryFile(
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 563, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 560, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/api/.__atomic-writecd0k9b0a'

```

**Comment by dhruvkb** [comment]
Yeah, this seems like a setup issue but we'll need more info to determine why permissions are not working as exepcted (also seen in another PR where Playwright wouldn't run). I'll tag @AetherUnbound and @sarayourfriend here as they are the maintainers who have active Linux dev machines and might be able to help more.

Meanwhile, you can skip the part where we exec into the dev container and run the commands on the host. The main reason for doing this in the host was to avoid OS-related issues but if you're on Linux, that should not be necessary.

```bash
$ git reset --hard origin/main
$ cd api/
$ pipenv uninstall boto3
$ git add Pipfile Pipfile.lock
```

**Comment by ngken0995** [comment]
@dhruvkb Thank you for the guidance. It works and all the git actions have passed.

**Review by dhruvkb — APPROVED** [review]
All good, thanks for the contribution @ngken0995!

**Comment by sarayourfriend** [comment]
> Meanwhile, you can skip the part where we exec into the dev container and run the commands on the host. The main reason for doing this in the host was to avoid OS-related issues but if you're on Linux, that should not be necessary.

@dhruvkb I wasn't aware that it was possible to run `pipenv` inside the container. Is that something you use on a regular basis? It would save a _lot_ of time when making changes to dependency if we worked that way because it removes the requirement to rebuild the container after changing `Pipfile`.

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Comment by dhruvkb** [comment]
Yes @sarayourfriend I mostly always use Pipenv inside the container, because it prevents the needless small diff changes between running Pipenv on a Mac vs Linux. IIRC Pipenv changes some metadata based on the OS, so running it in the container reduces this.

**Pull request merged**
