### PR TITLE
Add get-image-tag as dependency for nginx build step

### LINKED ISSUE #908: `SEMANTIC_VERSION` is not supplied to nginx image
## Description

Identified by @sarayourfriend

At present, the API is not showing a version at https://api.openverse.engineering/version:

```json
{

    "release": "",
    "environment": "production"

}
```

I've tracked this down to `SEMANTIC_VERSION` not being set at the build step here: 

https://github.com/WordPress/openverse/blob/d4b166818044fc7f0974e2055e9b39c2b2de645d/.github/workflows/ci_cd.yml#L432

It looks like this field was empty at the last release run:

https://github.com/WordPress/openverse/actions/runs/4367187713/jobs/7638243862

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #908 by @AetherUnbound

## Description

This PR adds the `get-image-tag` step as a dependency (via `needs`) of the nginx job which actually uses that value when building the image. This was not previously defined as a dependency, and so while the action unfortunately didn't throw an error, it built the image without a version defined.

## Testing Instructions

We should be able to see that this builds the nginx image with the correct semantic version as part of the CI/CD run.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
Weird that GitHub wouldn't raise an error and just assume a blank. LGTM!

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
@AetherUnbound Can you add the same fix for the frontend build as well? It also does not show the version.

https://openverse.org/version.json

Otherwise, LGTM.

**Comment by AetherUnbound** [comment]
Oh excellent find @sarayourfriend, will do!

**Review by sarayourfriend — APPROVED** [review]
:rocket: Nice work finding the fix :slightly_smiling_face: So similar to the _last_ time we fixed this issue but still different enough that I'd be stumbling around a bit to figure it out :sweat_smile:

**Pull request merged**
