### PR TITLE
Upgrade to Elasticsearch 8 locally

### LINKED ISSUE #2567: Use Elasticsearch 8 locally
## Problem

We need to make sure Openverse will work with ElasticSearch 8 prior to upgrading our existing cluster.

## Description

Update the root docker compose to use version `8.8.2` of ElasticSearch, or whatever the latest version is at the time of experimentation. 

https://github.com/WordPress/openverse/blob/2f39baa19fecbbf26fe3be913770c26fe9d57794/docker-compose.yml#L184

Additionally we should carefully review the [migration guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.0.html) to make sure nothing we use has been deprecated or altered.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #2567 

## Description

This PR updates our local development stack to use ElasticSearch 8. I've reviewed the ES8 changelog and documentation. It doesn't appear we're using any relevant functionality which was deprecated or altered from ES7-8. Our usage of ES _generally_ is quite simplistic.

The frontend and API both work flawlessly with this ES8 cluster locally. I tried all available frontend filters to ensure queries of all types are working, along with the search syntaxes described in our search guide.

## Testing Instructions

Try the API locally; observe that CI passes.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
I tried it locally and about 48 tests failed.

**Comment by zackkrida** [comment]
@dhruvkb interesting, which tests?

**Comment by dhruvkb** [comment]
Mostly in the search controller, as to be expected, right?

**Comment by zackkrida** [comment]
Here's my local results of `just api/test`:

```shell
❯ just api/test
env COMPOSE_PROFILES="api" just ../up
env COMPOSE_PROFILES="api" docker-compose -f docker-compose.yml -f docker-compose.overrides.yml up -d
[+] Running 8/8
 ✔ Container openverse-cache-1             Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-upstream_db-1       Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-db-1                Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-es-1                Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-indexer_worker-1    Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-web-1               Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-ingestion_server-1  Running                                                                                                                                                                                                                                                                       0.0s
 ✔ Container openverse-proxy-1             Started                                                                                                                                                                                                                                                                       0.4s

================================================================================
                                 Service Ports
================================================================================
webserver (catalog):
-  http://0.0.0.0:9090  (→ 8080)
ingestion_server (ingestion_server):
-  http://0.0.0.0:50281 (→ 8001)
plausible (plausible/analytics):
-  http://0.0.0.0:50288 (→ 8000)
web (api):
-  http://0.0.0.0:50280 (→ 8000)
-  http://0.0.0.0:50230 (→ 3000)
es (docker.elastic.co/elasticsearch/elasticsearch):
-  http://0.0.0.0:50292 (→ 9200)
s3 (minio/minio):
-  http://0.0.0.0:5010  (→ 5000)
-  http://0.0.0.0:5011  (→ 5001)
db (postgres):
-  http://0.0.0.0:50254 (→ 5432)
upstream_db (upstream_db):
-  http://0.0.0.0:50255 (→ 5432)
cache (redis):
-  http://0.0.0.0:50263 (→ 6379)
================================================================================
just ../ingestion_server/wait # API profile includes ingestion server
just wait # API waits for ES in entrypoint
env DC_USER="opener" just ../exec web pytest
just dc exec -u opener  web pytest
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml -f docker-compose.overrides.yml exec -u opener web pytest
Test session starts (platform: linux, Python 3.11.4, pytest 7.4.0, pytest-sugar 0.9.7)
django: settings: conf.settings (from env)
rootdir: /api
configfile: pytest.ini
plugins: sugar-0.9.7, Faker-18.11.2, django-4.5.2, raises-0.11
collecting ...

Testing LOCAL environment
collected 559 items

 test/test_auth.py ✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                                                  2% ▎
 test/test_dead_link_filter.py ✓✓✓✓✓✓                                                                                                                                                                                                                                                                            3% ▍
 test/unit/controllers/test_search_controller.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                             32% ███▎
 test/unit/management/commands/test_generatewaveforms.py ✓✓✓✓✓✓                                                                                                                                                                                                                                                 33% ███▍
 test/unit/models/test_audio.py ✓✓✓✓                                                                                                                                                                                                                                                                            34% ███▌
 test/unit/models/test_media_report.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                         40% ████
 test/unit/serializers/test_audio_serializers.py ✓✓✓                                                                                                                                                                                                                                                            40% ████
 test/unit/serializers/test_media_serializers.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                         72% ███████▎
 test/unit/templates/test_admin_base_html.py ✓✓✓                                                                                                                                                                                                                                                                46% ████▋
 test/unit/utils/test_image_proxy.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                 98% █████████▊
 test/unit/utils/test_search_context.py ✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                              48% ████▉
 test/unit/utils/test_throttle.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                              54% █████▌
 test/unit/views/test_health_views.py ✓✓✓✓✓✓                                                                                                                                                                                                                                                                   100% ██████████
 test/unit/views/test_image_views.py ✓✓✓                                                                                                                                                                                                                                                                        55% █████▌
 test/unit/views/test_media_views.py ✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                                 57% █████▊
 test/test_audio_integration.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                               60% ██████
 test/test_backwards_compat.py ✓✓✓✓                                                                                                                                                                                                                                                                             61% ██████▏
 test/test_examples.py ✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                                                62% ██████▎
 test/test_image_integration.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                              65% ██████▋
 test/test_v1_integration.py ✓✓ss✓✓✓✓s✓✓✓✓s                                                                                                                                                                                                                                                                     68% ██████▊
 test/unit/configuration/test_link_validation_cache.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                          71% ███████▏
 test/unit/utils/test_attribution.py ✓✓✓✓✓✓✓                                                                                                                                                                                                                                                                    74% ███████▍
 test/unit/utils/test_check_dead_links.py ✓✓✓✓                                                                                                                                                                                                                                                                  74% ███████▌
 test/unit/utils/test_drf_renderer.py ✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                                                                                                                               76% ███████▋
 test/unit/utils/test_help_text.py ✓✓✓✓                                                                                                                                                                                                                                                                         77% ███████▊
 test/unit/utils/test_tallies.py ✓✓✓✓                                                                                                                                                                                                                                                                           99% █████████▉
 test/unit/utils/test_watermark.py ✓✓                                                                                                                                                                                                                                                                           99% █████████▉
 test/unit/utils/test_waveform.py ✓                                                                                                                                                                                                                                                                             99% █████████▉
====================================================================================================================================================== warnings summary ======================================================================================================================================================
../venv/lib/python3.11/site-packages/gunicorn/util.py:25
  /venv/lib/python3.11/site-packages/gunicorn/util.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2871
../venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2871
  /venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[image-Image-ImageReport-DeletedImage-ImageFactory]
test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[image-Image-ImageReport-DeletedImage-ImageFactory]
test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[audio-Audio-AudioReport-DeletedAudio-AudioFactory]
test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[audio-Audio-AudioReport-DeletedAudio-AudioFactory]
  /venv/lib/python3.11/site-packages/django/db/models/fields/related_lookups.py:52: RemovedInDjango50Warning: Passing unsaved model instances to related filters is deprecated.
    warnings.warn(

test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[image_media_type_config-has_confirmed_report-has_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[image_media_type_config-has_confirmed_report-has_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[image_media_type_config-has_confirmed_report-no_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[image_media_type_config-has_confirmed_report-no_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[audio_media_type_config-has_confirmed_report-has_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[audio_media_type_config-has_confirmed_report-has_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[audio_media_type_config-has_confirmed_report-no_sensitive_text]
test/unit/serializers/test_media_serializers.py::test_media_serializer_sensitivity[audio_media_type_config-has_confirmed_report-no_sensitive_text]
  /api/api/models/media.py:272: DeprecationWarning: The 'body' parameter is deprecated for the 'update' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
    getattr(es, method)(

test/unit/utils/test_watermark.py::test_sends_UA_header
test/unit/utils/test_watermark.py::test_long_title_wraps_correctly
  /api/api/utils/watermark.py:203: DeprecationWarning: getsize_multiline is deprecated and will be removed in Pillow 10 (2023-07-01). Use ImageDraw.multiline_textbbox instead.
    _, attribution_height = font.getsize_multiline(text)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

Results (88.72s (0:01:28)):
     555 passed
       4 skipped
```

**Comment by dhruvkb** [comment]
Wow, must be something wrong with my setup then!

**Comment by zackkrida** [comment]
Closing, we feel this validates exploring ES8 configuration in terraform and staging.

**Comment by zackkrida** [comment]
@WordPress/openverse-maintainers, @sarayourfriend pointed out to me that if this is working, we might as well switch to ES8 locally. What do you think?

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
LGTM, but can you revert bfee9304ac8f6dd443ed0d77f306e2637c31ceb2 before merging?

**Review by sarayourfriend — APPROVED** [review]

**Review by krysal — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
