### PR TITLE
Downgrade the API's python version back to 3.11

### LINKED ISSUE #4901: RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x55dc68caf9f0>; the handl...
Sentry Issue: [OPENVERSE-API-YE](https://openverse.sentry.io/issues/5807647157/?referrer=github_integration)

```
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x55dc68caf9f0>; the handler is closed
  File "uvloop/sslproto.pyx", line 714, in uvloop.loop.SSLProtocol._do_read
  File "uvloop/sslproto.pyx", line 699, in uvloop.loop.SSLProtocol._process_outgoing
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
    self._ensure_alive()
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
    raise RuntimeError(

Fatal error on SSL protocol
protocol: <uvloop.loop.SSLProtocol object at 0x7fbb6a8681a0>
transport: <TCPTransport closed=True reading=False 0x55dc68caf9f0>
```

### PR DESCRIPTION
**Pull request by krysal**
## Description

This PR downgrades the Python version to the previous one, 3.11.*, partially reverting #5095, to see if the API memory utilization slows down. Ideally, it should return to acceleration levels previous to release from [November 4th](https://github.com/WordPress/openverse/releases/tag/api-2024.11.04.06.41.58) (below 50% after 2 weeks).

Screenshot 2024-12-19 at 15-34-22 Dashboards ECS-Production-Dashboard CloudWatch us-east-1

The highest peak on the graph coincides with the update of aiohttp (#5165) but we wanted that to fix #4901. It may have been drived by the Django v5 upgrade too, see release from [2024.11.17](https://github.com/WordPress/openverse/releases/tag/api-2024.11.17.18.36.17). So it's easier to test the Python version downgrade first. If that doesn't alleviate the problem, we can go back to version 3.12 (or even further, bump to 3.13) and revert the aiohttp update.

I restricted the versions allowed in some API packages to avoid doing many updates of other dependencies here, and also had to loosen the required python version of the `openverse-attribution` package to be able to downgrade the API.

## Testing Instructions

```
just build
just api/up
```

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog PRs) or the media properties generator (`ov just catalog/generate-docs media-props` for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
Good catch, the slope of the memory consumption definitely seems higher on the right side of the Python version bump (although it didn't get to as high of a peak as it does later on). I can get behind your reasoning for trying this out.

That said, this PR still updates a number of packages (even major versions in some cases). I think those will make it harder to pinpoint if it really was the Python version upgrade that caused the leak, and if it really was the Python version downgrade that fixed it.

In this PR, there are
- patch upgrade in some packages: `aiohappyeyeballs`, `aiosignal`
- major upgrade in some packages: `anyio`, `asttokens`
- introduction of some new packages: `async-timeout`

Can we try downgrading the Python version, without changing any of the packages? I think PDM's [`--update-reuse` flag](https://pdm-project.org/en/latest/reference/cli/#lock) will avoid changes to the versions in the lock file wherever possible.

```bash
pdm lock --update-reuse
```

**Comment by krysal** [comment]
> Can we try downgrading the Python version, without changing any of the packages? I think PDM's [--update-reuse flag](https://pdm-project.org/en/latest/reference/cli/#lock) will avoid changes to the versions in the lock file wherever possible.

Good call! That was the reason I was removing `psycopg` in the first place, so the command could work, but somehow I forget about it in the middle, lol. Pushing the changes as requested.

**Review by dhruvkb — APPROVED** [review]
I looked through both the lock files and it seems everything is good there. None of the IO package pins are changing so we'll be able to determine if the Python version itself was the cause of the trouble.

The attribution package has a number of updates to its packages but those should not be blocking because they're not related to IO and cannot be associated with the memory leak.

**Review by AetherUnbound — APPROVED** [review]
Dang, that graph does look like trouble 😨 I've built this and run the API successfully locally, hope this addresses the issue! 🤞🏼

**Pull request merged**
