### PR TITLE
Run label check on every commit and label change

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

Follow up to https://github.com/WordPress/openverse-infrastructure/pull/326 which required label checks for all merges into main, this was causing issues where a maintainer had to add & remove labels to re-trigger the check so a PR could be merged.

This action was previously set up to only run when the labels on a PR change. Since we've made this a required check, it makes sense to have this run unconditionally on every PR commit so that the check can pass (or fail) appropriately prior to a merge.

## Testing Instructions

We might be able to see on this PR!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Shoot, now I'm worried that it'll interfere with the "Label new PR" action since those run quick and it might fail if the PR is submitted without labels but gets them from that action 😭 Let me see if we can actually expand the set of events rather than revert to the default set.

**Review by stacimc — APPROVED** [review]
I think this makes sense! LGTM, interesting problem. Thanks for jumping on it so fast

**Comment by AetherUnbound** [comment]
Okay, I think I've got a solution! This should now cover all the default PR actions (commits, opening, reopening, etc) _as well as_ when labels are updated. I'm going to let it run after this push, then try to change the labels to make sure the actions get triggered again.

**Comment by AetherUnbound** [comment]
Worked like a charm! 🥳

**Review by zackkrida — APPROVED** [review]
Ah, very nice, thanks for the work here!

**Review by stacimc — APPROVED** [review]
Re-approving, good catch :)

**Review by krysal — APPROVED** [review]
I was about to say it doesn't make much sense to me to run this action on every commit but it seems necessary, as this is the default config the [GH action project shows](https://github.com/agilepathway/label-checker#using-the-label-checker-action). Thanks for debugging this and finding the solution!

**Pull request merged**
