### PR TITLE
Update record count on about page

### LINKED ISSUE #3152: Update record count on about page
## Description

Our [about page](https://openverse.org/about) states:

> Openverse searches across more than 300 million images from open APIs and the Common Crawl dataset.

We should update this to reflect the fact that we're currently at over 700 million images _and audio_.

## Additional context

It looks like that value can just be updated here:

https://github.com/WordPress/openverse/blob/9952babb165927525057d3cc6355a2c9a3e38f0f/frontend/src/locales/scripts/en.json5#L81

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Fixes #3152 by @ujwalkumar1995

## Description
As suggested in the issue, this PR updates the record count on the home page.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you for your contribution, @ujwalkumar1995!

The visual regression tests are now failing because about page text has changed, and the saved snapshots do not match the rendered page. We need to update the snapshots by running `just frontend/run test:playwright -u`. Note that you will need to be running Docker for this to work.
Please, update the snapshots - or let us know, and we can update them for you if you have any problems. Then this PR will be ready 🚀

**Comment by ujwalkumar1995** [comment]
Hey @obulat 
Thank you for the heads up on the playwright tests.
I did try to run the playwright tests in local and update the snapshot as suggested by you. However I am running into the below error (attached screenshot). If you have some insights from the screenshot, please do let me know and I will try the fix. If not, please feel free to assign the issue to someone else who may be technically more capable of fixing the tests.
Screenshot 2023-10-06 145848

**Comment by obulat** [comment]
> If you have some insights from the screenshot, please do let me know and I will try the fix.

It appears that building the test image took longer than usual. In this case, you can try increasing the timeout here (do not commit the changes):

https://github.com/WordPress/openverse/blob/19dcc9a0e5d2b2e9b5ca6c559ab76761d070ba01/frontend/test/playwright/playwright.config.ts#L24

Try increasing it to something like 25 minutes:  `timeout: 60_000 * 25, `. If it still fails, I can update the snapshots for you.

**Comment by ujwalkumar1995** [comment]
Hey @obulat 
Increasing the timeout worked.
Thank you so much for the help.
I have updated the snapshot tests. Kindly review.

**Review by dhruvkb — APPROVED** [review]
LGTM, thanks for your contribution @ujwalkumar1995! Appreciate that you took the effort to update the screenshots as well.

**Review by obulat — APPROVED** [review]

**Pull request merged**
