### PR TITLE
Replaced `get_token_info` calls with the `request.auth.application`

### LINKED ISSUE #3514: Remove unnecessary `get_token_info`
## Current Situation

`get_token_info` entirely duplicates the functionality of the Oauth2 provider backend we use. All the information from `TokenInfo` is available from an authenticated request by way of DRF's implementation.

[The Oauth2 provider sets `auth` (by way of setting `access_token`) on the DRF request object to the `access_token` object, which already has `application` and `user` populated](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L417). The validator also calls `access_token.is_valid` which already checks the token expiry and does not populate `request.auth` if it is expired. Every aspect of `get_token_info` is an unnecessary duplication of what is already happening in the oauth request authentication.

DRF sets `auth` based on `access_token` here: https://github.com/encode/django-rest-framework/blob/0f39e0124d358b0098261f070175fa8e0359b739/rest_framework/request.py#L391

`request.auth.application` contains all the information that the `TokenInfo` object `get_token_info` returns has (and more!).

Most routes use the default throttle classes (only thumbnails and a select few others have special throttles, everything else including all search endpoints use the default throttle classes).

There are 7 default throttle classes that run on these requests: burst and sustained for each anon, standard oauth and enhanced oauth (6), in addition to the exempt oauth throttle. Each of these call `get_auth_token` (through the base class's `has_valid_token` method). Each call to `get_auth_token` causes up to two database queries but at minimum one. Each of these queries will be _identical_ each time a throttle calls `get_auth_token` for a given request. That is, the response will be exactly the same. Replacing these usages with `request.auth.<whatever>` instead of using the token info object from `get_auth_token` will remove at least 7 unnecessary additional database queries to every single search request (wow!).

## Suggested Improvement

Remove `get_token_info` and replace all usages of it with `request.auth`. `request.auth` will be an instance of `AccessToken` with `application` populated with the `ThrottledApplication` and the `User` instance for the token. Replace calls to `token_info.<whatever>` with `request.auth.<whatever>`. If `request.auth` is None, then either no token existed on the request or it was invalid. Nothing else needs to be checked.

We can also replace checks in serializers `request.user` and `request.user.is_anonymous` with just `request.auth is not None`, which should simplify the understanding of authentication in those code paths.

## Benefit

Remove a significant number of unnecessary queries in the throttle classes that happen on almost every single request.

Also we get to delete code, yay!

### PR DESCRIPTION
**Pull request by kb-0311**
## Fixes

Fixes #3514 by @sarayourfriend 

## Description

Incomplete PR, since during `test_throttle` we will need to reinitialize the `authed_request` fixture with the updated token each time.
Since earlier that was not needed as the saved access token used to be fetched from the database at every `get_cache_key` call with the `get_token_info`. So the test cases only needed to reinitialize the `access_token` fixture before. 
I am unfamiliar with `pytest` and `Django` testing so a little help would be appreciated regarding how to go about reinitializing the `authed_request` fixture or drop the use of fixture to simulate the mock request and instead use something else maybe @sarayourfriend thoughts? 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
Let's wait for #3505 to get merged, then we can rebase this PR and see what else is left with the tests. That other PR has a nice fix for some of what might be causing issues in this one.

**Comment by kb-0311** [comment]
@sarayourfriend any updates after the PR merge?

**Comment by sarayourfriend** [comment]
@kb-0311 I'm on holiday at the moment but just popping in so you don't think you're getting ignored! Please rebase the PR and then ping `@WordPress/openverse-api` for review :slightly_smiling_face:

**Comment by sarayourfriend** [comment]
@kb-0311 Just a heads up, I am rebasing this PR now and will push changes to the branch soon.

**Comment by sarayourfriend** [comment]
@kb-0311 I've pushed the changes.

@stacimc @dhruvkb can one of y'all take a look?

**Comment by kb-0311** [comment]
@sarayourfriend Yes, Thanks a lot for your help :)

**Review by stacimc — CHANGES_REQUESTED** [review]
Hi @kb-0311, thanks for your contribution! Do you mind updating the PR description now that this is ready for review?

This is looking great, but from the [issue](https://github.com/WordPress/openverse/issues/3514) I think there's a couple more things needed here.

I see a few more uses of `get_token_info` (in [oauth2_views.py](https://github.com/WordPress/openverse/blob/main/api/api/views/oauth2_views.py) and [response_headers_middleware.py](https://github.com/WordPress/openverse/blob/main/api/api/middleware/response_headers_middleware.py)) that we could replace. Once that's done, we can fully remove the `get_token_info` method.

Finally, in the serializers where you see checks like `request.user and request.user.is_anonymous`, we can replace that with just `request.auth is not None`.

**Comment by AetherUnbound** [comment]
Drafting until feedback can be addressed - @kb-0311 let us know if you would like any further pointers or assistance on this 🙂

**Comment by krysal** [comment]
@kb-0311 Would you be able to resume this work soon? We would appreciate it if you let us know in any case.

**Comment by kb-0311** [comment]
@krysal I am so sorry but I currently have my exams so won't be able to complete this PR till next week. 

By that time I think if anyone is interested they can push commits in this branch itself for the problem.

**Comment by sarayourfriend** [comment]
I've taken the liberty to go ahead and push a final version of this PR, with all required changes. I did so in a single commit, rebased on the current `main`, rather than updating the existing commits, because the conflicts were too pesky in each commit of the original branch to resolve.

I'm opening this back up for review and pinging @stacimc and @dhruvkb to request reviews on this PR, so we can finally get it merged.

**Comment by stacimc** [comment]
I fixed an issue with the logic for detecting `is_anonymous` (it was just inverted). I'm looking into the remaining test failure in the search controller; the authentication is determined correctly when I test _manually_ 👀

**Review by stacimc — APPROVED** [review]
@sarayourfriend thank you for pushing this along! I had to make some changes so I'm not sure what the best protocol is for approvals 😄  I'm going to request your review in case you'd like, but leave @dhruvkb as a reviewer as well.

I've tested this locally with and without authentication and all looks well to me. Happy to see the tests effectively catching things as well!

**Review by sarayourfriend — APPROVED** [review]
Considering the age of the PR, and the time it's taken to get reviews (and there are lots of other PRs that need reviews as well), I feel comfortable approving and merging this. A few different people have looked at this and the code was always _basically_ the same, with tweaks around the edges, so I think we agree on the overall approach. Tests are passing, so that's good enough for me :+1:

**Comment by sarayourfriend** [comment]
Thanks again @kb-0311 for kicking off this PR. It's a great performance improvement for our application and I'm excited to see it finally merged. Thank you especially for your patience in the review cycle these months.

**Pull request merged**
