### PR TITLE
Update `_AIRFLOW_DB_UPGRADE` to `_AIRFLOW_DB_MIGRATE`

### LINKED ISSUE #3077: Update `_AIRFLOW_DB_UPGRADE` to `_AIRFLOW_DB_MIGRATE`
## Description

The `_AIRFLOW_DB_UPGRADE` environment variable was recently deprecated: https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#the-db-init-db-upgrade-commands-and-database-load-default-connections-configuration-options-are-deprecated-33136

We will need to update this in the docker-compose file to `_AIRFLOW_DB_MIGRATE`:

https://github.com/WordPress/openverse/blob/0a5f1a4beaa27cfd5dd4d1baa10209b76f830924/docker-compose.yml#L115

## Reproduction

1. Run `just catalog/test-session`
2. Observe the following log line in the start up output:

```
WARNING: Environment variable '_AIRFLOW_DB_UPGRADE' is deprecated please use '_AIRFLOW_DB_MIGRATE' instead
```

### PR DESCRIPTION
**Pull request by 23198**
## Fixes

Fixes #3077 by @AetherUnbound 

## Description

The Airflow environment variable _AIRFLOW_DB_UPGRADE has been deprecated. Refer this link for details:-
https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#the-db-init-db-upgrade-commands-and-database-load-default-connections-configuration-options-are-deprecated-33136
To resolve this, the yaml configuration file has been updated with _AIRFLOW_DB_MIGRATE.

## Testing Instructions

With the Environment variable update to _AIRFLOW_DB_MIGRATE, just Run catalog/test-session and the environment variable deprecated warning will be removed.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
Hi, @23198! Thank you for your contribution! Could you please fill in the PR description and testing instructions? This is necessary for maintainers to review a PR.

**Comment by 23198** [comment]
> Hi, @23198! Thank you for your contribution! Could you please fill in the PR description and testing instructions? This is necessary for maintainers to review a PR.

Hi @obulat , description and testing instruction added. Thanks

**Review by krysal — APPROVED** [review]
Looks good to me!

**Review by AetherUnbound — APPROVED** [review]
Deprecation warning no longer appears, thanks for addressing this!

**Pull request merged**
