### PR TITLE
JavaScript to TypeScript

### LINKED ISSUE #2342: Use TypeScript for Tailwind config
## Problem

We are using CJS modules (with `module.exports`) for `screens` and `z-indices` because they are used by Tailwind config, which also uses CJS. Tailwind has recently added support for TS in config[^1], so we can move everything to TS.

## Description

Convert `frontend/tailwind.config.js`, `frontend/src/constants/screens.js` and `frontend/src/constants/z-indices.js` to TypeScript. There will be some changes to types (numbers might need to be wrapped in quotes). The `tsconfig` might also need to be updated.

## Alternatives

We could keep using JS with JSDoc. 

## Additional context

Nuxt 3 requires ESM, so this would be a great change to have.

[^1]: https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-type-script-support

### PR DESCRIPTION
**Pull request by Devanshi-Crypto**
## Fixes

Fixes #2342 by @obulat

## Description

- Converted JavaScript files to TypeScript
- Renaming tailwind.config.js to tailwind.config.ts 
- Removed tailwind-config-viewer to avoid conflicts with tailwind.config.ts

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@Devanshi-Crypto I reached out in Slack to let you know there as well, but I went ahead and rebased this branch and fixed the issue with unrelated changes showing up in the diff.

I also discovered that prettier was no longer working and that the configuration for the tailwind plugin needed to be updated as well as the plugin version itself to support the TypeScript configuration. I went ahead and did that as well to avoid further complicating an already complex PR for a first time contribution.

There are two remaining ESLint issues to resolve:

```
/home/sara/projects/openverse/frontend/src/constants/z-indices.ts
  18:4  error  tsdoc-undefined-tag: The TSDoc tag "@return" is not defined in this configuration  tsdoc/syntax

/home/sara/projects/openverse/frontend/tailwind.config.ts
  226:45  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```

You can see these if you run `just lint eslint` on this branch.

The explicit any warning we already discussed in the previous PR and can be resolved with the patch I shared there: https://github.com/WordPress/openverse/pull/2402#discussion_r1234687432

The other needs the referenced `@return` tag to be changed to `@returns` (with an `s` at the end) to match the TSDoc linter's expectation.

The type check already passes on this branch, so I think those are the final two changes required to finish this PR.

**Comment by sarayourfriend** [comment]
@Devanshi-Crypto Merging the `main` branch of your fork into this is going to inadvertently revert any changes merged to `main` on the upstream repo (this one). Before merging `main` from your fork into the branch, you should update `main` on the fork to match upstream. That's going to be hard though because the `main` branch on your fork is also a bit wonky. You can either (a) delete `main` on your fork and refetch it from upstream or (b) just merge upstream main into your branch instead of `main` from your fork. Let me know if you'd like help with either of these. Git can be a bit confusing when it gets this messy.

**Comment by Devanshi-Crypto** [comment]
> 

Yes, I get it. Sorry for this.

**Review by obulat — CHANGES_REQUESTED** [review]
The nuxt build errors are caused by `tailwind.config` still having the old extension in the nuxt config. It's best to replace all occurrences of `tailwind.config.js` with `tailwind.config.ts`

**Comment by obulat** [comment]
To prevent other bot pings, I'm going to draft this PR while the work is being done here.

**Comment by Devanshi-Crypto** [comment]
@obulat  Do you need anything from my end?

**Comment by obulat** [comment]
> @obulat Do you need anything from my end?

We've decided that we can go ahead with these changes and remove tailwind-config-viewer because it does not support ts, and we are not using it much.
So, now this PR is ready for review, and will be merged after two approvals. The information you provide in the PR description is important for the maintainers during the review, so could you fill in the description and testing instructions sections in the PR description, @Devanshi-Crypto?

**Review by obulat — APPROVED** [review]

**Comment by Devanshi-Crypto** [comment]
Yes thank you @obulat , I will do it ASAP.

**Comment by Devanshi-Crypto** [comment]
Converted JavaScript files to TypeScript
Renaming tailwind.config.js to tailwind.config.ts
Removed tailwind-config-viewer to avoid conflicts with tailwind.config.ts

**Review by sarayourfriend — APPROVED** [review]

**Comment by sarayourfriend** [comment]
Thank you @Devanshi-Crypto!

**Pull request merged**
