### PR TITLE
Update homepage copy to "700 million"

### LINKED ISSUE #839: Update homepage copy to "700 million"
## Problem

Openverse now includes over 700 million items, but the homepage only lists 600.

## Description

Update the copy to 700 million and update the homepage visual regression test snapshots.

### PR DESCRIPTION
**Pull request by Rishav1707**
## Fixes

Fixes #839 by @zackkrida

### Before
600_Millions

### After
700_Millions

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — DISMISSED** [review]
@Rishav1707 you will also need to update the snapshots of the homepage so that visual regression tests can pass.

**Comment by Rishav1707** [comment]
> @Rishav1707 you will also need to update the snapshots of the homepage so that visual regression tests can pass.

But how?

**Comment by obulat** [comment]
> > @Rishav1707 you will also need to update the snapshots of the homepage so that visual regression tests can pass.
> 
> But how? I didn't understand

The detailed instructions on how to run visual regression tests are here: https://github.com/WordPress/openverse/blob/main/frontend/test/playwright/README.md#running-the-tests The commands in that guide were not updated for the mono repository, you would need to use `just frontend/ run ...` instead of `pnpm run ...` now.

You will need to use the `-u` flag when running the test: `just frontend/run test:playwright visual-regression -u` to update the snapshots.

Please let us know if you'd like the maintainers to update the snapshots for you, that's fine too! Thank you for your contribution 🎉

**Comment by Rishav1707** [comment]
> > > @Rishav1707 you will also need to update the snapshots of the homepage so that visual regression tests can pass.
> > 
> > 
> > But how? I didn't understand
> 
> The detailed instructions on how to run visual regression tests are here: https://github.com/WordPress/openverse/blob/main/frontend/test/playwright/README.md#running-the-tests The commands in that guide were not updated for the mono repository, you would need to use `just frontend/ run ...` instead of `pnpm run ...` now.
> 
> You will need to use the `-u` flag when running the test: `just frontend/run test:playwright visual-regression -u` to update the snapshots.
> 
> Please let us know if you'd like the maintainers to update the snapshots for you, that's fine too! Thank you for your contribution 🎉

Yaah pls update the snapshots for me and thanku for your response 😊

**Review by obulat — APPROVED** [review]
I've added the updated snapshots, so now the tests are passing.

Thank you for your contribution, @Rishav1707 🌟

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
