### PR TITLE
Add `role="dialog"` to popover

### LINKED ISSUE #2076: VPopover is missing `role="dialog"`
## Description

As an element that appears on top of other content and contains focusable elements, `VPopover` should use `role="dialog"`.

## Additional context

See documentation: 
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2076 by @obulat
Related to #2020 by @sarayourfriend 

## Description

This PR adds `role=dialog` to the `VPopover` component for accessibility, and also updates the Playwright Visual regression tests to use `getByRole("dialog")` as selectors.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — DISMISSED** [review]
This might need verification from @fcoveram, but the spacing looks _really_ tight to me, especially when:

- There is a search term with descenders
- The sidebar is open

CleanShot 2023-05-12 at 14 11 05@2x

**Comment by zackkrida** [comment]
@obulat and @dhruvkb updated the priority to `critical` here to reflect the priority of the parent issue.

**Review by dhruvkb — APPROVED** [review]
^Meant to approve.

**Review by AetherUnbound — APPROVED** [review]
I wasn't sure how best to test this without any testing instructions. I ran the frontend locally and opened the report media popover and checked the HTML to see that it now has `role="dialog"`, hopefully that's sufficient along with the tests? The rest looks good to me!

**Comment by obulat** [comment]
> I wasn't sure how best to test this without any testing instructions. I ran the frontend locally and opened the report media popover and checked the HTML to see that it now has `role="dialog"`, hopefully that's sufficient along with the tests? The rest looks good to me!

Really sorry for the lack of instructions! Yes, that should be sufficient. Adding `dialog` role also changes the way some screen readers announce it.

**Pull request merged**
