### PR TITLE
Fix  Re-running failed Playwright tests leaves failure comment

### LINKED ISSUE #864: Re-running failed Playwright tests leaves failure comment
## Description

The order of Playwright tests is

- <4 parallel>
  - clean-playwright-failure-comment
  - nuxt-playwright-e2e
  - nuxt-playwright-vr
  - storybook-playwright
- playwright-test-failure-comment

When any one of the 3 Playwright test jobs fails, the CI workflow fails with it. If you re-run the workflow to run only the failed jobs, the job `clean-playwright-failure-comment` is not executed (as it had passed in the previous run), which leaves the failure comment even if the Playwright tests pass in the re-run.

## Solution

An easy solution is to move the comment removal steps from the `clean-playwright-failure-comment` job to the `playwright-test-failure-comment` job so that it can delete the existing comment, if any, and post a new comment, if needed.

### PR DESCRIPTION
**Pull request by AdarshRawat1**
## Fixes
Fixes - Playwright failure comment persists after re-running tests

Fixes #864 by @dhruvkb 

## Description
If any of the 3 Playwright test jobs fail, the entire CI workflow will fail. In case you re-run the workflow to execute only the failed jobs, the job clean-playwright-failure-comment will not run since it had passed in the previous run. This will result in the failure comment persisting even if the Playwright tests pass in the re-run.

Solution Implemented- 
Moved the comment removal steps from the `clean-playwright-failure-comment` job to the `playwright-test-failure-comment` job so that it can delete the existing comment, if any, and post a new comment, if needed.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
Please move all steps from `clean-playwright-failure-comment` to `playwright-test-failure-comment`. You've left the `peter-evans/find-comment` step in the previous job, leading to the `actionlint` error.

**Comment by AdarshRawat1** [comment]
Should I remove the remaining part of clean-playwright-failure-comment job?

**Comment by dhruvkb** [comment]
@AdarshRawat1 not remove, you should move those steps to the `playwright-test-failure-comment` job.

**Comment by AdarshRawat1** [comment]
@dhruvkb My code is failing this test, I tried fixing it but cannot find a solution to it, please help!
image
image

**Comment by AdarshRawat1** [comment]
I tried restoring the default steps of clean-playwright-failure-comment: job along with copied steps in playwright-test-failure-comment but still got the same error . I

**Review by obulat — APPROVED** [review]
The changes seem to be fine now, can't wait to see them in action. Thank you for your contribution, @AdarshRawat1!

**Comment by AdarshRawat1** [comment]
> The changes seem to be fine now, can't wait to see them in action. Thank you for your contribution, @AdarshRawat1!

Welcome, @obulat looking forward to contributing more to project.

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
