### PR TITLE
Add technology labels

### LINKED ISSUE #126: Add language labels
I propose we add language specific labels to make it easier for contributors to know what PRs they are capable of working on:

- `🐘 tech: PHP`
- `🐍 tech: Python`
- `🟨 tech: JavaScript`

As examples.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #126 by @zackkrida 

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
This is great! I'll recommend adding these:
- ? / Vue
- ? / Django
- ? / Airflow
- 🐳 / Docker

Seeing as many technologies don't have relevant emojis, it'd be nice to set a default for the category.

**Comment by AetherUnbound** [comment]
We probably also want something for "SQL" too!

**Comment by zackkrida** [comment]
Maybe `PostgreSQL` specifically, since people can get very opinionated about MySQL vs. Postgres

**Review by dhruvkb — APPROVED** [review]
LGTM<sup>2</sup>!

**Comment by AetherUnbound** [comment]
> Maybe `PostgreSQL` specifically, since people can get very opinionated about MySQL vs. Postgres

Sounds good to me, although now we have _two_ technologies that both use :elephant: lol

**Comment by zackkrida** [comment]
Maybe I'll use something like 💾, 🗃️,  or 🗄️ for Postgres haha

**Comment by zackkrida** [comment]
PostgreSQL added!

**Review by AetherUnbound — APPROVED** [review]
Love it!

**Comment by AetherUnbound** [comment]
The API already has a `python` issue type, will this conflict with that at all, or will it override it?

**Comment by zackkrida** [comment]
Let's find out! 🤣

**Comment by dhruvkb** [comment]
The script overwrites labels with the description and color if the label name matches. Otherwise, it makes a new label.

**Pull request merged**
