### PR TITLE
Unpin glibc

### LINKED ISSUE #3157: Remove pinned glibc update once docker images are updated
## Current Situation

#3154 adds explicit pinned updates to glibc in the Dockerfiles for the catalog airflow webserver, upstream_db, ingestion_server, and api to fix a security vulnerability not fixed in the python and airflow docker images.

## Suggested Improvement

Once the images are updated and the glibc version is verified, we can clean up the temporary updates in the docker files.

### PR DESCRIPTION
**Pull request by dhruvkb**
This reverts commit a1d0cc898f9fa1cab518b94f3b7e8b52175eb50c.

## Fixes

Fixes #3157 by @stacimc 

## Description

This PR unpins `glibc` that was pinned in #3154 as a security patch. With an updated `python3.11-slim` image containing the patched version of `glibc`, this is no longer necessary.

## Testing Instructions

0. Check the `glibc` version in the current `web` image (`ldd --version` shows this info).
1. Check out this PR and build the `web` image again.
2. Check that the `glibc` version does not change.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
LGTM!

**Review by AetherUnbound — CHANGES_REQUESTED** [review]
Unfortunately the `upstream_db` image (`postgres:13.10`) has not been updated ([taken from this comment](https://github.com/WordPress/openverse/pull/3154#pullrequestreview-1660996707) after running `just build && just up`):

```
$ for x in 'web' 'webserver' 'ingestion_server' 'upstream_db'; do echo "($x)" && j exec $x ldd --version | grep 'ldd' ; done
(web)
just dc exec -u root  web ldd --version
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml exec -u root web ldd --version
ldd (Debian GLIBC 2.36-9+deb12u3) 2.36
(webserver)
just dc exec -u root  webserver ldd --version
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml exec -u root webserver ldd --version
ldd (Debian GLIBC 2.31-13+deb11u7) 2.31
(ingestion_server)
just dc exec -u root  ingestion_server ldd --version
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml exec -u root ingestion_server ldd --version
ldd (Debian GLIBC 2.36-9+deb12u3) 2.36
(upstream_db)
just dc exec -u root  upstream_db ldd --version
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml exec -u root upstream_db ldd --version
ldd (Debian GLIBC 2.31-13+deb11u6) 2.31
```

Note that the last version is `11u6` and not `11u7`. We'll either need to leave that piece in for `upstream_db` or bump the version to `13.13` (which appears to be the current latest) and see if that includes the patched library.

**Comment by dhruvkb** [comment]
@AetherUnbound I can look into updates for this image, but I have a question. This is only for the local dev environment, we don't use Docker to host the production databases so is using an unpatched image for the DB even a risk at all?

**Review by AetherUnbound — APPROVED** [review]
🤦‍♀️ that's right, thanks for correcting me on that! No need to do anything specific for the upstream DB then since all the others are patched!

**Pull request merged**
