### PR TITLE
Fix: Remove unwanted leading/trailing whitespaces in attributions

### LINKED ISSUE #553: Trim leading/trailing whitespace from attribution copy button result

### PR DESCRIPTION
**Pull request by andrewscwei**
## Fixes

Fixes #553 by @ krysal

## Description

There are two issues that contributed to unwanted leading/trailing whitespaces around the attribution copy:
1. The translation used expects a `viewLegal` property, which is empty
2. The interpolated string has leading/trailing whitespace within the parent `<p>` element

## Testing instructions

1. Visit https://openverse.org/image/0fc8d459-6c59-4370-ae20-cc83c4a64e65 and copy all 3 of the options for attribution. Observe that they each have extra whitespace at the end, and both the HTML and plain text versions also have whitespace at the beginning
2. Run `just f` to start the frontend
3. Visit http://localhost:8443/image/0fc8d459-6c59-4370-ae20-cc83c4a64e65 and perform the same actions in step 1, observing that all 3 cases have no leading/trailing whitespace

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Thank you, @andrewscwei! This is a good fix and great catching the missing paragraph tag. The PR just needs to be linted to fix formatting, which you could do by either:

1. Running `just lint` locally
2. Applying this git diff (the result of me running `just lint` locally) by saving it to a file (`patch.diff`, for example) and using `git apply patch.diff`:

```diff
diff --git a/frontend/src/components/VMediaInfo/VCopyLicense.vue b/frontend/src/components/VMediaInfo/VCopyLicense.vue
index 2597e59b5..64512c60a 100644
--- a/frontend/src/components/VMediaInfo/VCopyLicense.vue
+++ b/frontend/src/components/VMediaInfo/VCopyLicense.vue
@@ -28,7 +28,9 @@
         :media-id="media.id"
         :media-type="media.frontendMediaType"
       >
-        <p id="attribution-html" class="break-all font-mono" dir="ltr">{{ getAttributionMarkup() }}</p>
+        <p id="attribution-html" class="break-all font-mono" dir="ltr">
+          {{ getAttributionMarkup() }}
+        </p>
       </VLicenseTabPanel>
       <VLicenseTabPanel
         :tab="tabs[2]"
diff --git a/frontend/src/utils/attribution-html.ts b/frontend/src/utils/attribution-html.ts
index c7435c74f..106d3b67b 100644
--- a/frontend/src/utils/attribution-html.ts
+++ b/frontend/src/utils/attribution-html.ts
@@ -244,7 +244,9 @@ export const getAttribution = (
     })
   }
 
-  const attribution = tFn("text", attributionParts).replace(/\s{2}/g, " ").trim()
+  const attribution = tFn("text", attributionParts)
+    .replace(/\s{2}/g, " ")
+    .trim()
 
   return isPlaintext
     ? attribution
```
3. Manually update the code to match this formatting :smile: 

Thank you so much!

**Review by zackkrida — CHANGES_REQUESTED** [review]
Thank you, @andrewscwei! This is a good fix and great catching the missing paragraph tag. The PR just needs to be linted to fix formatting, which you could do by either:

1. Running `just lint` locally
2. Applying this git diff (the result of me running `just lint` locally) by saving it to a file (`patch.diff`, for example) and using `git apply patch.diff`:

```diff
diff --git a/frontend/src/components/VMediaInfo/VCopyLicense.vue b/frontend/src/components/VMediaInfo/VCopyLicense.vue
index 2597e59b5..64512c60a 100644
--- a/frontend/src/components/VMediaInfo/VCopyLicense.vue
+++ b/frontend/src/components/VMediaInfo/VCopyLicense.vue
@@ -28,7 +28,9 @@
         :media-id="media.id"
         :media-type="media.frontendMediaType"
       >
-        <p id="attribution-html" class="break-all font-mono" dir="ltr">{{ getAttributionMarkup() }}</p>
+        <p id="attribution-html" class="break-all font-mono" dir="ltr">
+          {{ getAttributionMarkup() }}
+        </p>
       </VLicenseTabPanel>
       <VLicenseTabPanel
         :tab="tabs[2]"
diff --git a/frontend/src/utils/attribution-html.ts b/frontend/src/utils/attribution-html.ts
index c7435c74f..106d3b67b 100644
--- a/frontend/src/utils/attribution-html.ts
+++ b/frontend/src/utils/attribution-html.ts
@@ -244,7 +244,9 @@ export const getAttribution = (
     })
   }
 
-  const attribution = tFn("text", attributionParts).replace(/\s{2}/g, " ").trim()
+  const attribution = tFn("text", attributionParts)
+    .replace(/\s{2}/g, " ")
+    .trim()
 
   return isPlaintext
     ? attribution
```
3. Manually update the code to match this formatting :smile: 

Thank you so much!

**Comment by AetherUnbound** [comment]
@zackkrida Just a heads up that I think we'll actually need to have prettier ignore those particular lines I think. @andrewscwei and I determined that the cause was the whitespace _within the template_, which was being copied by the library we're using to copy into the clipboard. I believe Andrew will be applying a fix for the linting though so that prettier ignores those lines!

**Comment by zackkrida** [comment]
@AetherUnbound ah yes, newlines between tags and their contents in Vue components can behave weirdly with spaces. Sounds good!

**Review by andrewscwei — COMMENTED** [review]
@zackkrida [fe9c554](https://github.com/WordPress/openverse/pull/4066/commits/fe9c554afb6b312c8309513c736d93890f98e4a1) should have addressed the linting errors 

(had to add `prettier-ignore` so prettier doesn't insert new line due to line length restriction?)

**Review by AetherUnbound — APPROVED** [review]
Incredible finds! I was able to run the app locally to test and verify that no whitespace appeared before or after. Thanks for the contribution!

**Review by dhruvkb — COMMENTED** [review]
I could not reproduce the bug in either production or staging so I don't think I will be able to approve the changes in `VCopyLicense.vue` as I cannot tell if they fix the issue.

The change to `attribution-html.ts` LGTM as it removes the trailing space when `viewLegal` is not present.

**Review by zackkrida — APPROVED** [review]
Excellent! In production I have leading and trailing whitespace on these attributions and they're gone when testing the PR. Thanks for the contribution!

**Pull request merged**
