### PR TITLE
Dispatch deployment workflows from infrastructure repository

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes https://github.com/WordPress/openverse-infrastructure/issues/462 by @sarayourfriend 

I'll open a follow-up PR to remove the deployment workflows from this repository.

## Description

Dispatches the deployment workflows from the infrastructure repository using repository dispatch.

@dhruvkb You suggested we should use dispatch and wait, but I want to make sure that doesn't cause issues. Specifically it will block CI/CD from running on `main` while the staging deployments are awaited due to the concurrency setting. The release app workflow doesn't have that issue because the concurrency key includes the app name input. Staging deployments are only ~10 minutes or so but I wonder if we need CI on `main` to wait for them or if we can just rely on the fact that the upstream workflow will correctly handle concurrency and deploy things in order.

What do you think?

## Testing Instructions

Try release app from this branch and confirm it works. For CI/CD I think we just need to merge the PR and see if it works, though the code is almost identical to release app so theoretically there shouldn't be an operational difference.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
If the upstream workflow handles concurrency properly, I think it's okay to dispatch them and not wait for completion. We might want to keep an eye on the upstream backlog though because a rapid succession of PR merges on `main` might queue up a lot of back-to-back deployments in the upstream worfklow.

**Comment by sarayourfriend** [comment]
> We might want to keep an eye on the upstream backlog though because a rapid succession of PR merges on main might queue up a lot of back-to-back deployments in the upstream worfklow.

This was already the case though, right? Do you have any ideas for how best to keep an eye on the deployment queue? I would prefer not to add additional Slack notifications for deployments.

**Review by AetherUnbound — APPROVED** [review]
LGTM! Are there any pieces of documentation that also need to be updated alongside this change?

**Review by zackkrida — APPROVED** [review]
LGTM 🤞. Thanks for explaining `max_time`.

**Comment by sarayourfriend** [comment]
> LGTM! Are there any pieces of documentation that also need to be updated alongside this change?

Yes, in the monorepo. I'll do that in the PR there.

**Pull request merged**
