### PR TITLE
Silence pnpm peer dependency version warnings

### LINKED ISSUE #4733: Peer dependency issue post Nuxt 3
## Current Situation

There is a peer dependency issue since Nuxt 3:

```
  WARN  Issues with peer dependencies found
frontend
├─┬ @nuxt/test-utils 3.13.1
│ ├── ✕ unmet peer vitest@"^0.34.6 || ^1.0.0": found 2.0.4
│ ├── ✕ unmet peer @vitest/ui@"^0.34.6 || ^1.0.0": found 2.0.4
│ └─┬ vitest-environment-nuxt 1.0.0
│   └─┬ @nuxt/test-utils 3.13.1
│     ├── ✕ unmet peer vitest@"^0.34.6 || ^1.0.0": found 2.0.4
│     ├── ✕ unmet peer @vitest/ui@"^0.34.6 || ^1.0.0": found 2.0.4
│     └─┬ vitest-environment-nuxt 1.0.0
│       └─┬ @nuxt/test-utils 3.13.1
│         ├── ✕ unmet peer vitest@"^0.34.6 || ^1.0.0": found 2.0.4
│         └── ✕ unmet peer @vitest/ui@"^0.34.6 || ^1.0.0": found 2.0.4
└─┬ @sentry/node 8.20.0
  └─┬ @opentelemetry/instrumentation-mongodb 0.46.0
    └─┬ @opentelemetry/sdk-metrics 1.23.0
      ├── ✕ unmet peer @opentelemetry/api@">=1.3.0 <1.9.0": found 1.9.0 in @sentry/node
      ├─┬ @opentelemetry/core 1.23.0
      │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.9.0": found 1.9.0 in @sentry/node
      └─┬ @opentelemetry/resources 1.23.0
        └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.9.0": found 1.9.0 in @sentry/node
```

## Suggested Improvement

Add the peer dependencies required to resolve the warnings _or_ suppress them by other means.

cc @obulat

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #4733 by @sarayourfriend

## Description

~~This PR adds the current versions of packages to `allowedVersions` in pnpm to remove the warnings.~~
This PR updates the versions of Sentry-related packages and Vitest to remove the deprecation warnings when running `pnpm install`

## Testing Instructions

To make `pnpm` print warnings about peer dependencies, run `ov pnpm upgrade adm-zip`. You should not see the warnings from the issue.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@obulat can you add an explanation in the PR description why silencing these rather than resolving them is the appropriate course of action?

For example, if we updated `@nuxt/test-utils`, the vitest peer dependency would include vitest@2.x.x that we are on: https://github.com/nuxt/test-utils/blob/main/package.json#L111

For the Sentry ones, it looks like we can resolve this by either regenerating the lockfile or may just manually fixing the versions in the lockfile: https://github.com/getsentry/sentry-javascript/issues/13219#issuecomment-2271311500

Either way, it doesn't look like silencing these warnings is the _only_ way to solve this PR, and whenever we do so, we should make sure to document why we are doing it and when we would stop doing it. Peer dependency ranges aren't (in theory) declared without reason or intent. We should assume they are worth trying to address and match, even if things seem to work as they are, unless there's a good reason why we absolutely cannot (e.g., a dependency has declared a constraint on a package version with security vulnerabilities and later versions are tested and safe for our usage, a rare case, and one where we might question whether the package declaring the peer dependencies is well maintained enough for us to continue using it!).

**Review by sarayourfriend — DISMISSED** [review]
Requesting changes to either document in the PR description why we are forcing these versions to be allowed rather than fixing them or (ideally) to actually just fix the warnings as described in my other comment.

**Comment by obulat** [comment]
> Requesting changes to either document in the PR description why we are forcing these versions to be allowed rather than fixing them or (ideally) to actually just fix the warnings as described in my other comment.

Thank you for this request!
I tried removing the lock file and re-installing to fix the opentelemetry issue, but that didn't help. Then I added an override in the `package.json` to install the latest version of `opentelemetry/api`, which _did_ fix the issue. Then I just removed everything under the `pnpm` key in the top-most `package.json` since we don't need that anymore.

**Review by zackkrida — APPROVED** [review]
Great to see updated dependencies and removed overrides. LGTM.

**Pull request merged**
