### PR TITLE
Add concurrency settings for workflow

### LINKED ISSUE #267: Prevent concurrent action runs across all repositories
## Problem

It is currently possible for someone to push a branch several times and trigger multiple concurrent runs of GitHub actions.

## Description

We can follow the example from the Gutenberg repository to prevent this:

```
# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true
```

https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/bundle-size.yml#L27-L32

This would need to be added to each action individually in each repository. There may be actions that should not have this but I'm not sure.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by alrz1999**
## Fixes

Related to #267 by @sarayourfriend 

## Description

This pull request Adds concurrency settings for workflow

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Hi @alrz1999, this looks excellent. To close the parent issue #267 this will need to be implemented in a few other repositories:

- https://github.com/WordPress/openverse-api
- https://github.com/WordPress/openverse-catalog
- https://github.com/WordPress/openverse-frontend

Would you be interested in making pull requests for those repositories as well?

I believe this PR looks good, though. Thank you for your contribution!

**Review by zackkrida — APPROVED** [review]

**Review by sarayourfriend — APPROVED** [review]

**Comment by sarayourfriend** [comment]
@alrz1999 Thanks for the contribution! Can you run the linter locally by running `just lint` in the root directory and then committing the automated changes? Once that is done we can merge this PR :rocket:

**Comment by zackkrida** [comment]
Also @alrz1999 apologies that I forgot to mention that some workflows are synced across repositories (see this comment for details):

https://github.com/WordPress/openverse-frontend/pull/1881#pullrequestreview-1130808296

**Comment by sarayourfriend** [comment]
Thanks @alrz1999, congrats on the merge :tada:

**Pull request merged**
