### PR TITLE
Improve testing import behavior for the catalog

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

Try this one neat trick to make your python imports easier!™ _(delete the top level `__init__.py`)_

While attempting to experiment with solutions for @obulat's media generation PR (https://github.com/WordPress/openverse/pull/3620#discussion_r1548883284), I realized that we could drastically improve our testing import setup simply by removing the top level `__init__.py` file. I can't entirely explain the behavior, but as I understand it, putting an `__init__.py` there told pytest that the top level module was actually `catalog`. For myself though, this broke PyCharm's imports because I couldn't have _both_ a project defined at `catalog/` _and_ have it be a module (e.g. `from catalog import ...`) at the same time.

This PR removes the `__init__.py` file, and corrects all the instances in tests where we're importing from `catalog.` to import one module deeper. This is a huge DX improvement for me, because now I have code referencing where I previously did not! It should also help with #3620 in preventing us from having to manually alter the system path.

## Testing Instructions

- CI should pass
- Running `just c` to run the catalog should behave as expected
- Running `just catalog/generate-dag-docs` should succeed as normal

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
I tried rebasing #3620 onto this PR. 

After removing the `sys.path.insert`, to make the `justfile` work, I had to update the import files in `generate_media_properties.py`:
`from catalog.utilities.media_props_gen.helpers.column_parser` -> `from helpers.column_parser`
But then, running tests, I get this error:
```
tests/utilities/media_props_gen/test_generate_media_properties.py:5: in <module>
    from utilities.media_props_gen.generate_media_properties import (
utilities/media_props_gen/generate_media_properties.py:14: in <module>
    from helpers.column_parser import (  # noqa: E402
E   ModuleNotFoundError: No module named 'helpers'
```

It is complicated because we need to run the scripts within Docker and in test setup.

I don't know what change I'm requesting, but this change is not fixing the problem in my PR :(

**Comment by AetherUnbound** [comment]
@obulat I have a fix for the other PR which I'll share there, I still think this change is the appropriate one to make in order to make the imports work better with IDEs! I will note that because of the way Airflow works with importing DAGs, we always need to add the DAGs folder to the `PYTHONPATH` (however an IDE enables that): https://github.com/WordPress/openverse/blob/f8c634502895a1285892a1af130d15152a775836/catalog/Dockerfile#L18

**Review by stacimc — APPROVED** [review]
This has really bothered me as well, kudos for actually looking into it! I think this makes sense per [these docs](https://stackoverflow.com/a/50169991) 🤔 Tests and other `just` commands look great 👍

**Review by obulat — APPROVED** [review]
Thank you for figuring out the setup for #3620!
I did try changing the `PYTHONPATH`, but I used the dockerfile instead, so it didn't work correctly.
Nice that we could also find and remove the other `sys.path.insert` ✨

**Comment by obulat** [comment]
@AetherUnbound, I'm going to go ahead and merge this PR to make #3620 ready for re-review.

**Pull request merged**
