### PR TITLE
Fix sensitive term reindex query

### LINKED ISSUE #2328: Sensitive terms list produces too many clauses for create filtered index call
## Airflow log link

https://airflow.openverse.engineering/log?execution_date=2023-06-04T00%3A32%3A02.977074%2B00%3A00&task_id=wait_for_create_and_populate_filtered_index&dag_id=create_filtered_audio_index&map_index=-1

> **Note**: _Airflow is currently only accessible to maintainers & those given
> access. If you would like access to Airflow, please reach out to a member of
> @WordPress/openverse-maintainers_.

Exception from the ingestion server:

```
2023-06-04 00:32:12,485 WARNING base.py:288 - POST http://openverse-elasticsearch-prod.private:9200/_reindex?slices=auto&wait_for_completion=true [status:400 request:0.960s]
2023-06-04 00:32:12,485 ERROR tasks.py:220 - Error processing task `CREATE_AND_POPULATE_FILTERED_INDEX` for `audio`: RequestError(400, 'search_phase_execution_exception', 'too_many_clauses: maxClauseCount is set to 1024')
	2023-06-03T17:32:12.539-07:00	Process Process-5:
	2023-06-03T17:32:12.541-07:00	Traceback (most recent call last):
	2023-06-03T17:32:12.541-07:00	File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
	2023-06-03T17:32:12.541-07:00	self.run()
	2023-06-03T17:32:12.541-07:00	File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
	2023-06-03T17:32:12.541-07:00	self._target(*self._args, **self._kwargs)
	2023-06-03T17:32:12.541-07:00	File "/ingestion_server/ingestion_server/tasks.py", line 217, in perform_task
	2023-06-03T17:32:12.541-07:00	func(model, **kwargs) # Directly invoke indexer methods if no task function
	2023-06-03T17:32:12.541-07:00	^^^^^^^^^^^^^^^^^^^^^
	2023-06-03T17:32:12.541-07:00	File "/ingestion_server/ingestion_server/indexer.py", line 525, in create_and_populate_filtered_index
	2023-06-03T17:32:12.541-07:00	self.es.reindex(
	2023-06-03T17:32:12.541-07:00	File "/venv/lib/python3.11/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
	2023-06-03T17:32:12.541-07:00	return func(*args, params=params, headers=headers, **kwargs)
	2023-06-03T17:32:12.541-07:00	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	2023-06-03T17:32:12.541-07:00	File "/venv/lib/python3.11/site-packages/elasticsearch/client/__init__.py", line 1467, in reindex
	2023-06-03T17:32:12.541-07:00	return self.transport.perform_request(
	2023-06-03T17:32:12.541-07:00	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	2023-06-03T17:32:12.541-07:00	File "/venv/lib/python3.11/site-packages/elasticsearch/transport.py", line 466, in perform_request
	2023-06-03T17:32:12.541-07:00	raise e
	2023-06-03T17:32:12.541-07:00	File "/venv/lib/python3.11/site-packages/elasticsearch/transport.py", line 427, in perform_request
	2023-06-03T17:32:12.541-07:00	status, headers_response, data = connection.perform_request(
	2023-06-03T17:32:12.541-07:00	^^^^^^^^^^^^^^^^^^^^^^^^^^^
	2023-06-03T17:32:12.541-07:00	File "/venv/lib/python3.11/site-packages/elasticsearch/connection/http_requests.py", line 216, in perform_request
	2023-06-03T17:32:12.541-07:00	self._raise_error(response.status_code, raw_data)
	2023-06-03T17:32:12.541-07:00	File "/venv/lib/python3.11/site-packages/elasticsearch/connection/base.py", line 328, in _raise_error
	2023-06-03T17:32:12.541-07:00	raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
	2023-06-03T17:32:12.541-07:00	elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'too_many_clauses: maxClauseCount is set to 1024')
```

## Description

The most recent audio data refresh that ran over the weekend was the first run using the new sensitive terms list (see https://github.com/WordPress/openverse-infrastructure/pull/522). This sensitive terms list (not linked due to the sensitive nature) is almost 2k items long.

The default clause count in ES7 is 1024, but it [apparently was raised to 4096 in ES8](https://stackoverflow.com/a/73566889).

We will need to either find a workaround or increase this configuration value for the cluster in order to proceed.

## DAG status

Left enabled since pausing it may affect the data refresh itself.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #2328 by @AetherUnbound 

## Description

See the issue for the long explanation for why we are switching to `terms` query.

The summary is that:
- `terms` queries allow exact matching, fixing a separate issue where the terms were still querying tokenised text, resulting in false positives
- `terms` queries are subject to a separate, much higher limit than other queries.

## Testing Instructions

I can't test this locally due to #2362. I've executed the equivalent query against staging with the actual sensitive terms list and confirmed it does not cause any clause count errors.

You should be able to `just down -v && just api/up && just api/init` and then see a successfully created filtered index. All existing tests should pass without modification.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
    - I can't do this, see testing instructions above.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I've got my local environment fixed so I can see now that the issue causing the test to fail is that the filtered index includes all documents :clown_face: Debugging it now.

**Comment by sarayourfriend** [comment]
Fix and ready for review.

**Comment by zackkrida** [comment]
Did some initial local testing and while my local cluster health is `yellow` for some reason, likely unrelated to this PR, I was able to see the filtered indices successfully created. 4657 records in the filtered image index 👍. I'll give this a more in depth review later but it looks perfect so far.

**Review by obulat — APPROVED** [review]
It was really interesting to read how you came up with this solution :) 
The changes look correct, and they tested well locally for me.

**Comment by sarayourfriend** [comment]
Thanks for the reviews y'all.

> while my local cluster health is yellow for some reason

This is expected for the local cluster. Can you open an issue for us to either fix this for the local cluster (either adding one more node or perhaps changing a configuration setting locally) or to find a way to document it clearly?

**Pull request merged**
