### PR TITLE
Add icon, logo and brand usage guidelines

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description
This PR adds brand assets (and some usage guidelines) for Openverse to the repository.

## Technical details
Keeping the brand assets centralised is useful for
- hotlinking from places that don't want to ship with a copy of the assets
- sharing the assets with third-parties who want to depict their association to the project
- making changes in one place instead of many, if need be

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
What formatter is setting this markdown line width? This is otherwise fantastic work.

**Comment by dhruvkb** [comment]
I think it's the one built into PyCharm. Should I revert the line wrapping changes?

**Comment by dhruvkb** [comment]
Maybe later though, because merging this will unblock WordPress/openverse-api#170.

**Comment by zackkrida** [comment]
> should I revert the line wrapping changes?

Please do @dhruvkb, another PR is fine. Thank you!

**Pull request merged**
