### PR TITLE
Fix types in Vue components and add all of them to `tsconfig`

### LINKED ISSUE #2554: Add all components to `tsconfig`
## Problem

Most of the components are using TypeScript (`<script lang="ts">`) but not all of them are actually type-checked. This creates a false feeling of safety.

## Description

We should add all of the components to `tsconfig` to make them all checked by `types` step in the CI.

## Alternatives

Remove the `lang="ts"` from the components that are not in `tsconfig`. This will not actually solve the problem of type-checking, but it will clearly show that the component is not type-checked.

## Additional context

This was previously difficult to do because the `svg` was not type-checked correctly. Now that we've moved to `svg-module`, type-checking should be easier.

This is a pre-requisite for #2553, so the priority is set to `high`.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2554 by @obulat

## Description

This PR adds all of the components to `tsconfig`, and fixes all of the errors that were found by running `just lint types`.

## Testing Instructions

The CI should pass, and the changes should make sense.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Amazing. LGTM. So much better than managing the list of individual components. Everything is working locally.

**Comment by zackkrida** [comment]
Ah, I just thought of something related, also related to the tsconfig move Sara recently implemented:

`frontend/bin/add-entry-to-tsconfig.js` can be deleted and removed from the `create:component` script.

**Review by sarayourfriend — APPROVED** [review]
Incredible work, @obulat :rocket:

**Comment by sarayourfriend** [comment]
Once this is merged, what will be left to convert? Should we create issues like we did in the past for the composables/utilities? There might be a handful of good first issues or at least "help wanted" issues amongst those :thinking:

**Pull request merged**
