### PR TITLE
Sensitive content filter

### PR DESCRIPTION
**Pull request by anton202**
## Fixes
Related to https://github.com/WordPress/openverse/issues/636 by @panchovm

## Description
This PR creates a Toggle switch and a new sensitive content filter
senetive-filter

## Testing Instructions

to activate the filter go to localhost:8443/preferences and check toggle_sensitive_content

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
@anton202 this will be an excellent place to implement whatever is finally decided on in #791. What you have is super close what will likely be the final designs. I'm going to mark this as `blocked` until that is done and I'll let you know when the final designs are ready!

**Comment by AetherUnbound** [comment]
I'm not sure why Staci and I were chosen as reviewers 😅 I'll swap us out for more frontend-focused people 🙂

**Comment by zackkrida** [comment]
Hi @anton202, I just wanted to check in. We're _really close_ to resolving the design discussion in #791, and I've moved this PR to a draft until then. Thanks for your patience.

**Comment by sarayourfriend** [comment]
@anton202 I'm going to close this PR for now. We've finished the discussion in the design issue that Zack linked above, however we'll want to write an implementation plan before working on the designs as they are somewhat different from what we had before. If you're interested in working on implementing this after the plan is finished, let me know and I'll make sure to ping you when the issues are ready.

**Pull request closed without merging**
