### PR TITLE
Update the 'updated_on' column during popularity refresh

### PR DESCRIPTION
**Pull request by stacimc**
## Description

When records are updated as part of a popularity refresh, the `updated_on` column is not updated. This PR changes that.

It also updates the batched_update DAG to set the default `update_query` to include the updated_on update.

## Testing Instructions

Run a popularity refresh locally, ensure that it passes and that the `updated_on` column is updated.

Trigger a batched_update and verify that the default `update_query` is `SET updated_on = NOW(), ...`. Verify that you can run a batched_update with some additional query. Verify that if you try again but remove that part from the `update_query`, you get a validation error in the UI.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`just catalog/generate-docs media-props`
      for the catalog or `just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — COMMENTED** [review]
Would it be possible to set the `updated_on` in the `batched_update`? That would make it easier to update this field whenever the `batched_update` is run

**Comment by stacimc** [comment]
Yes, this PR came up in conversation on https://github.com/WordPress/openverse/pull/4429#discussion_r1630370221 where I noted that batched updates don't automatically set this either. My intention here is to fix it in the established DAGs while we think about a more permanent solution (likely a trigger).

**Review by obulat — APPROVED** [review]
Works perfectly! Nice that Airflow has a pattern verification functionality

**Review by krysal — APPROVED** [review]
LGTM!

**Pull request merged**
