### PR TITLE
Update @popperjs/core dependency

### PR DESCRIPTION
**Pull request by khushi-kothari**
## Fixes

Related to #3242 by @obulat

## Description

Update @popperjs/core dependency

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
@khushi-kothari, the linting errors in the CI and the numbers of lines changed (+3,773 −4,328) show that there are still unrelated changes in the lock file. 

 I updated the lock file here to only include the changes from this PR:
1. Checked out the lock file from `main` to remove all unrelated changes.
```
git checkout main -- pnpm-lock.yaml
```
2. Ran `just node-install` to update the lock file.
3. Committed the updated lock file to the branch and pushed the changes.

You will need to do the same for other PRs. After the CI passes, you can mark the PRs ready for review.
Next time, please only open one PR at a time to make the PR writing, reviewing and merging without conflicts easier.

**Comment by khushi-kothari** [comment]
> @khushi-kothari, the linting errors in the CI and the numbers of lines changed (+3,773 −4,328) show that there are still unrelated changes in the lock file.
> 
> I updated the lock file here to only include the changes from this PR:
> 
> 1. Checked out the lock file from `main` to remove all unrelated changes.
> 
> ```
> git checkout main -- pnpm-lock.yaml
> ```
> 
> 2. Ran `just node-install` to update the lock file.
> 3. Committed the updated lock file to the branch and pushed the changes.
> 
> You will need to do the same for other PRs. After the CI passes, you can mark the PRs ready for review. Next time, please only open one PR at a time to make the PR writing, reviewing and merging without conflicts easier.

Wow Thankyou very much, for some reason even after doing ``just node-install`` or ``just install`` lock file wasn't getting updated. This was really helpful of you. Making same changes in all the PRs and hope we'll soon be ready to go 🚀

**Comment by khushi-kothari** [comment]
All thanks to @obulat now this PR is passing all the CI 🎉

**Review by obulat — APPROVED** [review]
I tested the popovers (Report content, content switcher on desktop) locally, and they all work fine.
Thank you for your contribution, @khushi-kothari 🎉

**Review by dhruvkb — APPROVED** [review]
Thank you @khushi-kothari for this very targeted and precise update!

**Comment by khushi-kothari** [comment]
I'm glad you liked the changes. Thankyou for reviewing @dhruvkb, and I'm happy to contribute 😄🙌

**Pull request merged**
