### PR TITLE
Update banner to match new designs and add analytics notification 

### LINKED ISSUE #823: Create the analytics notification
## Description

Although we plan our analytics system to be privacy-oriented and GDPR compliant, in the interest of transparency we would like to inform users that the site has analytics and show them where they can opt-out.

This could potentially be a banner, which is a UI element we have used in the past for the CC Search to Openverse migration and to notify of incomplete translations. Showing multiple banners on one page might not look very pretty but that's something that @panchovm can help out with.

## Additional context

RFC: https://github.com/WordPress/openverse/blob/3fa9f03937d2af356535f158f7f80b20a6bd79d2/rfcs/analytics/20221006-implementation_plan_frontend.md

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #823 by @dhruvkb

## Description

> **Note**
> This PR targets #2117 i.e. `banner-style-refresh` and not `main`.

This PR
- updates the `VNotificationBanner` component to support
  - 4 natures (info, warning, success, error)
  - 2 variants (regular, dark)
- adds 4 natures x 2 variants x 2 breakpoints = 16 stories for these
- updates existing banners to use these new designs
- adds a banner for the analytics
- adds VRT for these Storybook stories
- updates existing VRTs to pass with the additional banner
- adds new icon assets (These are not a 1:1 match because some icons are not in the WP DL, requesting @fcoveram to provide)

## Testing Instructions

You can directly refer to updated snapshots in the "Files changed" tab. Or you can do the following: 

0. Check out the PR and run the dev server.
1. Clear all cookies.
2. Visit `http://localhost:8443/hi/?referrer=creativecommons.org`
3. You should see all three banners in the dark variant.
   Openly Licensed Images, Audio and More | Openverse

---

1. Visit `http://localhost:8443/hi/about/?referrer=creativecommons.org`
2. You should all all three banners in the regular variant.
   About Openverse | Openverse

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Looks flawless! LGTM. I did notice a bug that I'll fix in the `banner-style-refresh` branch. Just need to add a white background to the sticky header element on internal pages.

CleanShot 2023-05-19 at 08 28 07@2x

**Comment by dhruvkb** [comment]
Drafted and blocked awaiting the right icons and exact colors.

**Comment by zackkrida** [comment]
@sarayourfriend requesting your review here as I don't think @fcoveram has the capacity to look at this PR this week.

**Comment by sarayourfriend** [comment]
I'll review this today or tomorrow.

**Review by sarayourfriend — APPROVED** [review]
LGTM, works and looks great locally and on my relatively low-spec Android phone.

We should keep in mind the banner stacking and probably consider avoiding adding any more... Even two feels like a lot and will now be a common occurrence for folks visiting certain translations. At least the case with three is impossible to reach organically, right? CC search doesn't redirect any of our language prefixes as far as I can tell in my brief testing.

**Comment by dhruvkb** [comment]
@sarayourfriend you're right, while 3 is the theoretical maximum, 2 is the most that will occur in practice. CC Search does not redirect to our localised pages.

Even then, we need to be conscious about adding any more banners in the future, or finding an alternative UI to display notifications (other than banners) if there is a need to add any new ones.

**Comment by fcoveram** [comment]
Thanks for the work @dhruvkb, and @sarayourfriend and @zackkrida for reviewing it.

> Even then, we need to be conscious about adding any more banners in the future, or finding an alternative UI to display notifications (other than banners) if there is a need to add any new ones.

+100.

To this point, the best approach is to include notifications and any other similar feedback during the search experience or in context, like in the playing audio message when focusing on the component. We should avoid thinking of "adding a banner" as a first solution each time we need to convey information.

That degrades UX and product quality.

**Pull request merged**
