### PR TITLE
Update Nuxt and related dependencies to v3.13.0

### PR DESCRIPTION
**Pull request by zackkrida**
## Description

This PR updates Nuxt to the latest minor version. I tried using their reccommended `ov pnpx nuxi@latest upgrade --force` command to do the upgrade, but I had to update the version in our package.json first before the subdependencies would be updated in the lock file.

This PR also makes a change to locales, renaming the `iso` field to `language`, in preparation of v9 of Nuxt-i18n: https://i18n.nuxtjs.org/docs/v9/guide/breaking-changes-in-v9#locale-iso-renamed-to-language

## Testing Instructions

All the things should work. CI should pass, and a local frontend clickthrough should not show any issues.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
The snapshots look identical to me 😕

**Comment by zackkrida** [comment]
@obulat I replaced the error snapshot, the original seemed to have an extra 1px of whitespace on the left side!

**Review by sarayourfriend — APPROVED** [review]
LGTM, and great! This includes an update to `@nuxtjs/robots` that fixes its robots rule parsing and should allow us to add query-param based rules, so crawlers know they don't need to land on the tag and creator collection pages, which should reduce some of the load we've seen to search.

**Comment by sarayourfriend** [comment]
BTW: I tried to play around with the robots settings, but I wasn't sure if it would end up breaking some bots. Slack and Twitter bot both ignore robots.txt to get embeds information, but apparently Discord's bot does not. It's hard to find comprehensive information about this, but I think to really resolve the issue we'd need to take a holistic look at our SEO goals and get input from someone more familiar with this stuff. On the other hand, the updates to the robots module are working great, so when/if we choose to make changes there, we'll have a great degree of flexibility now.

**Pull request merged**
