### PR TITLE
polyfill flatMap for Chrome < 69

### LINKED ISSUE #2745: Error when cleaning up vueuse event handlers on Chrome 68 TypeError: n.flatMap is not a function
## Description
We updated Vueuse version recently, and moved to using the Vueuse `useEventListener` composable instead of the one we vendored in. This is causing problems for older browsers.

Vueuse uses `flatMap` to clean up the event listeners when an element is unmounted. `flatMap` is not available in Chrome versions below 69, so the event listeners cannot be removed.
Here's a link to the issue in the Vueuse repository: https://github.com/vueuse/vueuse/issues/2642

A workaround suggested in the issue comment is to import the `core-js` `flatMap` shim in the entry file:
`import 'core-js/actual/array/flat-map'`

I'm not sure where the `entry` file in the Nuxt app would be. Best place, I think, would be a plugin, similar to the `focus-visible.client.ts` (but without `.client`). @zackkrida, do you agree?

## Sentry link
Sentry Issue: [OPENVERSE-FRONTEND-16K](https://openverse.sentry.io/issues/4329079092/?referrer=github_integration)

```
TypeError: n.flatMap is not a function
  at useFeatureFlagStore.actions.syncAnalyticsWithLocalStorage (./src/stores/feature-flag.ts:227:23)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #2745 by the sentry bot

## Description

Polyfills the Array.prototype.flatMap method so it works in versions of Chrome < 69. This has occurred enough times to warrant the polyfilling. 

## Testing Instructions

Build locally and confirm the presence of the polyfill in the client bundle by searching for `flatMap:` and confirming it's there. 

We should also see a minuscule increase to the bundle size.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Thank you for fixing this! The testing instructions and comments are great.

**Review by sarayourfriend — COMMENTED** [review]
Rather than manually adding the polyfill (and potentially playing whack-a-mole if other newer APIs get used by dependencies), would it be cleaner to expand our browserslist to accurately reflect the browsers we wish to support (in this case, Chrome < 69)? As I understand it, if we do it that way we might only see a bundle size increase for the "legacy" bundle rather than in all bundles, in addition to the benefit of not needing to manually manage polyfills.

**Comment by obulat** [comment]
> Rather than manually adding the polyfill (and potentially playing whack-a-mole if other newer APIs get used by dependencies), would it be cleaner to expand our browserslist to accurately reflect the browsers we wish to support (in this case, Chrome < 69)? As I understand it, if we do it that way we might only see a bundle size increase for the "legacy" bundle rather than in all bundles, in addition to the benefit of not needing to manually manage polyfills.

Would adding something like "chrome >= 68" to the "browserslist" in `package.json` also turn into a game of wack-a-mole, though? What if another version of another browser would start causing a different issue?
I looked up the distribution of browsers that cause this error, and there is a wide range of browsers and versions. There's an argument for adding this polyfill specifically because we do get a very clear signal from Sentry that we need to polyfill the `flatMap`. I am not against your suggestion, @sarayourfriend , I'm just trying to understand the tradeoffs.

**Review by sarayourfriend — APPROVED** [review]
I'm going to approve and merge this now, actually, because the bundle size increase is relatively small and browserslist doesn't support complex usage of `not` ("or not" does not work the way we would think it does). But I will say that if we're adding a polyfill for this, we should consider how our browserslist target is configured. The number of actual clients that are effected by this, based on Chrome numbers on our Plausible, is probably ~200. That 200 clients of 578000. In other words, _very few people_. 

I think a preferrable alternative to always including the flat-map polyfill could be an asynchronous import of `https://polyfill.io/v3/polyfill.min.js?version=3.111.0&features=Array.prototype.flatMap%2CArray.prototype.flat`. Polyfill.io only returns the polyfills if the requesting browser needs it. We'd add `await import('https://polyfill.io/v3/polyfill.min.js?version=3.111.0&features=Array.prototype.flatMap%2CArray.prototype.flat')` before using the particular vueuse core composable that requires it.

In any case, we can go with this option for now, but we could open to change it to use a conditional polyfill. Half a kB doesn't seem like heaps when our total bundle size is 868 kB... but that rationale would have us never make bundle size improvements that incrementally add up in the end. From a carbon perspective, on the other hand, it might be better to always send that half a kB rather than creating another request to the polyfill.io CDN. Hard trade offs to make :thinking:  I haven't gone ahead and opened the issue because I don't know exactly which action to recommend myself.

**Comment by sarayourfriend** [comment]
Oops, I was writing my approving review while you were writing your comment, Olga. The approach with browserslist I was hoping would work is the `not supports array-flat`, but it doesn't combine "not" in a flexible enough way. It might be possible to do but I think it would be very complex.

In any case, approved and merged. I think my comment about the actual number of people effected by this is valid though and we should consider strongly what kind of coverage we consider as standard. Our browserslist configuration is actually _narrower_ than the default browsers list config, so there isn't anything to currently suggest we have an intention of very wide client support.

**Pull request merged**
