### PR TITLE
Raise Exception for SVG Watermark

### LINKED ISSUE #3373: Watermarking fails for SVG images
## Description

Pillow library that handles watermarking does not support SVG images [^1]. Watermark returns `424 Failed Dependency` error: `"cannot identify image file <_io.BytesIO object at 0x7f213a52cb80>"`

## Reproduction

Go to an SVG image's watermark endpoint: https://api.openverse.engineering/v1/images/b5f553df-c852-4506-94d4-55b638e4d030/watermark/
See 424 Failed Dependency error: `"cannot identify image file <_io.BytesIO object at 0x7f213a52cb80>"`
Sentry error event: https://openverse.sentry.io/issues/4093254538/events/6c4901bc54d3489a985cda2ff0d7578c/

## Additional context

In the watermark method, we should check the extension, and return 415 Unsupported media type if it's SVG.
Some fixes to the watermark method were added in #1234

`watermark` module is in `api/api/utils/watermark.py`
[^1]: [Pillow's supported image formats](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html)

### PR DESCRIPTION
**Pull request by firatbezir**
## Fixes 

Fixes #3373 by @obulat 

## Description

This checks if the URL ends with ".svg" or file type is an SVG and raises an UpstreamWatermarkException.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
Thanks for the contribution @firatbezir, it looks great so far. I just have two requests before I can approve:

1. Can you add a new unit test for this case? Existing watermark tests are in `test_watermark.py`.
2. Please run the linting locally with `just lint` and commit the changes. The linting CI step is failing and must pass before we can merge a PR.

**Comment by sarayourfriend** [comment]
Just a heads up, @firatbezir, I'm converting this to a draft to avoid the repeated pings until the unit test is present. Thanks again for the contribution, looking forward to being able to merge it :slightly_smiling_face:

**Review by obulat — APPROVED** [review]
Thank you for your contribution, @firatbezir ! The CI passes :)

**Comment by firatbezir** [comment]
> Thank you for your contribution, @firatbezir ! The CI passes :)

**Comment by firatbezir** [comment]
@obulat that is great. I truely owe you a big thank for your help and patience.

**Comment by AetherUnbound** [comment]
@firatbezir is it okay to reopen this? I think we still want these changes!

**Comment by firatbezir** [comment]
@AetherUnbound which changes did you mean?

**Comment by AetherUnbound** [comment]
This PR! It's closed but hasn't been merged yet. I'm going to reopen it so we can get the code merged in once it's reviewed 🙂

**Review by sarayourfriend — APPROVED** [review]

**Pull request merged**
