### PR TITLE
Add more docs for Plausible and auto-initialise custom event names

### LINKED ISSUE #1120: Automatically add existing custom events to Plausible setup locally via set up script
## Problem

To test any custom events locally, you need to manually add them. It would be nice if all existing events were automatically populated in the local testing environment for convenience.

## Description

This could be done using the https://plausible.io/docs/sites-api#put-apiv1sitesgoals endpoint. We could write a script that greps the frontend code for calls to `sendCustomEvent` and try to automatically extract the custom event names. This wouldn't work for dynamic event names but for most cases it would work and would minimise the maintenance burden of this feature by removing one more step for adding custom events locally.

We could use the same script to autopopulate production with new custom events as well, potentially in a GitHub workflow on pushes to main that modify the list.

We should not remove custom events though, as that should only be done manually when we're sure we no longer need a custom event's data.

## Alternatives

Continue relying on manually adding the events.

## Additional context

Marked as medium as there are a bunch of issues for adding new custom events that are all marked as "good first issue". This would help make it slightly easier for new contributors to work on these issues.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1120 by @sarayourfriend
Fixes https://github.com/WordPress/openverse/issues/1119 by @sarayourfriend

## Description

Updates the existing analytics documentation with more comprehensive information about the local Plausible setup. I've also added documentation on how to work with custom events and a new script to automatically populate the local Plausible instance with the custom events so that we don't have to manually add them when testing.

## Testing Instructions

Read the updated documentation and confirm it makes sense and is accurate.

Test out the changes to `setup_plausible.sh` and confirm that the custom events get added as expected. Currently, there is only a single custom event defined, so to test that the loop logic works, add a test event to the `Events` type and re-run `just frontend/init`.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
This is great. Worked with creating a few custom events locally and the documentation was very helpful.

**Comment by zackkrida** [comment]
@sarayourfriend I did notice one small problem. The analytics document doesn't show up in the ToC Because while the file lives at `documentation/guides/frontend/analytics.md`, it's included in the reference ToC at `documentation/reference/frontend/index.md`.

**Comment by sarayourfriend** [comment]
Thanks, Zack. Fixed the ToC. I was initially unsure where to put the guide, I didn't even realise there was an existing analytics documentation at first because I expected it to be under references. I opened this discussion to help clarify the documentation organisation: https://github.com/WordPress/openverse/discussions/1121#discussioncomment-5508904

**Review by obulat — APPROVED** [review]
Excellent instructions! I removed all the containers and tried the instructions, and everything worked.

I think we should add a note about starting the frontend (`just frontend/run dev`) to the quick start because if you only run `just frontend/up` and `just frontend/init`, you won't be able to test events: the app is not running on localhost yet.
We could add it here, or, to speed up this PR, in a different PR.

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
