### PR TITLE
Fix load sample data script provider insertion

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Addresses an issue introduced in #3931

## Description

This PR fixes a syntax issue in the provider insertion step of the load sample data script. I discovered this when I ran the script locally and observed this in the `just api/init` output:

```
env COMPOSE_PROFILES="api,ingestion_server,frontend,catalog" docker-compose -f docker-compose.yml exec -T db psql -AXqt
ERROR:  syntax error at or near "now"
LINE 1: (now(), 'ccmixter', 'CCMixter', 'https://ccmixter.org', fals...
         ^
```

I tried to determine why the error wasn't bubbled up any further, but was unable to do so in the short time that I was looking at this.

## Testing Instructions

Run `just api/init` on this branch and observe that the above step succeeds where it previously failed.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
eek. nice catch

**Comment by zackkrida** [comment]
Just noticed some test failures:

https://github.com/WordPress/openverse/actions/runs/8443376375/job/23126934115?pr=3971#step:6:165

```shell
 test/unit/serializers/test_media_serializers.py::test_page_size_validation[501-True]
  /venv/lib/python3.11/site-packages/_pytest/python.py:1792: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
  Plugin: schemathesis, Hook: pytest_pyfunc_call
  ValidationError: {'page_size': [ErrorDetail(string='Ensure this value is less than or equal to 500.', code='max_value')]}
  For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)

test/test_examples.py::test_audio_success_examples[\n# Get the statistics for audio sources\ncurl \\\n   \\\n  "http://localhost:50280/v1/audio/stats/"\n-out_val1]
  /venv/lib/python3.11/site-packages/_pytest/python.py:1792: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
  Plugin: schemathesis, Hook: pytest_pyfunc_call
  AssertionError: assert [{'display_na...mixter', ...}] == [{'display_na..._audio', ...}]
    Left contains one more item: {'display_name': 'CCMixter', 'logo_url': None, 'media_count': 1, 'source_name': 'ccmixter', ...}
    Use -v to get more diff
  For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
```

**Comment by AetherUnbound** [comment]
Oops, thanks folks 😖 didn't think this would affect tests at all and should have run them locally! I'll get a fix up.

**Review by obulat — APPROVED** [review]
I couldn't understand why the tests were failing when I added ccMixter to `audio_responses`, and didn't notice the `;` instead of `,`.
Tested locally, and it works well.

**Review by stacimc — APPROVED** [review]
Nice catch 😮

**Pull request merged**
