### PR TITLE
Draft PRs fix for PR Board automation

### LINKED ISSUE #3467: PRs that both have changes requested and are drafted should be in the drafted column of the PR board
## Description

It appears that if a PR both has changes requested _and_ is drafted, it shows up in the "changes requested" column of the PR board. The maintainer team usually uses drafting a PR as knowing that it requires further changes or additional work, any drafted PR should go into the drafted column regardless of how many reviews it has (or what the state of those reviews are).

## Screenshots

Screenshot 2023-12-05_13-20-06

### PR DESCRIPTION
**Pull request by The5cheduler**
## Fixes

Fixes #3467 by @AetherUnbound 

## Description

- Included additional check for case where PRs that both have changes requested and are drafted should be in the drafted column of the PR board.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by The5cheduler** [comment]
add label: 🧱 stack: mgmt

**Review by dhruvkb — CHANGES_REQUESTED** [review]
The change, although correct in terms of the diff, has been made in the wrong place. It was supposed to be on line 85.

**Comment by The5cheduler** [comment]
Applied requested changes with [ec3305a](https://github.com/WordPress/openverse/pull/3649/commits/ec3305ab641f48362df6b4e3db90f19b67bcb52e)

**Review by dhruvkb — APPROVED** [review]
Thank you this contribution @The5cheduler! We will have to wait for a second approval, feel free to contribute on another issue in the meantime.

**Review by AetherUnbound — APPROVED** [review]
Awesome, thank you for the fix 😄

**Pull request merged**
