### PR TITLE
Move NGINX-based services out of the API profile

### LINKED ISSUE #4289: CI + CD builds `nginx` image during API up
## Problem

The `nginx` image is always built in CI job "Run tests for the API". This is because the api/compose.yml does not have an `image` field in the `nginx` service, which forces it to be built when API is brought up.

- https://github.com/WordPress/openverse/actions/runs/8992601250/job/24702911944#step:5:13
- https://github.com/WordPress/openverse/actions/runs/8989040826/job/24691377170#step:5:9

## Description

Add the field `services.nginx.image` to ensure that the image is built-once and cached and subsequently re-used.

## Alternatives

Another alternative is to drop `nginx` and `proxy` from the API profile and let them be started manually by the developers who actually need to run them.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #4289 by @dhruvkb 

## Description

This PR removes the use of the NGINX based services `nginx` and `proxy` from the `api` profile. This means they will no longer be created when invoking the `api/up` recipe.

Instead these services, along with the main API services `web` and `cache` are part of the `api_extra` profile and they can all be created by invoking the `api/up-extra` recipe (modelled after the `catalog_dependencies` approach). 

This should speed up CI because of fewer services being built and raised.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`just catalog/generate-docs media-props`
      for the catalog or `just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Nice improvement to CI speed!

**Comment by AetherUnbound** [comment]
Do any other CI jobs need to change in order to ensure these are built for release?

**Comment by dhruvkb** [comment]
@AetherUnbound we are still building them and publishing them when appropriate, we just won't build them for the tests that don't need them.

**Review by AetherUnbound — APPROVED** [review]
Gotcha, thanks for clarifying! Looks good!

**Pull request merged**
