### PR TITLE
Making docker user names consistent

### LINKED ISSUE #1145: Use consistent Docker user names
## Problem

Our services use an interesting mix of usernames for users created inside Docker.

| Service | Username |
|-|-|
| api | [opener](https://github.com/WordPress/openverse/blob/5106dc3e73d0b55f8eb0bfb8375c103c93402c1a/api/Dockerfile#L76) |
| ingestion_server | [ingestionu](https://github.com/WordPress/openverse/blob/5106dc3e73d0b55f8eb0bfb8375c103c93402c1a/ingestion_server/Dockerfile#L58) |
| catalog | [airflow](https://github.com/WordPress/openverse-catalog/blob/46281fc9fda60ab2df0df6d85043565dfc51b12d/docker/airflow/Dockerfile#L51) |

## Description

We should use the same, or a similar format of, names for these users.

### PR DESCRIPTION
**Pull request by tejaswarathe**
## Fixes

Fixes #1145 by @dhruvkb 

## Description

This PR changes the docker usernames for services using different names to a single, meaningful name 'ov_user'.
Changes to the airflow user name have been intentionally left out because the airflow image has to use the airflow user name.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
I'm starting with the review of `catalog/Dockerfile`.

In this file there are a few references to `/home/airflow/...`. This the path to the `$HOME` directory when the username is `airflow`. When the username is changed to `ov_user`, the path to the `$HOME` directory will become `/home/ov_user/...`.

Once you make this change, the CI + CD workflow will be able to proceed further and we'll see if the other checks are passing.

**Comment by tejaswarathe** [comment]
@dhruvkb What exactly is a DC_USER? Do we need to change it as well?

**Comment by dhruvkb** [comment]
@tejaswarathe I'm sorry about not checking this earlier but it seems that the `airflow` image has to use the username of `airflow` and there is no way around that. They've hardcoded into their [`Dockerfile`](https://github.com/apache/airflow/blob/67313bbc844454bd56482fef88896eb75b242d1a/Dockerfile) in several places.

Can you try reverting the changes to the Airflow code? The CI + CD workflow will be able to run normally then.

**Comment by tejaswarathe** [comment]
Reverted the name changes for the catalog, completed the change for API, ingestion_server, indexer_worker.

**Comment by dhruvkb** [comment]
I found two more occurrences of "opener" in the code.

https://github.com/WordPress/openverse/blob/81f0edbdc8456a55e7f89acfafc61f9195a78a9d/env.template#L1

https://github.com/WordPress/openverse/blob/81f0edbdc8456a55e7f89acfafc61f9195a78a9d/justfile#L8

**Review by dhruvkb — APPROVED** [review]
Thanks for the contribution @tejaswarathe. LGTM, this is a good normalisation of Docker usernames.

I'll also ask for one more review from another maintainer because it's touching multiple different services but with CI passing, I'm fairly confident that everything is good to go.

**Review by krysal — APPROVED** [review]
Looks good to me! Thank you, @tejaswarathe 💯

**Pull request merged**
