### PR TITLE
Fix header bottom border when scrolled

### LINKED ISSUE #2274: Header's bottom border not visible in small breakpoints
## Description

In `xs`, `sm`, and `md`, the bottom border (in `dark charcoal 20`) of header is not visible. This cut off the page, making it look broken.

## Reproduction

1. Go to openverse on a device or view that fits with the breakpoints mentioned
2. Search anything
3. Scroll down in the search results
4. See how the bottom border doesn't show up.

## Screenshots

https://github.com/WordPress/openverse/assets/895819/2c198ad7-6874-4f53-870f-3b60bdd55f9a

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2274 by @fcoveram

## Description

This PR fixes the header bottom border: it is shown when the site is scrolled down on the content pages, search result pages and the single result pages. It moves the setting of the border from inside the header components to the parent layouts.

## Testing Instructions

Go to content pages (about), search page and the single result pages, scroll down and see that the border appears when you scroll down and disappears when you scroll up. This should happen both on the mobile widths and the wider screens.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by fcoveram — CHANGES_REQUESTED** [review]
I noticed the following bug

https://github.com/WordPress/openverse/assets/895819/3751c278-c7d5-421c-81c3-a5a399f4422d

If you scroll in the header area, the page shows a white space below and openverse within it.

The recording was using Firefox on iOS 16.5.1. In my Macbook Pro, the bug is visible on Chrome, but not on Firefox.

**Comment by obulat** [comment]
> I noticed the following bug
> 
> If you scroll in the header area, the page shows a white space below and openverse within it.
> 
> The recording was using Firefox on iOS 16.5.1. In my Macbook Pro, the bug is visible on Chrome, but not on Firefox.

@fcoveram, this is a different issue that is also, unfortunately, present in prod. It was reported here: https://github.com/WordPress/openverse/issues/2596

We should assign that issue this week, but since it's not related to the changes in this PR, this PR could be approved if it fixes the bottom border issues :)

**Review by fcoveram — CHANGES_REQUESTED** [review]
I don't see the border in any breakpoint

|`xs`|`xl`|
|:---|:---|
|header of search results in XS breakpoint|header of search results in XL breakpoint|

**Comment by obulat** [comment]
> I don't see the border in any breakpoint

Oops, I added the color to the border, but forgot to add the border itself. Sorry! It's fixed now.

**Review by fcoveram — APPROVED** [review]
It works correctly 🚀

**Review by zackkrida — APPROVED** [review]
LGTM, I like this implementation 👍

**Pull request merged**
