### PR TITLE
Use contentlist role for search results for a11y

### LINKED ISSUE #541: Add loading skeleton to `VImageGrid`
## Problem

We don't have the skeleton loading indicator in the Image grid.

## Description

We use the `VSkeleton` component for the audio and all content grids loading state. We should also use `VSkeleton` to show that `VImageGrid` is loading. `VImageGrid` is used for 'Images' view and for showing the Related images on the single result page.

## Alternatives

We are currently using the spinner, but it would be more consistent to use the skeleton loader for all types.

## Additional context

This issue came up in another PR that was improving the loading state for related images: https://github.com/WordPress/openverse-frontend/pull/1524#issuecomment-1154713052.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### LINKED ISSUE #794: Move search results to an ordered list
Openverse search results should be wrapped in an ordered list and  `li` element for each returned result. This will help screen reader users identify the number of results returned and their current position in the results.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #794 by @zackkrida
Fixes #541 by @obulat 

## Description

This PR wraps the search results into an ordered list to make the screen reader announce it as a contentlist, and to make it possible for the users to know how many items there are.

For the list `aria-label`, I used "Search results for query", without the media type. I think this might be clear from previous navigation, and it's easier to implement this way. I am open to suggestions about the text.

There are also a couple of other fixes:
- image grid adds a Skeleton loader. This is a very simple addition that makes all of the search views consistent.
- "Openverse" text is passed to the home link to prevent it saying "Opening braces openverse closing braces"
- Removes the incorrect grid for the VContentLinks that I added in the grid fix PR (I accidentally added the grid fixes to both the "All content" results AND the content links).

## Testing Instructions

Run the app using `just frontend/run dev`
Open a search page `localhost:8443/search/image?q=cat` and turn on a screenreader (CMD + F5 for VoiceOver on Mac, for Windows I used the UI to open NVDA)
On Mac, with Voiceover:
When you navigate to the search results, you should hear "Content list Search results for cat, 20 items" when screenreader reads out the page, and "Entering Search results for cat content list" when you navigate to the results.

On Windows, with NVDA:
You should hear "Search results for cat List with 27 items Cat link" when you navigate to the first result on All content list.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — COMMENTED** [review]
Thanks so much for the thorough testing instructions!! I haven't done screenreader testing, so this was quite informative. I ended up trying to get `orca` working on Linux, and while I was getting screenreader results, I wasn't hearing the text you mentioned about the number of search results. I was also seeing the following in my console running the frontend:

```

 WARN  [vue-i18n] Value of key 'browse-page.aria.results' is not a string or function !                                                                                                                   13:00:14


 WARN  [vue-i18n] Cannot translate the value of keypath 'browse-page.aria.results'. Use the value of keypath as default. 
```

Could that be related? Is there an extra step I'm missing in terms of setup?

**Comment by obulat** [comment]
> Thanks so much for the thorough testing instructions!! I haven't done screenreader testing, so this was quite informative. I ended up trying to get `orca` working on Linux, and while I was getting screenreader results, I wasn't hearing the text you mentioned about the number of search results. I was also seeing the following in my console running the frontend:
> 
> ```
> 
>  WARN  [vue-i18n] Value of key 'browse-page.aria.results' is not a string or function !                                                                                                                   13:00:14
> 
> 
>  WARN  [vue-i18n] Cannot translate the value of keypath 'browse-page.aria.results'. Use the value of keypath as default. 
> ```
> 
> Could that be related? Is there an extra step I'm missing in terms of setup?

Thank you so much for testing, @AetherUnbound ! I'm sure the set up was quite time and effort consuming. Having a Linux machine for testing, too, is great for breadth of different setups.

Yes, the two points you mention are related. We save all of the texts as `json5` in `locales/en.json5`. There is a step during the frontend build that converts the json5 file into a json file that is actually used in the app. That step usually runs when you do `just frontend/run dev`, but it seems that it didn't for some reason. To specifically copy the new strings to the json file, you can run `just frontend/run i18n:en`. This should fix it. There is also a way to do it manually: copy the string from `en.json5` to `en.json` with the same key (so, adding a key "results" nested under `browse-page.aria`), but it shouldn't be necessary.

**Review by AetherUnbound — APPROVED** [review]
The code changes generally make sense to me! Took me a sec to grok `v-for` 😄 

I suspect the not-counting-results may be a difference between screen reader implementations, since your changes only include reading out the "search results for" label. So I think this is working as expected!

**Comment by zackkrida** [comment]
@AetherUnbound we have some docs on general screen reader testing here that might prove useful!

https://docs.openverse.org/frontend/reference/testing_guidelines.html#accessibility

**Review by zackkrida — CHANGES_REQUESTED** [review]
@obulat I am also not hearing result counts, just being told that I am in a group and then read the aria label "Search results for {query}."

**Comment by obulat** [comment]
> @obulat I am also not hearing result counts, just being told that I am in a group and then read the aria label "Search results for {query}."

I think this is how VoiceOver implements it. When you navigate to the results using <kbd>Tab</kbd>, you don't hear the number of items, but if you navigate to the page, you will hear:
Screenshot 2023-05-13 at 7 42 50 AM

I also tried other lists on other sites, and they do not announce the number of items in the contentlist.

I also tested this change with NVDA on windows, and it says "Search results for "Cat". List with 32 items. Cat cafe in Seol link" when I navigate to the first result using keyboard

**Pull request merged**
