### PR TITLE
Fix stories

### LINKED ISSUE #2216: VModal story is broken
## Description

https://docs.openverse.org/storybook/?path=/story/components-vmodal--default-story is broken with the error message below:

```
props.variant is undefined

./src/components/VButton.vue/setup/isFocusSlimFilled<@https://docs.openverse.org/storybook/main.97df8a96.iframe.bundle.js:2:978024
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.evaluate@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2589865
get value@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2581610
get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2551522
render@https://docs.openverse.org/storybook/main.97df8a96.iframe.bundle.js:2:980721
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._render@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2628922
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689997
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.run@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2589521
flushSchedulerQueue@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2569913
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/nextTick/<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2577873
flushCallbacks@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2577061
```

### LINKED ISSUE #2217: VItemGroup story is broken
## Description

https://docs.openverse.org/storybook/?path=/story/components-vitemgroup--default-story is broken with the error message below:

```
name.split is not a function

getInfo@https://docs.openverse.org/storybook/main.97df8a96.iframe.bundle.js:2:652494
render@https://docs.openverse.org/storybook/main.97df8a96.iframe.bundle.js:2:652669
createFunctionalComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2606635
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2607017
_createElement@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2558163
createElement$1@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2558504
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._init/vm._c@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2623376
render@https://docs.openverse.org/storybook/main.97df8a96.iframe.bundle.js:2:1312397
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._render@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2628922
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689997
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
updateChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2673878
patchVnode@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2674539
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677317
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627556
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.run@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2589521
flushSchedulerQueue@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2569913
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/nextTick/<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2577873
flushCallbacks@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2577061
```

### LINKED ISSUE #2218: VButton story is broken
## Description

https://docs.openverse.org/storybook/?path=/story/components-vbutton--v-button is broken with the following error message:

```
args.variant is undefined

anonymous@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js line 2 > Function:3:117
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._render@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2628922
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689997
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
createChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2668777
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667728
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677178
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627586
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
Watcher@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588581
mountComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690019
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2690462
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2746048
init@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2599859
createComponent@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2666702
createElm@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2667260
updateChildren@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2673878
patchVnode@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2674539
patch@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2677317
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype._update@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2627556
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Vue.prototype.$mount/updateComponent<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2689986
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.get@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2588691
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/Watcher.prototype.run@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2589521
flushSchedulerQueue@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2569913
../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.js/</factory/nextTick/<@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2577873
flushCallbacks@https://docs.openverse.org/storybook/vendors~main.2636c955.iframe.bundle.js:2:2577061

```

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2216 by @sarayourfriend
Fixes #2217 by @sarayourfriend
Fixes #2218 by @sarayourfriend

## Description

This PR fixes the errors in Storybook stories that stop them from building.

I've opened a single PR to fix three stories because the fixes are just single-line changes.

The errors were caused by recent changes: `variant` and `size` are now required props for `VButton`. Another change was `svg` `name` property was using incorrect prop.

## Testing Instructions

Run storybook using `just frontend/run storybook` and check that `VButton`, `VItemGroup` and `VModal` stories don't have errors. Also check the link in the published storybook preview.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
Why did the docs not build for this PR?

**Comment by dhruvkb** [comment]
@obulat it does seem like the filters for documentation are not catching MDX files. See [this line in logs](https://github.com/WordPress/openverse/actions/runs/5134175336/jobs/9237790886#step:3:96).

**Review by zackkrida — APPROVED** [review]
Yep, stories look good!

**Comment by sarayourfriend** [comment]
@dhruvkb @obulat the pattern need to be `frontend/**/*.mdx`. Minimatch converts `**` to `*` in some cases, including this one. You can test minimatch patterns on this site:

http://pthrasher.github.io/minimatch-test/

For the set:

```
frontend/whatever/stories/button.mdx
frontend/help.mdx
```

`frontend/**.mdx` only matches the second (help.mdx) whereas `frontend/**/*.mdx` matches both.

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
`/?path=/story/components-vitemgroup--popover` is still broken with the `state.rects` error.

The modal story also either shows a bug in the modal implementation or has a bad implementation: the close button of the modal is invisible:

image

If it is a problem with the modal story and we can fix it in this PR, that'd be great. Otherwise, it needs its own issue.

**Comment by obulat** [comment]
> The modal story also either shows a bug in the modal implementation or has a bad implementation: the close button of the modal is invisible:

This was caused by the Core UI improvement project changing buttons. The modal in Storybook is the only one that I know of that uses the top bar, and it does not match any existing mock-ups, so I just used a button from the Content Settings Modal (from the mobile modal) to quickly fix this important issue. If we want to update the designs of the storybook modal (and the buttons within it), I think we should open a separate issue/PR.

> /?path=/story/components-vitemgroup--popover is still broken with the state.rects error.
This will require a different investigation, that's why I specifically did not touch it here, and did not add it to the list of fixed issues.

**Review by sarayourfriend — APPROVED** [review]
> This will require a different investigation, that's why I specifically did not touch it here, and did not add it to the list of fixed issues.

Ahh, the story I linked is a VItemGroup sub-story, which is why I thought it would be covered, but I see now that it's the popover story, which I guess is what was excluded here. Apologies.

This LGTM then.

**Pull request merged**
