### PR TITLE
Fix sketchfab loading state error

### LINKED ISSUE #3729: Image skeleton keeps rendering on page for 3D model images
## Description

When looking at the detail page of an image that uses the Sketchfab 3D viewer, the skeleton placeholder doesn't disappear, taking most of the space where the image should be placed.

## Reproduction

1. Search for images filtering by the [Sketchfab](https://sketchfab.com/) provider
2. Click on anyone to see the details page
3. See error.

## Screenshots

Screenshot 2024-01-31 at 14-41-03 Pokemon - Jigglypuff

## Additional context

Related [Sentry issue](https://openverse.sentry.io/share/issue/64e3f283a77b4c3fb573b0d956ab9d60/).

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #3729 by @krysal 

## Description

Fixes the display logic for showing the single image result loading skeleton by introducing a computed `showLoadingState` conditional that checks for the presence of a sketchfab identifier. 

This PR _also_ fixes the display of single sketchfab results. Previously, the viewer was only rendering ~300px wide (you can view an example here: https://openverse.org/image/70a225e6-05e5-498a-862a-cbd0ed44d9c4?q=dog). This is because our logic for displaying images correctly relies on object-fit which only applies to replaced elements like images and videos, not the Sketchfab iframe.

We should probably have an additional visual regression test for single Sketchfab results to prevent this in the future. I'll create a new issue for that.

## Testing Instructions

1. Checkout the PR and `j f` to run the frontend locally
2. Make an image search and filter by sketchfab.
3. Visit a single result; observe it now displays correctly

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — CHANGES_REQUESTED** [review]
The changes look okay and run fine locally! However, when viewing a sketchfab result from the results list, I have to press the browser back button _twice_ in order to go back to the results (the first back seems to just remove the sketchfab render itself). It doesn't look like this behavior is the same on `main`.

**Comment by zackkrida** [comment]
@AetherUnbound interesting, I see this behavior in production as well. Only in Firefox. Could you confirm that it isn't specific to this PR, and then I'll go ahead and create a separate issue? Thanks for the review!

**Comment by AetherUnbound** [comment]
> @AetherUnbound interesting, I see this behavior in production as well. Only in Firefox. Could you confirm that it isn't specific to this PR, and then I'll go ahead and create a separate issue? Thanks for the review!

@zackkrida I mention at the end of the previous comment that I wasn't able to replicate it on `main`! So it seems specific to this PR.

**Comment by zackkrida** [comment]
@AetherUnbound apologies, I wanted to confirm if you were seeing it on https://openverse.org vs. looking at the `main` branch locally. But I was mostly looking for a double check as I'm really struggling to see how this PR could introduce this change! 

I'll ask others to take a look tomorrow though; thanks!

**Comment by zackkrida** [comment]
Here's a video of what I see in production:

[Screencast from 2024-02-20 22-31-43.webm](https://github.com/WordPress/openverse/assets/6351754/bf913b01-0a02-48f1-9d82-0199f2fe3f8a)

**Review by obulat — APPROVED** [review]
I can reproduce the bug reported by @AetherUnbound locally using Firefox. If you use the browser back button, on first click, only the 3d model is hidden, and on the second click, you navigate back to the results. However, this is also present in prod (openverse.org). Also, if you use the "Back to results" button, you navigate right away.

Here's the recording of what I see in prod:

https://github.com/WordPress/openverse/assets/15233243/052dbc09-acea-43b9-b1c1-569c96013845


I'm approving this PR because it fixes the loading problem. We can open a new issue for the back button bug in Firefox.

**Pull request merged**
