### PR TITLE
Absorb `build-nginx` job into `build-images` job

### LINKED ISSUE #899: Include `collectstatic` step inside API Dockerfile
## Problem

Currently the Dockerfile for the API (https://github.com/WordPress/openverse/blob/38af21c359703d3faee9e160f1ac69372661d6a2/api/Dockerfile) uses the following build stages.

- `builder`
- `nginx`
- `api`

Here the `nginx` build stage requires that `just api/collectstatic` be run beforehand so that it can be copied into the image from the static files path. 

https://github.com/WordPress/openverse/blob/38af21c359703d3faee9e160f1ac69372661d6a2/api/Dockerfile#L42

So to build the `api_nginx` image, the API needs to be spun up with the entire services orchestra just to collect static files.

https://github.com/WordPress/openverse/blob/38af21c359703d3faee9e160f1ac69372661d6a2/.github/workflows/ci_cd.yml#L408

## Description

This problem can be avoided if staticfiles are collected during the build process itself. And copied into the `nginx` target from the appropriate stage. This will also drop the need for the NGINX build to be a separate job in CI.

https://github.com/WordPress/openverse/blob/38af21c359703d3faee9e160f1ac69372661d6a2/.github/workflows/ci_cd.yml#L384

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #899 by @dhruvkb

## Description

This PR merges `build-nginx` inside `build-images` thus making it the comprehensive image building job for the entire workflow. It also makes the build process faster by parallelising using matrix and removing the need to spin up the entire Docker Compose system.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM. Works fine locally. This will cause the published API image to increase by the size of the static directory. The last published image is 453 MB and this PR increases it to 480 MB. Locally the static directory for me is 25.6 MB so the change in size tracks. This will be (useless) duplicated between the API and the nginx image.

This PR does simplify things though. While it'd be nice to remove this duplication, the correct way to do it would be through shared mounts, which we just need to spend time configuring for ECS. It's not a big hurdle to configure this. I've opened an issue in the infrastructure repository to track this work.

**Comment by dhruvkb** [comment]
@sarayourfriend yes, the API image does grow by ~25MB. I felt that the tradeoff was worth it given how much complexity it eliminates by being able to build the NGINX image in the matrix with all the others.

**Review by zackkrida — APPROVED** [review]
I support this change, the size increase seems worth the benefits, and it does work locally 👍

**Comment by krysal** [comment]
How were you all able to see the size of the new image? After `recreate` my `web` service is only 67 MB in size and exits immediately after starting.

**Pull request merged**
