### PR TITLE
Validate `name` field to replace `IntegrityError`s with 400 response

### LINKED ISSUE #2168: IntegrityError: duplicate key value violates unique constraint "api_oauth2registration_name_key"
## Sentry link

https://openverse.sentry.io/share/issue/7209f5953fa14780910a5412cce44f5c/

## Description

When a user sends a `/auth_tokens/register` request with a duplicate application name, API returns a 500 response.

## Reproduction

Send the registration request with the same application name twice. I used `httpie`:
```
echo '{"name": "Olga test project", "description": "To help Openverse API users", "email": "myemail@example.com"}' | https --json POST api.openverse.engineering/v1/auth_tokens/register/
```
 The second time, you'll get the following error
```
HTTP/1.1 500 Internal Server Error
CF-Cache-Status: DYNAMIC
CF-RAY: 7cbbf9e79ae50523-OTP
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Tue, 23 May 2023 08:37:19 GMT
Server: cloudflare
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Transfer-Encoding: chunked
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cross-origin-opener-policy: same-origin
referrer-policy: same-origin
vary: Authorization, Origin
x-content-type-options: nosniff
x-frame-options: DENY

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
<script  .../>
</body>
</html>
```

```
UniqueViolation: duplicate key value violates unique constraint "api_oauth2registration_name_key"
DETAIL:  Key (name)=(Olga test project) already exists.
  File "django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)

IntegrityError: duplicate key value violates unique constraint "api_oauth2registration_name_key"
DETAIL:  Key (name)=(Olga test project) already exists.
(21 additional frame(s) were not displayed)
...
  File "api/views/oauth2_views.py", line 55, in post
    serialized.save()
```

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2168 from Sentry

## Description

This PR adds validation to the `name` field in `OAuth2RegistrationSerializer` to prevent `IntegrityErrors` from arising in the database when a duplicate name is provided.

## Testing Instructions

0. Check out the PR and run the dev server.
0. Create two applications with the same name.
1. The second one will return a 400 response like so

```
HTTP/1.1 400 Bad Request

{
    "name": [
        "An application with this name already exists."
    ]
}
```

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by krysal — COMMENTED** [review]
The change looks incredibly simple, and it works as expected. Thanks for taking a look at this Dhruv!

However, I wondered why the validations are not coming from the `OAuth2Registration` model as specified under the Meta class. It seems that manually repeating the fields override those validations. I'm not sure why it was like that, but it looks like a 1:1 equivalence with the model's fields. We're repeating code unnecessarily.

I tried deleting lines from 9 to 34 from the `main` branch and it grabbed the validation just fine. You only get a different message:

```json
{
	"name": [
		"o auth2 registration with this name already exists."
	]
}
``` 
I believe this alternative simply the code a lot, and later if we change the model, the serializer won't need to be updated manually What do you think?

**Comment by dhruvkb** [comment]
@krysal that is true, if we let the serializer infer the fields, the code would be very simplified. Would you like to update the PR with your simplified code?

**Comment by krysal** [comment]
Sure! Pushing the change shortly.

**Review by krysal — APPROVED** [review]
Done ✅

**Review by dhruvkb — COMMENTED** [review]
Ah yes, we weren't adding anything truly meaningful with these hardcoded fields. Thanks @krysal.

**Review by sarayourfriend — APPROVED** [review]
What an incredible change for this particular fix :sweat_smile: DRF's magic really shines in times like this when you realise how much it handles automatically for you.

**Pull request merged**
