### PR TITLE
Start data refresh schedule on Tuesdays UTC 00:00

### LINKED ISSUE #2979: Move data refresh schedule to start on Tuesdays UTC 00:00
## Description

Presently, the data refreshes are scheduled to run `@weekly` which means they begin on Sunday at UTC 00:00. This typically means that the process begins over the weekend. While this has been useful in the past, increased instability with the data refreshes has meant that maintainers have come back from the weekend with issues to address.

It would be ideal to start the data refresh on Tuesday, UTC 00:00. This will allow the data refresh to run during the week while maintainers can monitor it and be available to address issues which may arise. It also provides some time on Monday to determine whether or not the data refresh _should_ be run for a given week (e.g. if issues were encountered with the last run or pending changes need to be deployed).

## Additional context

The schedules for both the audio and image data refresh will need to be modified here to become the [cron string `0 0 * * 2`](https://crontab.guru/#0_0_*_*_2) rather than `@weekly`:

https://github.com/WordPress/openverse/blob/a11969e59140c7d23d5eadcedabeb8f21803ff08/catalog/dags/data_refresh/data_refresh_types.py#L49

### PR DESCRIPTION
**Pull request by cullenwatson**
## Fixes

* Fixes #2979 by @AetherUnbound 

## Description

This changes the data refresh schedule to start on Tuesdays UTC 00:00 from the original Sunday at UTC 00:0.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.
- [x] I ran the DAG documentation generator (only applicable for catalog PRs).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Thanks for contributing this change @cullenwatson! We have a standard PR template which we use for pull request descriptions: https://github.com/WordPress/openverse/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Do you mind editing the description of this PR to reflect the contents of the template, with the details for this PR filled in appropriately? Thanks!

**Comment by sarayourfriend** [comment]
@cullenwatson for future contributions, please fill out the PR template body. It includes helpful things like an area for PR description, testing instructions, and, critically, a checklist of things that must be addressed before a PR is ready for review. In this case, the DAG documentation generator needs to be run. Please run `just catalog/generate-dag-docs` locally and commit the changes.

**Comment by sarayourfriend** [comment]
Sorry for the duplicate feedback. Madison's comment hadn't come through while I was writing mine. Thanks for updating the DAG docs and the PR description :pray:

**Review by sarayourfriend — APPROVED** [review]

**Comment by cullenwatson** [comment]
Np, cheers to 10k commits

**Review by dhruvkb — APPROVED** [review]
This expression means [at 00:00 on Tuesday](https://crontab.guru/#0_0_*_*_2) so LGTM!

**Review by krysal — APPROVED** [review]
Thanks for updating the PR description @cullenwatson. Looks good to me!

**Pull request merged**
