### PR TITLE
fix: Changed the default color in Tailwind CSS

### LINKED ISSUE #2439: Tailwind Typography should specify "default" color
## Description

Tailwind Typography currently sets the colors using `theme()` function to get the `dark-charcoal` color from the theme:

https://github.com/WordPress/openverse/blob/04a36fcb320063aa8b42ea703c8059d7254d6990/frontend/tailwind.config.js#L229-L230

However, `dark-charcoal` inside the `theme()` function corresponds to the whole object (not the `DEFAULT` value):
https://github.com/WordPress/openverse/blob/04a36fcb320063aa8b42ea703c8059d7254d6990/frontend/tailwind.config.js#L53-L66

## Fix

We should update the settings to use `theme("colors.dark-charcoal.default")` in these 2 lines:
https://github.com/WordPress/openverse/blob/04a36fcb320063aa8b42ea703c8059d7254d6990/frontend/tailwind.config.js#L229-L230

## Additional context

Discovered when testing Nuxt 3 migration: CSS build step shows warnings of incorrect CSS values. If you look to the values in production, you'll see that the body color in content pages is not set, but it's still correctly using `dark-charcoal` color because it falls back to the color declared for `html`

### PR DESCRIPTION
**Pull request by vishalpawarR**
## Fixes

Fixes #2439 by @obulat

Updated the settings to use theme("colors.dark-charcoal.default")

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Thank you for the quick fix, @vishalpawarR, and welcome to Openverse! I've updated the description to remove the `[]` brackets around the issue it fixes and by who so that the links work correctly.

Could you add a sentence to the PR "Description" saying what this PR does? You can copy some info from the issue it solves.

**Comment by vishalpawarR** [comment]
> Thank you for the quick fix, @vishalpawarR, and welcome to Openverse! I've updated the description to remove the `[]` brackets around the issue it fixes and by who so that the links work correctly.
> 
> Could you add a sentence to the PR "Description" saying what this PR does? You can copy some info from the issue it solves.

Hey! Thank you for accepting the PR and It was showing some errors before for adding the some label where to add these labels and how to solve that issue?

I have added some description to the PR.

**Comment by obulat** [comment]
> > Thank you for the quick fix, @vishalpawarR, and welcome to Openverse! I've updated the description to remove the `[]` brackets around the issue it fixes and by who so that the links work correctly.
> > Could you add a sentence to the PR "Description" saying what this PR does? You can copy some info from the issue it solves.
> 
> Hey! Thank you for accepting the PR and It was showing some errors before for adding the some label where to add these labels and how to solve that issue?
> 
> I have added some description to the PR.

Thank you for adding the description! It's necessary for other reviewers to understand what needs to be checked.

The labels were not added automatically because of the `[]` around the issue number, so I added the labels manually.  Next time, if you write a sentence like "Fixes #2439", without the braces, the PR will be labeled automatically.

**Review by zackkrida — APPROVED** [review]
Perfect, thank you @vishalpawarR!

**Pull request merged**
