### PR TITLE
Add `standardized_popularity` to Catalog media tables

### LINKED ISSUE #2087: Add `standardized_popularity` column to the Catalog media tables
## Description

Add `standardized_popularity` as a nullable column to the catalog media tables.

```pgsql
ALTER TABLE image ADD COLUMN standardized_popularity DOUBLE PRECISION;
ALTER TABLE audio ADD COLUMN standardized_popularity DOUBLE PRECISION;
```

We can do this manually in production, but we should also update the table schemas ([image](https://github.com/WordPress/openverse/blob/0642022fb9c81d0ae49a1ed8ac726bf8509febcd/docker/upstream_db/0003_openledger_image_schema.sql) and [audio](https://github.com/WordPress/openverse/blob/0642022fb9c81d0ae49a1ed8ac726bf8509febcd/docker/upstream_db/0006_openledger_audio_schema.sql)).

## Additional context

After this change is made, ingestion and data refreshes should continue to work as normal.

This change blocks all other changes for this project.

### PR DESCRIPTION
**Pull request by stacimc**
## Fixes

Fixes #2087 by @stacimc 

## Description

Adds `standardized_popularity` to the media tables in the Catalog DB.
We will also need to add them manually in production:

```pgsql
ALTER TABLE image ADD COLUMN standardized_popularity DOUBLE PRECISION;
ALTER TABLE audio ADD COLUMN standardized_popularity DOUBLE PRECISION;
```

## Testing Instructions

1. Pull this branch.
2. Recreate the Catalog (`just catalog/recreate`)
3. Open a db shell (`just catalog/pgcli`)
4. Inspect the image and audio tables to see that the column was added:

```
openledger> describe image;
+-------------------------+--------------------------+--------------------------------------+
| Column                  | Type                     | Modifiers                            |
|-------------------------+--------------------------+--------------------------------------|
| identifier              | uuid                     |  not null default uuid_generate_v4() |
| created_on              | timestamp with time zone |  not null                            |
| updated_on              | timestamp with time zone |  not null                            |
| ingestion_type          | character varying(80)    |                                      |
| provider                | character varying(80)    |                                      |
| source                  | character varying(80)    |                                      |
| foreign_identifier      | character varying(3000)  |                                      |
| foreign_landing_url     | character varying(1000)  |                                      |
| url                     | character varying(3000)  |  not null                            |
| thumbnail               | character varying(3000)  |                                      |
| width                   | integer                  |                                      |
| height                  | integer                  |                                      |
| filesize                | integer                  |                                      |
| license                 | character varying(50)    |  not null                            |
| license_version         | character varying(25)    |                                      |
| creator                 | character varying(2000)  |                                      |
| creator_url             | character varying(2000)  |                                      |
| title                   | character varying(5000)  |                                      |
| meta_data               | jsonb                    |                                      |
| tags                    | jsonb                    |                                      |
| watermarked             | boolean                  |                                      |
| last_synced_with_source | timestamp with time zone |                                      |
| removed_from_source     | boolean                  |  not null                            |
| filetype                | character varying(5)     |                                      |
| category                | character varying(80)    |                                      |
| standardized_popularity | double precision         |                                      |
+-------------------------+--------------------------+--------------------------------------+
Indexes:
    "image_pkey" PRIMARY KEY, btree (identifier)
    "image_identifier_key" UNIQUE, btree (identifier)
    "image_provider_fid_idx" UNIQUE, btree (provider, md5(foreign_identifier::text))
    "image_url_key" UNIQUE, btree (url)

openledger> describe audio;
+-------------------------+--------------------------+--------------------------------------+
| Column                  | Type                     | Modifiers                            |
|-------------------------+--------------------------+--------------------------------------|
| identifier              | uuid                     |  not null default uuid_generate_v4() |
| created_on              | timestamp with time zone |  not null                            |
| updated_on              | timestamp with time zone |  not null                            |
| ingestion_type          | character varying(80)    |                                      |
| provider                | character varying(80)    |                                      |
| source                  | character varying(80)    |                                      |
| foreign_identifier      | character varying(3000)  |                                      |
| foreign_landing_url     | character varying(1000)  |                                      |
| url                     | character varying(3000)  |  not null                            |
| thumbnail               | character varying(3000)  |                                      |
| filetype                | character varying(5)     |                                      |
| duration                | integer                  |                                      |
| bit_rate                | integer                  |                                      |
| sample_rate             | integer                  |                                      |
| category                | character varying(80)    |                                      |
| genres                  | character varying(80)[]  |                                      |
| audio_set               | jsonb                    |                                      |
| set_position            | integer                  |                                      |
| alt_files               | jsonb                    |                                      |
| filesize                | integer                  |                                      |
| license                 | character varying(50)    |  not null                            |
| license_version         | character varying(25)    |                                      |
| creator                 | character varying(2000)  |                                      |
| creator_url             | character varying(2000)  |                                      |
| title                   | character varying(5000)  |                                      |
| meta_data               | jsonb                    |                                      |
| tags                    | jsonb                    |                                      |
| watermarked             | boolean                  |                                      |
| last_synced_with_source | timestamp with time zone |                                      |
| removed_from_source     | boolean                  |  not null                            |

...skipping 1 line
+-------------------------+--------------------------+--------------------------------------+
Indexes:
    "audio_pkey" PRIMARY KEY, btree (identifier)
    "audio_identifier_key" UNIQUE, btree (identifier)
    "audio_provider_fid_idx" UNIQUE, btree (provider, md5(foreign_identifier::text))
    "audio_url_key" UNIQUE, btree (url)
```

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by krysal — APPROVED** [review]
LGTM

**Review by zackkrida — APPROVED** [review]
Simple, works as-described locally. LGTM.

**Review by AetherUnbound — APPROVED** [review]
Looks great! Since these are the base tables I don't think they require any extra changes to `common/popularity/sql.py`, which is good :smile:

**Comment by stacimc** [comment]
I added null `standardized_popularity` to all of the sample data, to prevent failures in the `load_sample_data` step. You can test that it works by running a full `just recreate`.

**Pull request merged**
