### PR TITLE
Enable the sensitive content flag and cleanup

### LINKED ISSUE #3142: Enable sensitive content feature flag in production & cleanup
## Problem

The sensitive content feature flag is currently behind a feature flag and not accessible on prod. The goal is to enable the flag, and clean up the code to remove flag artefacts like `if`/`v-if` conditions.

## Description

Since that feature has been developed and extensively tested in local and staging environments, it is time to unveil it and make it generally available for all users.

## Additional context

An announcement for this feature can be made after the corresponding PR is merged into `main` and subsequently deployed to prod.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #3142 by @dhruvkb

## Description

This PR enables the 'sensitive_content' feature flag by deleting the flag and ensuring all usages of the flag evaluate to `true`.

## Testing Instructions

0. Check out the PR and run the dev server.
1. Ensure that all features behind this flag are generally accessible.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — COMMENTED** [review]
This looks great! I'll test it locally tomorrow. One question: do we want to keep the `fake_sensitive` flag for testing in staging?

**Comment by dhruvkb** [comment]
I think that flag would be useful during development because it allows us to work on sensitivity features without exposing us to real sensitive content.

**Review by obulat — APPROVED** [review]
LGTM, everything works well locally 🚀

**Review by AetherUnbound — APPROVED** [review]
Changes look good, ran this locally and the sensitive content features were enabled as expected!

**Comment by dhruvkb** [comment]
Merging this PR. The next prod deployment of the frontend will enable this feature in production!

**Pull request merged**
