### PR TITLE
Add analytics stack label

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes failing stack label check in https://github.com/WordPress/openverse/pull/943

## Description

Do we actually want this? **How do we decide what the "stacks" are?**

## Testing Instructions

Test by confirming the check passes in this PR with the analytics label.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
I think we can drop the analytics stack. IIRC I added that when we hadn't picked on a backend for the analytics (and there was a possibilitiy to use a custom-made services like we had before) and then changed my mental association to refer to the Plausible + PostgreSQL + Clickhouse services. Considering that the `🧱 stack: frontend` labels covers this use case, we can drop the label and close the PR too.

As for what constitutes the stack, that's a good question and one that needs more clarity, and possibly better naming.

- backend (unclear, I intended to deprecate this eventually, and replace with one of the following)
  - API
  - ingestion sever
- frontend
- mgmt

**Comment by sarayourfriend** [comment]
> Considering that the 🧱 stack: frontend labels covers this use case

This is only true if we assume that Django won't be sending analytics events. #873 requests one analytics event added on the API side.

I'm not sure what the intention of the stack labels is though, what they mean to convey.

> As for what constitutes the stack, that's a good question and one that needs more clarity, and possibly better naming.

Can you open an issue for this? It shouldn't be too hard to do, just need a backfill job or manual work to switch things that used the old "backend" label so we can delete it, right?

**Review by obulat — APPROVED** [review]
I think that we do need `analytics` stack label that would mainly apply to the backend Plausible set up, but maybe also some Nuxt analytics issues.

As for the other "stacks", I've used the ["No stack" view ](https://github.com/orgs/WordPress/projects/75/views/18)in the Openverse project to assign `api` or `ingestion_server` labels to all that had been labeled `backend` for the ease of transition to the monorepo.

Now, there are some issues that still don't have a stack, and they can be grouped into:
- Browser extension deprecation issues (should this be `mgmt`?)
- Infrastructure issues (new stack?)
- WordPress integration (new stack?)

**Comment by dhruvkb** [comment]
@obulat do we have infra issues in this repo? WordPress plugins do seem like a new stack. Also documentation deservers to be a stack, considering it's a standalone Sphinx project.

**Comment by sarayourfriend** [comment]
@dhruvkb Do you have any further thoughts on this PR? I'd like to close it if we don't want to take this approach. But then it's worth discussing the stack labels a bit more generally elsewhere to clarify what their purpose is and how we would decide to add new ones.

**Comment by dhruvkb** [comment]
I think we can close the PR, or put it on hold, till we have a discussion to clearly understand what the labels actually mean.

**Comment by sarayourfriend** [comment]
Sounds good! Identifying the use-cases for them during that future discussion will hopefully help give clarity.

**Pull request closed without merging**
