### PR TITLE
Retry `up` recipe in case port is occupied

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Addresses https://github.com/WordPress/openverse/issues/200#issuecomment-1257716418

## Description

Since there are flaky occurrences of ports being in use, this PR makes `just up` run thrice with 5 second pauses so that the port can be grabbed. I think this should work because the issue goes away during the re-run of the failing jobs.

## Testing Instructions

As seen in the screenshot, the first run is the output when a service is bound to port 50254 and thus the `db` service, which needs it cannot run. The second run is the output when that port is available.

Screenshot 2023-03-22 at 9 13 26 PM

If the port is freed up within 15 seconds, the `up` command will succeed and the CI+CD jobs will continue to run.

## Checklist

- [X] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [X] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@dhruvkb It seems we were occupied by the same concerns recently :) I wrote this issue proposing an alternative solution: https://github.com/WordPress/openverse/issues/1035

This one doesn't add _too_ much complexity, so I don't think the approach in this PR isn't worth doing. But I think the solution I proposed in the linked issue would solve the problem outright with absolutely no chance of flakiness: provided it is actually possible.

**Comment by dhruvkb** [comment]
@sarayourfriend your observation about not needing to bind ports is true for CI. That's seems like a concrete avoidance of the problem compared to bandaging on top of it (that this PR does). It does add a little bit of complexity, however `just dc` takes care of assigning the right Compose config file, so the overriding of multiple Compose files can be handled by `just` itself.

Nonetheless, retrying `up` does not cause any negative effects so I'll merge this PR if it gets the two approvals. If #1035 is resolved first, I'll close this PR as unmerged.

**Review by obulat — APPROVED** [review]
LGTM!

**Review by stacimc — APPROVED** [review]
Looks good and discussion [here](https://github.com/WordPress/openverse/pull/990#issuecomment-1484518542) makes sense to me 👍

**Pull request merged**
