### PR TITLE
Add throttle classess for health check endpoint

### LINKED ISSUE #1924: Healthcheck endpoint throttles load balancer health checks
## Description

The API healthcheck endpoint uses the default anon rate limits. This causes the load balancers to be throttled when making healthcheck requests.

## Reproduction

This is evident in deployment logs (non-public) but is reproduced locally by turning on throttling and making healthcheck requests.

## Additional context

We should increase the throttle rate for this to 2/minute to match the load balancer's healthcheck interval of 30 seconds.

I do not think we should increase the load balancers healthcheck interval as it would increase deployment times.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #1924 by @sarayourfriend 

## Description

Increase the throttle rate for this endpoint as per suggested in the issue (albeit giving it a leeway). I believe this is the first use of the `ExemptOAuth2IdRateThrottle` class as well, seems suitable in this case though I don't think we make many of these requests authenticated.

## Testing Instructions

Run the django app and try to make several requests to http://localhost:50280/healthcheck/ See

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
Could you add some unit tests, please? Other than that, LGTM! Approving to unblock.

**Review by sarayourfriend — APPROVED** [review]
LGTM. I don't know exactly what kind of unit test would be useful for this as all the ones I can think of would mostly be testing DRF rather than our code. This PR seems more like configuration than anything.

By the way, `ExemptOAuth2IdRateThrottle` is in the default throttle classes and the frontend relies on it already, so it is well tested in production.

**Comment by krysal** [comment]
I thought the same as Sara first but as per Dhruvk request, I checked test locally with `DISABLE_GLOBAL_THROTTLING=False` and health check tests failed. This situation is a bit complicated as I can't find a way to disable throttling _only for certain tests_. So I'll merge this for now as that would require more investigation but this is necessary for the following deployments.

**Comment by sarayourfriend** [comment]
> I thought the same as Sara first but as per Dhruvk request, I checked test locally with DISABLE_GLOBAL_THROTTLING=False and health check tests failed. This situation is a bit complicated as I can't find a way to disable throttling only for certain tests. So I'll merge this for now as that would require more investigation but this is necessary for the following deployments.

We may need an issue to do this as it would be helpful for some tests we already have that will fail if you run them multiple times in succession due to rate limiting.

To do it we'd need to update our rate limiting class to check settings at runtime. As it stands, our approach to disabling throttling is to just remove all the throttling configuration in the settings at start-up so any runtime changes to the `DISABLE_GLOBAL_THROTTLING` doesn't cause a difference unless you force the settings module to be re-evaluated.

**Pull request merged**
