### PR TITLE
Add report creation, better filtering and more improvements to admin views for media

### LINKED ISSUE #4412: Make admin media endpoint work for all media items not just those with reports
## Problem

Currently the admin media endpoints at `admin/api/{media_type}/{id}/change/` do not resolve for media items that do not have reports because such media items are excluded from the queryset.

## Description

We need to include these media items in the queryset while providing ways to filter them down to those with reports to get to the moderation queue.

### LINKED ISSUE #4413: Include report filing in admin media view
## Description

As of #4386, the media admin view has a form to take moderation decisions. This view should be expanded to provide a way to file reports as well, using a similar form-based implementation.

This would make the admin media view the comprehensive page to file reports and take actions against media items.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #4412 by @dhruvkb 
Fixes #4413 by @dhruvkb

## Description

This PR
- updates the sidebar filter to show both moderation queue and all media items
- enables the creation of reports from the media change view
- makes code quality and interface improvements
  - use of descriptions as per Django admin UI
  - changing hardcoded URLs to `{% static %}`
  - showing helpful messages when reports/decisions do not exist

## Testing Instructions

1. Check out the PR and run the dev server.
2. Go to the image/audio list, you should see the moderation queue by default.
3. Click on "All" in the sidebar, you should now see all 5000 media items listed.
4. Open an item that's not in the moderation queue, you should see descriptive messages in the report and decision list sections.
5. Create a report using the form in the "Create report", the report should appear in the "Reports" section under it.
6. Take a decision for the report using the "Create decision" section, the decision should appear in the "Decisions" section under it.

This way the complete flow for reporting and moderating any individual media item is present in one page. However moderation flow involving multiple media items cannot be accomplished using this process.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`just catalog/generate-docs media-props`
      for the catalog or `just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Such improvements since the last time I looked at this code!

Do we really need to have a different word ("complain") for the reporting view? I think it would be easier to keep a single name.

**Comment by dhruvkb** [comment]
The main reason for using the word "complain" was that it is a verb that corresponds to the creation of a "report" similar to how the verb "moderate" corresponds to the creation of a "decision" model instance.

I wanted to avoid the potential confusion that can occur because "report" is both a noun and a verb, and also used in a number of places to refer to the `ImageReport` and `AudioReport` models together.

That said, I'm happy to change the name if more people feel the same way as @obulat.

**Review by zackkrida — APPROVED** [review]
LGTM. I share @obulat's preference about the name, though. I don't consider it blocking, but "complain" is such a new concept to introduce that I can see it leading to confusion. I'd like to see either:

- Comment(s) explaining the naming
- An alternative name like "media_submit", "media_create_report", or something

**Comment by dhruvkb** [comment]
Ok, I've replaced verbs "complain" and "moderate" with "report_create" and "decision_create" in commit f9a7402.

**Pull request merged**
