### PR TITLE
Send SELECT_SEARCH_RESULT event only on left-mouse clicks

### LINKED ISSUE #2551: Any mouse click on a search results sends `SELECT_SEARCH_RESULT` analytics event
## Description

`SELECT_SEARCH_RESULT` event should be sent when the user clicks the main (left) mouse button.

Now it is sent when you click any mouse button. Do we want to send this event if the user click an auxiliary mouse button (usually right)? It can be used to see if the users are using "Right-click" -> "Open in a new tab", do we want to track these events?

## Reproduction

1. Run the app, search for something and click on a search result with a secondary button (usually right).
2. See the `SELECT_SEARCH_RESULT` logged in the console

## Additional context

Vue has `.left` modifier for the `click` event: https://vuejs.org/guide/essentials/event-handling.html#key-modifiers, but I'm not sure if it can be used.
We can also just check for `button` property in the `click` event handler: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

### PR DESCRIPTION
**Pull request by aneevel**
## Fixes

Fixes #2551 by @obulat 

## Description

When sending a SELECT_SEARCH_RESULT event, there is now a check that the event was performed with the primary mouse button (typically left-mouse click) before propagating the event

## Testing Instructions

Run the app, and search for anything. Click on any search result with the primary mouse button and check the console; you will see a SELECT_SEARCH_RESULT logged in the console. Click on any search result with a button other than primary and check the console; you will not see an event logged to the console.

## Checklist

- [X] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [X] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you for great work, @aneevel! Could you revert the changes to `pnpm-lock.yaml`? Are you using a different version of pnpm than what is used in this repository? We are still on v.7, and the current version is 8. This might have caused the unnecessary changes.

**Comment by aneevel** [comment]
Thanks for the help @obulat - I've reverted `pnpm-lock.yaml` as requested.

**Review by obulat — APPROVED** [review]
🎉

**Review by sarayourfriend — COMMENTED** [review]
This LGTM! @aneevel, are you able to add a Playwright test for this case? @obulat let me know if you don't think that's necessary for this change and I'll approve it instead.

**Review by dhruvkb — APPROVED** [review]
We should try to get this merged, even without the Playwright test, before the frontend code freeze. @aneevel if you've been working on it (and can still add the test), let us know.

**Comment by sarayourfriend** [comment]
Good point, Dhruv. Let's merge this now, then. If there's work on a playright test it can be in a separate PR anyway, right?

**Comment by sarayourfriend** [comment]
Here's an issue to follow up on the unit test: https://github.com/WordPress/openverse/issues/3555

**Pull request merged**
