### PR TITLE
Update media list admin view to add ES-powered search

### LINKED ISSUE #3841: Update admin Media views with new filters and bulk actions
## Description

Blocked by #3840 

Update the Media views in the Django admin to support bulk moderation decisions. This includes two parts:

* Add the actions for bulk deindexing and marking sensitive, implemented in #3840, to the dropdown in the Media views. Bulk actions should only be available to maintainers.
* Add new filters to facilitate searching for records for bulk decisions. These should be implemented as additional custom text filters in the sidebar for the Media views. **The filters should query Elasticsearch rather than Postgres.** 
  * `query` - this field searches for a match in description, tags, or title
  * `provider`
  * `creator` - this field should have helptext reminding the user to also filter by provider in order to disambiguate a specific creator.

## Additional context

Context in the IP [here](https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20240122-implementation_plan_bulk_moderation_actions.html#media-views).

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Partially addresses #3841 by @stacimc 

## Description

This PR
- adds advanced search to media list view, powered by Elasticsearch
- adds source/provider filters to media list view

Combined with the bulk moderation action added in #4654, the linked issue is fully resolved.

## Testing Instructions

0. Check out the PR and run the API.
1. Visit the admin page for image list (or audio list).
2. Search for the following:
   - a specific UUID `3b858852-67df-44e1-8d57-683991d3ec67`
   - a specific creator `creator:"Al S"`
   - a creator with wildcard `creator:Al*`
   - a word in the document `cat`
   - a word in a specific field `tag.name:cat`
8. Combine your searches with a source/provider filter from the right sidebar for further narrowing.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
This is excellent, I think however instead of _only_ recommending query string syntax for advanced search, that specific functionality should be documented. The examples from your PR description may be sufficient! 

This is meant to cover this note in the issue and IP:

> this field should have helptext reminding the user to also filter by provider in order to disambiguate a specific creator.

But also, I think this type of documentation and examples will make this much easier for moderators to remember.

Side note: `/admin/api/image/` still times out with a 504 in production. Are there any plans in the remaining issues for this moderation project to make that page work, or an issue you're aware of to capture that problem?

**Comment by dhruvkb** [comment]
@zackkrida since the examples and explanation for the search functionality might be a bit too long to fit below the search box, would you recommend I make a separate page for this in the docs and link to it from the search bar help text?

That page could document all the different search options from the PR explanation as well as the note about disambiguating a creator by filtering by providers.

**Comment by zackkrida** [comment]
@dhruvkb I think some of the value comes from these notes being inline and quick to access for moderators. A page is acceptable but my preference would be text directly on the page. The default font size is so small that a lot of text only takes up a few lines. Additionally, I had an idea: Using a `<details><summary>Examples<summary><ul><li>Example 1</li></ul></details>` block would be an elegant way to show a collapsible list of examples! Put together it all looks something like this:

image

I'll support any approach, however.

**Comment by dhruvkb** [comment]
Great idea to use `<details>`, implemented in 3d4d094.

**Review by zackkrida — APPROVED** [review]
Looks great!

**Pull request merged**
