### PR TITLE
Add test/ to .dockerignore to exlcude tests and test assets from frontend image build context

### LINKED ISSUE #856: Exclude tests and test assets from frontend image build context
## Description

The `test/` directory inside frontend is over a 100MB in size. Excluding it from the build context will make the images smaller and make the build a little faster. We don't need tapes and visual regression snapshots in our staging/prod containers.

## Screenshots

image

Screenshot 2023-03-07 at 11 14 26 AM

### PR DESCRIPTION
**Pull request by sehgxl**
Fixes #856 by @dhruvkb 

## Description

Adds `test/` to the file `openverse/frontend/.dockerignore`

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sehgxl** [comment]
@dhruvkb I was looking up online. I have an idea of how to make a volume and mount it to a docker container. But I am not able to figure out how to add the `test/` directory to the volume. Let me know where I can know more about this.

**Comment by AetherUnbound** [comment]
@sehgxl the tests folder will need to be added to the volume mount here:
https://github.com/WordPress/openverse/blob/8afb04bc81429cda3f0aa3f8be1d22ad4bd8cbc7/frontend/docker-compose.playwright.yml#L10-L13

Likely something along the lines of ` - ./test:/frontend/test`. Although, it looks like those files should be mounted anyway, so I'm a bit surprised that adding them to the ignore is causing the tests to fail 🤔

**Comment by AetherUnbound** [comment]
I've kicked off the failed tests again, perhaps it was a flake!

**Review by dhruvkb — APPROVED** [review]
On `main`: 780MB
On this PR, with `main` merged: 652MB (smaller by ~16%)

LGTM, Good work! Thanks @sehgxl.

**Review by AetherUnbound — APPROVED** [review]
Excellent, thanks for the contribution!!

**Comment by sehgxl** [comment]
@AetherUnbound @dhruvkb Thanks guys for the help!

**Comment by AetherUnbound** [comment]
@sehgxl I'm not a guy, but I'm still happy to have been of assistance 😁

**Comment by sehgxl** [comment]
> @sehgxl I'm not a guy, but I'm still happy to have been of assistance 😁 

My bad, have edited the comment :)

**Pull request merged**
