### PR TITLE
Use Elasticsearch configuration file to avoid tricky envvar names

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes https://github.com/WordPress/openverse/issues/4974 by @zackkrida 

## Description

See [my comment on the issue clarifying the cause and long-term fixes](https://github.com/WordPress/openverse/issues/4974#issuecomment-2375037131) for additional rationale of this change.

TL;DR: Docker compose broke the way environment variables are parsed, and no longer accepts those defined in `es/env.docker`. On the other hand, it appears that there is no way to pass allow-origin as an environment variable, as ES will not recognise the same option with an underscore, and provides no method to map hyphens. The configuration file is much more searchable against the docs anyway.

## Testing Instructions

CI must pass (proving ES is accessible throughout the development stack). Also check out this branch and run `ov j api/up` to get ES running locally, and make an http request like `ov http http://0.0.0.0:50292/_cluster/health`. Also use a tool like Elasticvue to prove CORS is working for local development usage.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
The approach taken looks correct and I do think ultimately this is a better approach even if it was forced on us by docker compose. 

One caveat to my review is that I am away from my computer and cannot run this locally. It does look right though, so feel free to use your discretion in merging.

**Comment by sarayourfriend** [comment]
I'll merge based on that review, my testing locally using the tests I shared in the PR description, and the fact that CI passes, which includes running API tests and loading sample data, both of which use the local Elasticsearch cluster.

**Comment by AetherUnbound** [comment]
I'm looking now as well, if you wanted a second set of eyes before merging.

**Comment by sarayourfriend** [comment]
Ah, sorry @AetherUnbound, your comment had not come through on the page! If you find any issues I am around to hotfix.

**Comment by AetherUnbound** [comment]
No worries, changes look good to me!

**Pull request merged**
