### PR TITLE
Bump the minimum required PDM version for the API

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

I was seeing an issue on `main` where when I tried to run `ov just build`, I got the following error:

```
------
 > [web builder 5/5] RUN pdm install --check --frozen-lockfile --dev:
1.475 WARNING: Lockfile is not compatible with PDM
1.476 Please run `pdm lock` to update the lock file
------
failed to solve: process "/bin/sh -c pdm install --check --frozen-lockfile $PDM_INSTALL_ARGS" did not complete successfully: exit code: 1
error: Recipe `dc` failed on line 209 with exit code 17
error: Recipe `build` failed on line 213 with exit code 17
```

@dhruvkb pointed out that this version might need to be bumped, and indeed it helped resolve the issue on my end!

## Testing Instructions

Check out this branch and run `ov just build`, ensure that everything works as expected.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
Since the `lock_version` got bumped to the latest version, I suspect Renovate uses the latest version of PDM. So I suppose we could also drop the version and let `pip` install the latest one automatically?

**Comment by AetherUnbound** [comment]
> Since the `lock_version` got bumped to the latest version, I suspect Renovate uses the latest version of PDM. So I suppose we could also drop the version and let `pip` install the latest one automatically?

Only trouble with that approach is that, because the line doesn't change in the `Dockerfile`, I'm not sure when Docker would necessarily know it needs to re-run the install of PDM (and thus resolve issues like this which occur in the future). Hopefully the structure of the lockfile doesn't change too frequently.

**Review by zackkrida — APPROVED** [review]

**Comment by sarayourfriend** [comment]
I agree with Dhruv, dropping the version might be the way to go. I think that `apt-get ...` line runs every single time I run `just build web`, but we could copy the lockfile in before it if we wanted to make sure it definitely ran anytime the lockfile changed.

Not sure what PDM's backwards compatibility approach is though. Pinning to a major version is probably a good idea...

**Comment by AetherUnbound** [comment]
> I think that `apt-get ...` line runs every single time I run `just build web`

Those layers should almost certainly be cached, it seems odd that would be happening every time 🤔 That said, I'm going to go ahead and merge this, but the idea of moving the `pdm.lock` copy step to before the install could work. We should probably move the `pip install pdm` line to a different `RUN` layer so the `apt-get install` line can be cached more frequently, since the lock file can change quite often and it might be a nuisance to reinstall _all_ dependencies even if only the python ones have changed.

**Pull request merged**
