### PR TITLE
Remove unused thumb tapes

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

I didn't open an issue for this. While working on #3186, I realized that there are a lot of thumbnail tapes that are not used in tests, and their lack does not affect the CI.

## Description

This PR removes the thumb tapes that don't affect the CI.

## Testing Instructions

The CI should pass.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by krysal** [comment]
Why are they not used anymore?

**Review by dhruvkb — APPROVED** [review]
CI is passing so I guess they really are unused.

**Review by sarayourfriend — DISMISSED** [review]
Awesome! I wonder if there's any way for us to automatically detect unused tapes :thinking: Apparently talkback is capable of giving that information: https://github.com/ijpiantanida/talkback#exit-summary

**Comment by sarayourfriend** [comment]
> CI is passing so I guess they really are unused.

I was thinking about this for how to respond to @krysal. I don't know if it's 100% true that these aren't used just because CI passes. It could be that CI passed because the thumbnails were just requested (successfully) as normal?

@obulat how did you tell that these weren't being used? Did you use the talkback summary?

**Comment by obulat** [comment]
When working on #3186, I deleted all of the thumbnail tapes, and then ran `playwright` tests with `UPDATE_TAPES=true`. Then I checked out `main`, compared it to #3186, and deleted all the tapes that were not updated in #3186.

> @obulat how did you tell that these weren't being used? Did you use the talkback summary? I wonder if we used page.route, would we be better able to intercept thumbnails without needing to use tapes while also making sure that we aren't accidentally making thumbnail requests?

We decided that we **want** to use the real images because they would should the image grid with images of different sizes. If we only block the `thumb` requests, then the frontend will try to use the source direct URL which will mean making network requests. We could block both the thumb and the direct URL requests for some tests, where the image sizes are not important (e2e tests). In this case, the fallback image will be used.

**Review by AetherUnbound — APPROVED** [review]
That's a lot of lines deleted, what a ratio! 😄

**Pull request merged**
