### PR TITLE
Split deployment workflow into 4 separate workflows

### LINKED ISSUE #877: Refactor deployment workflow into separate workflows per app and environment
## Problem

Before the monorepo switch, it was possible to view distinct workflow logs for staging and production frontend deployments by filtering the deployment workflow on the event trigger. This is no longer possible as the event is always dispatched (a distinct event type) and the same workflow is shared for all four of our apps + environments deployed via the workflow.

## Description

Split the Deployment workflow into four separate workflows named something like:

- Staging Frontend Deployment
- Production Frontend Deployment
- Staging API Deployment
- Production API Deployment

These workflows should still accept a tag. Update the CI+CD workflow to dispatch the staging frontend and staging API deployment workflows instead of directly calling the composite action so that the staging deployment workflows will have proper logs for each staging deployment.

These workflows will also double as rollback workflows and should all have the same "protection" applied so that only specific people can successfully dispatch the workflow.

## Alternatives

There are probably some more complex alternatives to this using callable workflows or some other GitHub feature. Or we could store the deployment logs in a file somewhere and have it automatically updated by the workflow. All of those options seem much more complicated than just splitting the existing Deployment workflow and using it consistently.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #877 by @sarayourfriend

## Description

This PR applies https://github.com/WordPress/openverse-infrastructure/pull/412 separates the single deployment workflow we had before into 4 separate workflows. Future iterations within this PR will also call the workflow from the existing workflows that instead directly call the composite action.

## Testing Instructions

Testing will be done on this branch.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Excellent, this worked as expected! See the deployment here: https://github.com/WordPress/openverse/actions/runs/4389610476/jobs/7687454499

**Review by dhruvkb — APPROVED** [review]
This is great! 

I did not know it was possible to invoke workflows with `uses` and now I'm thinking if there are other chunks we can break from this file to keep it small and manageable. This file could then just be an outline of the steps, describing the `needs` and `if` conditions with the actual jobs defined separately.

**Comment by AetherUnbound** [comment]
> I did not know it was possible to invoke workflows with `uses` and now I'm thinking if there are other chunks we can break from this file to keep it small and manageable. This file could then just be an outline of the steps, describing the `needs` and `if` conditions with the actual jobs defined separately.

That exact thought was brought up by @sarayourfriend during our last team meeting! The CI/CD workflow is (understandably) a behemoth at this point, even just splitting some sections out by per-service workflows could help readability.

**Comment by dhruvkb** [comment]
> The CI/CD workflow is (understandably) a behemoth at this point 

And it will blow up when the catalog is included. So +1 for that.

**Review by sarayourfriend — APPROVED** [review]
:rocket:

**Comment by sarayourfriend** [comment]
I'm going to merge this as I'd like to work on #876 today and it'll be useful to have these four workflows available to link to in the document :rocket:

**Pull request merged**
