### PR TITLE
Use `.venv` for catalog virtualenv instead of `venv`

### LINKED ISSUE #4109: Use `.venv` for catalog virtualenv
## Problem

The catalog virtualenv is currently placed in `venv/` in the catalog directory. This is a bit non-standard and the conventional name of the virtualenv directory is `.venv/`.

## Description

The catalog should be updated to create and use a virtualenv in the `.venv/` directory.

## Additional context

All major package managers adhere to this convention.

- [Poetry](https://python-poetry.org/docs/configuration/#virtualenvsin-project)
- [Rye](https://rye-up.com/guide/faq/#can-i-relocate-virtualenvs)
- [PDM](https://pdm-project.org/latest/usage/venv/#the-location-of-virtualenvs)

### PR DESCRIPTION
**Pull request by thegreendrinker**
## Fixes

Fixes #4109  by @dhruvkb 

## Description

Changed `openverse/catalog/justfile` so that the catalog automatically creates virtualenv at `/.venv` instead of `/venv`. Also updated `documentation/catalog/guides/quickstart.md` so that it includes the new instructions to create virtualenv (utilizing `just`) and deleted the old ones. 

## Testing Instructions

First run `rm -R catalog/venv catalog/.venv` to get rid of any existing environments to start from scratch. Then run `just catalog/venv` to create the virtualenv. Utilizing `ls -a` ensure that `catalog/.venv` exists and not `catalog/venv`.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`just catalog/generate-docs media-props`
      for the catalog or `just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
Looks great, I tested this locally and verified that the virtual environment was created in the right place!

**Comment by AetherUnbound** [comment]
Ahh actually, I think we'll need one more change - we need to add the `.venv` folder to the `.gitignore`, it can probably be added here:

https://github.com/WordPress/openverse/blob/3d6e8b5ab96a31ba6da84feb292790f97b39f4a8/.gitignore#L19-L18

**Review by dhruvkb — CHANGES_REQUESTED** [review]
LGTM, and thanks for the contribution @thegreendrinker! 

Only requesting a change to restore the `.gitignore` file and pull from `main`.

**Comment by thegreendrinker** [comment]
I did as you instructed and did `git pull origin main` on my local `catalog_virtualenv` branch after resetting to remove the `.gitignore` change, but my local version of `gitignore` does not include `.venv`.

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Review by dhruvkb — APPROVED** [review]
Awesome, LGTM! Thanks for the contribution @thegreendrinker!

**Pull request merged**
