### PR TITLE
Update internal header snapshots

### LINKED ISSUE #2473: "visual-regression/v-header-internal.spec.ts:35:11 › VHeaderInternal › screen at breakpoint xs with width 340 › mobile-header-internal-modal-ltr" is flaky
## Description

Failed run on `main` CI: https://github.com/WordPress/openverse/actions/runs/5340998522/jobs/9681413214

Test results artefact: [storybook_test_results.zip](https://github.com/WordPress/openverse/files/11828233/storybook_test_results.zip)

## Additional context
Marked critical as per our policy for flaky tests

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2473 by @sarayourfriend

## Description

This PR
- updates flaky snapshots, actually showing the difference in logo size
- removes unused snapshots

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
I know this is still a draft, but checks are passing 👍 I believe it resolves the issue.

**Comment by dhruvkb** [comment]
The initial diff also showed a small difference in the fonts that I don't know how to debug. It has to be pretty rare because it's the first time I've seen this type of difference.

**Review by AetherUnbound — APPROVED** [review]
LGTM!

**Comment by sarayourfriend** [comment]
> It has to be pretty rare because it's the first time I've seen this type of difference

IIRC @obulat Had to deal with something around this in the past that had to do with how Ubuntu (the Playwright container's base image) loads fonts.

**Pull request merged**
