### PR TITLE
Do not use unstable pook reference for API

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

https://github.com/h2non/pook/pull/132 will introduce breaking changes to pook. There isn't a version released with the breaking changes yet, but if I merged the PR, the Openverse API tests would start failing due to it being affected by the breaking changes that will come in pook v2. The API uses `master` instead of a stable version reference, so anything that changes on `master` could break the API if a new `pdm lock` updates the git revision used in the lock file.

## Description

Change `pook` in the API pyproject.toml to use a real version range.

The catalog and ingestion servers also use pook but already use a specific version or range.

## Testing Instructions

CI should pass. This shouldn't have any effect on the actual test runs. Everything the API relied on (why it started using `master`) already exists on the latest version of pook (1.4.3)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (`./ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`./ov just catalog/generate-docs media-props`
      for the catalog or `./ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by krysal** [comment]
It looks like tests are failing, so I'll put this in draft mode in the meantime.

**Review by krysal — APPROVED** [review]
LGTM

**Review by dhruvkb — APPROVED** [review]
I don't want to block this PR but I think now `git` is no longer necessary in the API `Dockerfile`. Afaik it was only present so that we could fetch `pook` from the GitHub repo.

**Comment by sarayourfriend** [comment]
Oh, that's a good point, @dhruvkb, thanks for pointing it out. I'll try removing it and if it works without issue I'll go ahead and include that here, otherwise I'll open an issue to investigate further.

**Pull request merged**
