### PR TITLE
Update VBackToSearchResultsLink size to "small"

### LINKED ISSUE #2657: Update "Back to results" and "Report this content" buttons
## Description

As part of the design ideas approved for #377 and #410 projects, "Back to results" and "Report this content" buttons need to update their style to catch the last changes.

### Back to results

Since the show/hide button (#2462 #2463) is `size: small`, "Back to results" needs to reflect the same size. The area where both buttons are placed also changes to match the spacing in all breakpoints.

* "Back to results" button, in all breakpoints
   * Style: Transparent, icon left
   * Size: Small
   * Color: Gray
* Buttons area
   * in `xs, sm`: left, right and bottom padding of `16px (4)`
   * in `md` and beyond: left and right padding of `32px (8)` and padding bottom of `16px (4)`

| `xs`, `sm` | `md` and beyond |
|:---|:---|
|Back to results area in XS breakpoint with frontend notes|Back to results area in XL breakpoint with frontend notes|

### Report content

Designs for #410 displays all buttons in `size: small`. Because of that, this button needs to have the following.

* "Report" button, in all breakpoints
   * Style: Transparent, icon right
   * Size: Small
   * Color: Gray

| `xs`, `sm` | `md` and beyond |
|:---|:---|
| Report button in XS breakpoint with frontend notes | Report button in XL breakpoint with frontend notes |

## Design

Mockups for both changes can be found in #410's [design file](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?node-id=22%3A13656&mode=dev), in their respective area.

## Additional context
Projects related:
* #410 
* #377

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #2657 by @fcoveram 

## Description

This small PR finishes the work in #2696 by changing the size of the VBackToSearchResultsLink size to "small".

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
The change is "small" 😉 

I wonder why the buttons change the size, but also the color of the text in the snapshots.

**Comment by zackkrida** [comment]
It's so weird @obulat. I suspect the old snapshots are wrong somehow. I want to try regenerating them on `main` and see if it produces updated snapshots

**Comment by obulat** [comment]
> It's so weird @obulat. I suspect the old snapshots are wrong somehow. I want to try regenerating them on `main` and see if it produces updated snapshots

I found the reason, we have a `threshold` set higher than 0, so the changes weren't picked up previously.

https://github.com/WordPress/openverse/blob/cb4c934b75be19e573dbac4de4163d9587f62187/frontend/test/playwright/visual-regression/pages/pages-single-result.spec.ts#L32

**Review by fcoveram — APPROVED** [review]
It looks correct 🚀

**Pull request merged**
