### PR TITLE
Update logo nav component in header

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #476 by @fcoveram 

## Description

This PR updates the `VHomeLink` component and the `VLogoButton` component to match the Figma mockups. It cleans up the components from unused props and adds the Storybook stories.

This PR is necessary for replacing the svg dependencies in #2135, which, in turn, is required for Nuxt 3 migration. This is the reason for "high" priority label.

Because this PR changes the spacing of the header logo, there are a lot of snapshot changes.

## Testing Instructions

Check the home links in the internal header (the one with the page links, as on the homepage, content pages such as "about" page and the single result pages). The logo should be 18px high, as in the mockups, and the link itself should be 48px high. On hover on white pages, the background becomes yellow. When focused, it should have a pink focus ring.
A special case is a pages modal on mobile width screen. You can open it if you open the site on a narrow screen and click on the "hamburger" menu button. The modal background is black, so the logo becomes white. The focus ring is yellow instead of pink.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
The logo in `frontend/test/playwright/visual-regression/components/filters.spec.ts-snapshots/filters-modal-filters-selected-ltr-png-xs-linux.png` seems to be animating. Can we pause the animation for VRT, I suspect it will cause flakiness otherwise?

**Comment by obulat** [comment]
> The logo in `frontend/test/playwright/visual-regression/components/filters.spec.ts-snapshots/filters-modal-filters-selected-ltr-png-xs-linux.png` seems to be animating. Can we pause the animation for VRT, I suspect it will cause flakiness otherwise?

That was a locally-generated snapshot that I've updated later. I think we don't need to pause animation, but if the tests do fail again, I'll investigate if we need to adjust the wait. I've replaced the snapshot with a correct one.

**Review by AetherUnbound — APPROVED** [review]
Thanks for the great testing instructions, I was able to confirm each of the cases when running locally!

**Comment by fcoveram** [comment]
> is this discrepancy present in Figma? Does it matter to fix this?

As in the [example shared](https://share.cleanshot.com/TSbFf3kz), it's not present in Figma. If you go to the [Logo nav](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=3835-11055&t=uPA9AZDYaxI7i3Zj-4) component in the Design Library, you will see the following

Screenshot of Logo nav component with notes

Row 1 (size: small) is the logo for the content header in small breakpoints when it's part of the search bar. Row 2 (size: medium) is for the content header in bigger breakpoints. And Row 3 (size: large) is for the internal header in all breakpoints.

Row 2 and 3 share the same size for the symbol, but the latter adds the word "openverse" and has a 16px padding on left and right sides.

Medium and Large versions of Logo nav with spacing guides

---

So going back to your questions from the video:
* **Is this discrepancy present in Figma?** The symbol size discrepancy is wrong. The only difference is the padding in row 3 (size: large)
* **Does it matter to fix this?** It does. Especially in [header content](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=3835-11019&t=uPA9AZDYaxI7i3Zj-4) where logo looks bigger than mockups in all breakpoints. See the image below where I compared both headers in their two main variants.

Screenshot of big and small headers in small and big breakpoints

**Review by fcoveram — APPROVED** [review]
It looks perfect ✨ 🚀 

Since this PR addresses changes in [Header internal](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=3835-11021&t=uPA9AZDYaxI7i3Zj-4), the component specs described [here](https://github.com/WordPress/openverse/pull/2136#issuecomment-1560603958) can be tackled in a different PR.

**Pull request merged**
