### PR TITLE
Add APPLY_FILTER analytics event

### LINKED ISSUE #1070: Analytics event: `APPLY_FILTER`
## Description

The goal is to 

- add the type for event `APPLY_FILTER` to the `Events` type.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/types/analytics.ts#L12

- fire this event from the appropriate location in the codebase using the `useAnalytics` composable.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/composables/use-analytics.ts#L11

## Reference

https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/rfcs/analytics/20221006-implementation_plan_frontend.md?plain=1#L170

## Additional information

- [RFC](https://docs.openverse.org/projects/proposals/analytics/20221006-implementation_plan_frontend.html#events)
- [Example usage in `VHomeGallery.vue`](https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/components/VHomeGallery/VHomeGallery.vue#L128-L134)

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1070 by @dhruvkb

## Description

This PR adds `APPLY_FILTER` event sent when the user selects a filter.
We might want to debounce it, I'm not sure if I should add it here?

Some unrelated changes were also added to clean up the unused ref, and use `storeToRefs` pinia helper to reduce the number of computeds used in the file.

## Testing Instructions

Try clicking on the filters (both in the modal on mobile screen, and the sidebar on the desktop). You should see the event logged in the console, and tracked in Plausible at 0.0.0.0:50288 (if you run `just frontend/up` and `just frontend/init` as described in https://docs.openverse.org/frontend/guides/analytics.html).

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — COMMENTED** [review]
If we want to debounce this it should be added here, otherwise there will be a time span where the event happens _far more often_ than otherwise, making it harder to understand the rate of the event being sent per session.

However, if we debounced it, what would we send? In debouncing, would we still send individual events per filter value changed? In that case, don't bother debouncing. We only debounce the filter changes being sent to search to prevent unnecessary search requests. If we debounced and combine all the updated filters into a single event, that might be worth it, but would slightly change the way this event would be queried. It would probably warrant a slightly different API to make it easier to tell both what filters are applied and how often a particular filter is applied then unapplied (which might imply the filter isn't as useful as others).

**Comment by zackkrida** [comment]
Olga and I chatted a bit yesterday and we concluded we should try without debouncing these. The only reason to debounce would be perceived performance for the user or performance of the `/api/event` endpoint and we don't suspect either of those will be an issue here.

**Review by zackkrida — CHANGES_REQUESTED** [review]
This works perfectly. However, I think we're missing a property for if the filter is being enabled or disabled in the payload. This was the original intention of the "value" property, but the way it's implemented here makes sense to me so I think we just need an additional property.

**Review by dhruvkb — APPROVED** [review]
LGTM! Works well.

**Review by zackkrida — APPROVED** [review]

**Pull request merged**
