### PR TITLE
Update the VFilterButton to use the new variants

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #1020 by @obulat

## Description

This PR uses the new variants for the VFilterButton. This standardizes the border behavior (no dark ring in the focus ring, no transitions for border color).

The Storybook tests are also updated: better order, added `focused` state test, and the hot-fix for focus-ring (wait) is removed.

~~The `xl` and `2xl` snapshots are updated because now the button has no border, so the width for larger buttons becomes 2px more.~~ The buttons were updated to always have a border, so no snapshot changes were necessary.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
@obulat is this one ready for review? Just want to make sure; saw some new commits.

**Comment by obulat** [comment]
> @obulat is this one ready for review? Just want to make sure; saw some new commits. 

Yes, @zackkrida, it's ready for review. The latest change was to set the hover color to dark-charcoal-90, not 80, after @panchovm  confirmed in Figma that the correct value is 90

**Review by zackkrida — APPROVED** [review]
LGTM.

**Comment by panchovm** [comment]
Yes! Confirming what @obulat said

**Comment by obulat** [comment]
@panchovm, just a note about the `bordered-white` variant that is used for the Filters button when it's not pressed. Normally, it shows that it's hovered by showing the gray button. However, if it's focused, we do not show the border even if it's hovered, so when the button is focused, there's no indication of hover. I don't think it's a problem because it is an edge-case, and we _do_ show the focus state which is required for accessibility.

**Comment by panchovm** [comment]
You are right @obulat. We can leave it as it is.

I checked the same situation in Gutenberg and the style doesn't change. We can review it in the future if we notice some problems.

**Review by panchovm — APPROVED** [review]
It looks great ✨ 🚀

**Pull request merged**
