### PR TITLE
Swap from flake8 to ruff

### PR DESCRIPTION
**Pull request by glowatsk**
## Fixes
Partially addresses https://github.com/WordPress/openverse/issues/787

## Description
Move the current configuration to the ruff linter. pre-commit will use ruff now for linting, extra configuration can be added as needed. I opted for `.ruff.yaml` as the dotfile is usually handled better with editors. This can be changed as needed.

E203 is made obsolete by black.
W503 is made obsolete by black.
Line length is by default 88.

https://beta.ruff.rs/docs/rules/

I do not see any documentation involving flake8.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Awesome, @glowatsk! It looks like in the CI the `.ruff.toml` file failed to parse:

```shell
error: Failed to parse `/home/runner/work/openverse/openverse/.ruff.toml`: TOML parse error at line 7, column 15
  |
7 | line-length = 88
  |               ^^
invalid type: integer `88`, expected a sequence
```

details of the CI run here: https://github.com/WordPress/openverse/actions/runs/4471769545/jobs/7857074527?pr=963

**Comment by glowatsk** [comment]
> Awesome, @glowatsk! It looks like in the CI the `.ruff.toml` file failed to parse:
> 
> ```shell
> error: Failed to parse `/home/runner/work/openverse/openverse/.ruff.toml`: TOML parse error at line 7, column 15
>   |
> 7 | line-length = 88
>   |               ^^
> invalid type: integer `88`, expected a sequence
> ```
> 
> details of the CI run here: https://github.com/WordPress/openverse/actions/runs/4471769545/jobs/7857074527?pr=963

Thanks, looks like this is default and is no longer needed. 
https://beta.ruff.rs/docs/settings/#line-length

**Comment by glowatsk** [comment]
@zackkrida think this is good to go now.

**Review by sarayourfriend — APPROVED** [review]
Fantastic, thanks for the contribution @glowatsk.

**Review by zackkrida — APPROVED** [review]
Sweet, nice work @glowatsk

**Comment by glowatsk** [comment]
> CI has to pass before we merge this. Because if not, every other PR will fail CI.

Should just need the appropriate stack label.

**Comment by dhruvkb** [comment]
Ah, sorry, my bad. I misread the lint check as failing. The 'CI + CD / Add stack label (pull_request)' check fails on PRs from forks, so we can merge it despite the failing check.

**Comment by AetherUnbound** [comment]
Thanks so much for this contribution @glowatsk!! What an awesome improvement to have come from the PyCascades sprints 😄 🥳 🏎️

**Comment by AetherUnbound** [comment]
Oh also, does #787 still need to remain open, or can it be closed?

**Pull request merged**
