### PR TITLE
Extract `use-audio-snackbar` component

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #2694 by @obulat

## Description

This PR extracts `use-audio-snackbar` composable to make reviewing #2695 easier. This composable is used on the All media search page and Audio search page, and will be used on Additional search views (by tag, source and creator).

## Testing Instructions

The snackbar should appear when you focus an audio on the search view, and it should disappear when you "interact" with it by pressing "spacebar" or clicking on the play button.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
👍

**Review by krysal — COMMENTED** [review]
It's quite nice to see the separation of code that composables provide 💯

However I don't see the snackbar hiding, not even in `main` actually 😅 Is it just me? I tested in Firefox and Chrome. Maybe adding some tests could help?

**Comment by obulat** [comment]
> It's quite nice to see the separation of code that composables provide 💯
> 
> However I don't see the snackbar hiding, not even in `main` actually 😅 Is it just me? I tested in Firefox and Chrome. Maybe adding some tests could help?

Great catch, Krystle. It was working on the All content view (where I was testing), and not on the Audio view. I've added hiding now.

**Review by krysal — APPROVED** [review]
Awesome! Works great.

**Pull request merged**
