### PR TITLE
Add 10s timeout to check_image_type head requests

### LINKED ISSUE #2419: Add timeout to image type `head` requests in `photon.check_image_type`
## Description

`photon.check_image_type` runs in the same request lifecycle as the already long-running thumbnails endpoint. Without a timeout, this head request, for slower providers, could be the source of the thumbnail endpoint causing workers to timeout.

## Reproduction

As of right now there is no way to reproduce this behaviour, as far as I know. cc @zackkrida who originally identified the need for the timeout.

## Fix

Add `timeout=10` to the call to `request.head`. This is long, but gunicorn times workers out after 30 seconds. Combined with the timeout in `photon.get` at 15 seconds, this leaves 5 seconds for our own Django request handling. That's a lot of time, but I'm not sure how close we can get to the 30 seconds max (which we do not want to increase for our entire API) when we'd rather the request just terminate if it's taking that long anyway.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #2419 by @sarayourfriend  

## Description

Adds a 10s timeout to head requests in `check_image_type`. Not sure we need a test for this but I'm happy to add one based on suggestions. Seems like we'd just be testing the internals of the request library.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
For testing, I tried adding a callback to a `pook.get` request to make the call timeout. However, the test waited 20 seconds and passed anyway 😅 which makes me think I'm not understanding how pook works. Perhaps it's mocking the `requests.head` call itself in which case the timeout won't occur at all since none of the requests internals are being called.

```diff
diff --git a/api/api/utils/photon.py b/api/api/utils/photon.py
index 1e161736c..bfd33627c 100644
--- a/api/api/utils/photon.py
+++ b/api/api/utils/photon.py
@@ -31,6 +31,8 @@ HEADERS = {
     )
 }
 
+HEAD_REQUEST_TIMEOUT = 10
+
 
 def _get_file_extension_from_url(image_url: str) -> str:
     """Return the image extension if present in the URL."""
@@ -63,7 +65,7 @@ def check_image_type(image_url: str, media_obj) -> None:
     if not ext:
         # If the extension is still not present, try getting it from the content type
         try:
-            response = requests.head(image_url, timeout=10)
+            response = requests.head(image_url, timeout=HEAD_REQUEST_TIMEOUT)
             response.raise_for_status()
         except Exception as exc:
             sentry_sdk.capture_exception(exc)
diff --git a/api/test/unit/utils/test_photon.py b/api/test/unit/utils/test_photon.py
index 7ea41252b..273d84ff5 100644
--- a/api/test/unit/utils/test_photon.py
+++ b/api/test/unit/utils/test_photon.py
@@ -1,3 +1,4 @@
+import time
 from test.factory.models.image import ImageFactory
 from unittest import mock
 from unittest.mock import MagicMock
@@ -12,6 +13,7 @@ import requests
 
 from api.utils.photon import (
     HEADERS,
+    HEAD_REQUEST_TIMEOUT,
     UpstreamThumbnailException,
     _get_file_extension_from_url,
     check_image_type,
@@ -91,6 +93,31 @@ def test_get_successful_with_auth_key_default_args(mock_image_data, auth_key):
     assert mock_get.matched
 
 
+@pook.on
+def test_get_successful_no_auth_key_times_out(mock_image_data):
+    mock_get: pook.Mock = (
+        pook.get(PHOTON_URL_FOR_TEST_IMAGE)
+        .params(
+            {
+                "w": settings.THUMBNAIL_WIDTH_PX,
+                "quality": settings.THUMBNAIL_QUALITY,
+            }
+        )
+        .header("User-Agent", UA_HEADER)
+        .header("Accept", "image/*")
+        .callback(lambda *args: time.sleep(HEAD_REQUEST_TIMEOUT * 2))
+        .reply(200)
+        .body(MOCK_BODY)
+        .mock
+    )
+
+    res = photon_get(TEST_IMAGE_URL)
+
+    assert res.content == MOCK_BODY.encode()
+    assert res.status_code == 200
+    assert mock_get.matched
+
+
 @pook.on
 def test_get_successful_no_auth_key_not_compressed(mock_image_data):
     mock_get: pook.Mock = (
```

**Review by AetherUnbound — APPROVED** [review]
Looks good! We could add a test which asserts that `request.head` is called with `timeout=10`, but that would require a different mocking procedure than the rest of the tests use so I think this is okay as-is 🙂

**Comment by zackkrida** [comment]
Perhaps it's mocking the requests.head call itself in which case the timeout won't occur at all since none of the requests internals are being called.

@AetherUnbound yep, looks that's exactly what pook does. Good to know. Thanks for looking at this!

**Review by stacimc — APPROVED** [review]

**Review by sarayourfriend — APPROVED** [review]
I think it's fair to test that `timeout=10` is passed, primarily as a way to encode that it is there for a specific reason, though the git history will already bear that out (if anyone looks at that).

**Pull request merged**
