### PR TITLE
Make additional search types flag clearer and add external sources for additional types

### LINKED ISSUE #2138: "external_sources" feature flag needs to be improved
## Problem

"external_sources" flag name is not very clear, and the External sources popover does not use additional types when this flag is enabled.

## Description

I propose renaming the flag to "additional_content_types" as it enables the display of additional types in the content switcher. When this flag is enabled, you should be able to select the external sources for the page's type (even video and model_3d). Now, however, those external sources are never displayed.

## Additional context

I discovered the problem that you cannot view the external sources for additional content types when trying to remove the `build-url` library that's been deprecated. It is used to create the external source URLs with query parameters.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2138 by @obulat

## Description

This PR renames the "external_sources" feature flag to "additional_search_types" as the flag enables showing additional search types in the content switcher.
It also enables showing the additional search type external sources if the flag is enabled, instead of falling back to image on "all_content", "video" and "model_3d" pages.

## Testing Instructions

Go to "/preferences" and turn on the "additional_search_types" flag.
Then select additional search types (video, 3d models) in the content switchers (in the header, in the search bar on the homepage). When you are on a video page, you should see the video source links in the external sources popover, not the image sources.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
Looks good and makes sense! Just for my own understanding, we don't need to do anything with regards to  backwards compatibility because this is a per-session preference (and thus resets when opening a new tab/browser)?

Also, I noticed some odd behavior when playing around with this. It's unrelated to these changes so I don't think it's blocking but I wanted to see if this is expected: When the sources list is clicked, you can't click _anywhere_ else on the page to make the sources list go away, you have to hit the "X" on the sources list modal. Even clicking the "Sources" drop down doesn't work, it has to be the "X". What confused me more here is that I could move my mouse and hovering over the search bar made it change color! Which made me think I could interact with it. Here's a video (might only be viewable in Chrome):


https://github.com/WordPress/openverse/assets/10214785/4755b724-2587-4cdf-9019-1cbcfd6ea2d5

Is that expected?

**Comment by sarayourfriend** [comment]
> Is that expected?

It is definitely not the intended behaviour and is reproducible on staging (https://staging.openverse.org/search/video?q=food) so you're right that it isn't an issue with this PR. Can you open an issue for it? (You can convert the video to ogg, btw, for cross-browser support.)

**Comment by sarayourfriend** [comment]
> we don't need to do anything with regards to backwards compatibility because this is a per-session preference (and thus resets when opening a new tab/browser)?

We don't need to worry about this because the setting isn't available in production: https://openverse.org/preferences

**Review by sarayourfriend — APPROVED** [review]
LGTM, tested locally and works well.

**Comment by obulat** [comment]
> Also, I noticed some odd behavior when playing around with this. It's unrelated to these changes so I don't think it's blocking but I wanted to see if this is expected: When the sources list is clicked, you can't click _anywhere_ else on the page to make the sources list go away, you have to hit the "X" on the sources list modal. Even clicking the "Sources" drop down doesn't work, it has to be the "X". What confused me more here is that I could move my mouse and hovering over the search bar made it change color! Which made me think I could interact with it. Here's a video (might only be viewable in Chrome):

This is not an expected behavior, thank you for reporting! It is probably caused by recent changes that added role `dialog` to popovers. I'll open an issue if there isn't one already.

**Pull request merged**
