### PR TITLE
Upgrade ESLint and Prettier packages in monorepo root

### LINKED ISSUE #2571: Enable `playwright/expect-expect` once the plugin supports extending the assert function names
## Problem

`eslint-plugin-playwright` does not have the ability to modify the list of accepted assert function names: https://github.com/playwright-community/eslint-plugin-playwright/issues/154

Because we make heavy use of reusable assertion functions, especially in visual regression tests, this particular rule is temporarily disabled (once #2312 is resolved).

## Description

After the issue in the plugin is resolved, upgrade the plugin and enable the expect-expect rule.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #2571 by @sarayourfriend 

## Description

This PR does the following:

1. Upgrade all ESLint and prettier root packages to their latest versions. I used `pnpm up --latest '*eslint*'` and `pnpm up --latest '*prettier*'` to make this easy. Originally I was going to just update the eslint plugins but it made sense to go ahead and update prettier as well. I did not update the TypeScript related ones because it's a major version jump for TS and IIRC there are some lingering issues we need to address. I'll investigate and open issues if necessary.
2. Re-enable and address the `playwright/expect-expect` warnings.
3. Fix one TS issue that required a one-line change to fix (opted for that rather than to open an issue). Filed #2907 for another TS issue.
4. Disable a new vue-a11y rule and opened an issue to investigate whether any of those need to be re-enabled. The disabled rule as a reference to the issue on each disable comment. #2906
5. Update prettier configuration to address https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/208.

## Testing Instructions

Checkout the branch, run `pnpm install` to get the new dependency versions installed, and add some code that would cause ESLint to fail, confirm that it does. Read through the new comments etc and confirm they are accurate.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
It looks like the branch currently has conflicts @sarayourfriend 😮 

Also, I'm getting the following when I run `eslint` locally, I presume this is unexpected?

<details> <summary>Error output</summary>

```
eslint...................................................................Failed
- hook id: eslint
- exit code: 1

 WARN  Unsupported engine: wanted: {"node":">= 18.0.0 <19"} (current: {"node":"v16.19.0","pnpm":"7.17.1"})

> openverse@0.0.0 preeslint /home/madison/git-a8c/openverse
> pnpm --filter eslint-plugin run build

.                                        |  WARN  Unsupported engine: wanted: {"node":">= 18.0.0 <19"} (current: {"node":"v16.19.0","pnpm":"7.17.1"})

> @openverse/eslint-plugin@0.0.0 build /home/madison/git-a8c/openverse/packages/eslint-plugin
> babel --extensions '.ts' --out-dir dist ./src

Successfully compiled 7 files with Babel (615ms).

> openverse@0.0.0 eslint /home/madison/git-a8c/openverse
> eslint --ext .js,.ts,.vue,.json,.json5 --ignore-path .gitignore --ignore-path .eslintignore --max-warnings=0 frontend automations/js packages .pnpmfile.cjs .eslintrc.js tsconfig.json prettier.config.js "--fix"


/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/all-results-analytics.spec.ts
  16:3  warning  Test has no assertions  playwright/expect-expect
  34:3  warning  Test has no assertions  playwright/expect-expect
  53:3  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/audio-detail.spec.ts
  40:3  warning  Test has no assertions  playwright/expect-expect
  60:3  warning  Test has no assertions  playwright/expect-expect
  76:3  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/external-sources.spec.ts
  10:1  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/homepage.spec.ts
  39:1  warning  Test has no assertions  playwright/expect-expect
  50:1  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/image-detail.spec.ts
  57:1  warning  Test has no assertions  playwright/expect-expect
  62:1  warning  Test has no assertions  playwright/expect-expect
  68:3  warning  Test has no assertions  playwright/expect-expect
  89:3  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/load-more.spec.ts
  168:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/report-media.spec.ts
  103:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/e2e/search-types.spec.ts
  107:7  warning  Test has no assertions  playwright/expect-expect
  115:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/components/content-report-form.spec.ts
  21:3  warning  Test has no assertions  playwright/expect-expect
  35:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/components/external-sources-section.spec.ts
  18:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/components/filters.spec.ts
  29:7  warning  Test has no assertions  playwright/expect-expect
  38:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/components/global-audio-player.spec.ts
  14:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/components/header.spec.ts
  29:7  warning  Test has no assertions  playwright/expect-expect
  45:9  warning  Test has no assertions  playwright/expect-expect
  51:9  warning  Test has no assertions  playwright/expect-expect
  58:9  warning  Test has no assertions  playwright/expect-expect
  67:9  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/pages/errors.spec.ts
  23:5  warning  Test has no assertions  playwright/expect-expect
  33:5  warning  Test has no assertions  playwright/expect-expect
  67:5  warning  Test has no assertions  playwright/expect-expect
  83:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/pages/homepage.spec.ts
  39:7  warning  Test has no assertions  playwright/expect-expect
  46:9  warning  Test has no assertions  playwright/expect-expect
  53:9  warning  Test has no assertions  playwright/expect-expect
  62:9  warning  Test has no assertions  playwright/expect-expect
  68:9  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/pages/no-results.spec.ts
  19:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/pages/pages-single-result.spec.ts
  27:7  warning  Test has no assertions  playwright/expect-expect
  47:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/pages/pages.spec.ts
  36:9  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/playwright/visual-regression/pages/search-with-banners.spec.ts
  14:3  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/custom-button-components.spec.ts
  15:5  warning  Test has no assertions  playwright/expect-expect
  20:5  warning  Test has no assertions  playwright/expect-expect
  26:5  warning  Test has no assertions  playwright/expect-expect
  32:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/focus.spec.ts
  23:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-filter-button.spec.ts
  17:7  warning  Test has no assertions  playwright/expect-expect
  25:7  warning  Test has no assertions  playwright/expect-expect
  36:7  warning  Test has no assertions  playwright/expect-expect
  49:7  warning  Test has no assertions  playwright/expect-expect
  59:7  warning  Test has no assertions  playwright/expect-expect
  70:7  warning  Test has no assertions  playwright/expect-expect
  82:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-footer.spec.ts
  31:9  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-header-internal.spec.ts
  17:7  warning  Test has no assertions  playwright/expect-expect
  27:7  warning  Test has no assertions  playwright/expect-expect
  35:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-language-select.spec.ts
  10:3  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-media-license.spec.ts
  33:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-media-reuse.spec.ts
  29:9  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-notitication-banner.spec.ts
  25:9  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-safety-wall.spec.ts
  16:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-search-type-button.spec.ts
  20:7  warning  Test has no assertions  playwright/expect-expect
  28:7  warning  Test has no assertions  playwright/expect-expect
  37:7  warning  Test has no assertions  playwright/expect-expect
  45:7  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-search-types.spec.ts
  17:5  warning  Test has no assertions  playwright/expect-expect
  21:5  warning  Test has no assertions  playwright/expect-expect
  26:5  warning  Test has no assertions  playwright/expect-expect
  37:5  warning  Test has no assertions  playwright/expect-expect
  41:5  warning  Test has no assertions  playwright/expect-expect
  46:5  warning  Test has no assertions  playwright/expect-expect

/home/madison/git-a8c/openverse/frontend/test/storybook/visual-regression/v-select-field.spec.ts
  12:3  warning  Test has no assertions  playwright/expect-expect
  17:3  warning  Test has no assertions  playwright/expect-expect
  22:3  warning  Test has no assertions  playwright/expect-expect

✖ 76 problems (0 errors, 76 warnings)

ESLint found too many warnings (maximum: 0).
 ELIFECYCLE  Command failed with exit code 1.
```

</details>

**Comment by sarayourfriend** [comment]
@AetherUnbound Have you run `pnpm install`? I'll update the testing instructions and resolve the conflict.s

**Comment by sarayourfriend** [comment]
Also: you should update your node locally. [Volta](https://docs.volta.sh/guide/getting-started) is a great tool for managing node versions if you still need the older version, for some reason. Some of our dependencies will probably stop working on EOL'd node versions at some point.

**Review by AetherUnbound — APPROVED** [review]
LGTM and no eslint errors locally! I'm not sure what an appropriate change would be to make a new error occur but I removed one of the warning ignorations and saw an error was raised 🙂

**Pull request merged**
