### PR TITLE
Use trigger_and_wait for alias point step in create filtered index DAG

### LINKED ISSUE #2619: Add a wait sensor for the create filtered index DAG's trigger alias point step
## Description

It is possible, during the create filtered index DAG, for the point alias step to take up to 12 hours due to the cluster health check which occurs within it:

https://github.com/WordPress/openverse/blob/a11969e59140c7d23d5eadcedabeb8f21803ff08/ingestion_server/ingestion_server/indexer.py#L358-L362

The trigger delete step of the DAG is issued right after the point alias without waiting for the latter to complete. We will need to add a sensor for the task that is created during the point alias step prior to attempting a delete, otherwise the delete will fail because the alias point of the index to be deleted is not complete. 

## Additional context

We received this error message:

```
023-07-11 07:15:31,968 ERROR indexer.py:448 - Indeximage-3582ac6299524df192ce652a13ef37d7is associated with aliases ['image-filtered'], cannot delete. Delete aliases first.
```

Following that, we received the message:

```
2023-07-11 09:48:13,655 INFO indexer.py:388 - `image`: Migrated alias `image-filtered` from index `image-3582ac6299524df192ce652a13ef37d7` to index `image-273c6f23b5b144ad8f1b576f5e3a14d7-filtered` | _Next: delete old index_
```

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #2619 by @AetherUnbound

## Description

This PR uses the `trigger_and_wait_for_task` method for the point alias step of the `create_filtered_<media-type>_index` DAG. This ensures that the point alias step completes before the deletion is attempted.

## Testing Instructions

1. `just down -v`
1. `just api/init`
1. `just i && just c`
1. Enable the `create_filtered_image_index` DAG, then the `image_data_refresh` DAG
1. Observe that the wait step completes before deletion is attempted.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM!

Is there anywhere else this kind of fix might need to be applied, if not necessarily in this PR/issue then for another issue?

**Review by obulat — APPROVED** [review]
LGTM!
Do we have any other async tasks like this in other DAGs that might need a similar change? Should we conduct an audit for it?

**Comment by AetherUnbound** [comment]
Great questions! I will do a quick audit of the other tasks and put up another PR if I find any other necessary cases 😄 For now I'll merge this so we can kick off another filtered run 🚀

**Comment by AetherUnbound** [comment]
I've checked the other ES related tasks and the only step that _could_ use a wait is the `trigger_delete` ones, but in all cases we don't actually need to wait for the delete for subsequent steps to complete successfully. This should be the only necessary case!

**Pull request merged**
