### PR TITLE
Add the UI toggle for changing theme

### LINKED ISSUE #4155: Site theme switcher (dark mode toggle)
Designs for Dark mode project (#3592)

## Description
Given that users need to set the site theme from any part of the site, the most affordable area is the site footer. It already has the language selector, that behaves equally, and adding the action there is the more logical solution.

## Mockups
For the current arrangement of pages in both footer content and internal, the following version is the one that convince me most.

New footer design in XS and LG breakpoints

The switcher is placed next to the language selector and it behaves equally. The options displayed are Light, Dark, and System in the OS/browser popover.

### Footer 
Content footer is on top and internal footer at the bottom.

Content and internal footers

## Middle- and long-term idea
With the [design explored](https://github.com/WordPress/openverse/issues/3564#issuecomment-1916380597) (#3564) to make the internal pages area more simple, I would like to bring again the opportunity we have to make the footer even more simple by putting the general/site settings in a unique config menu.

Designs for the future footer

Site settings menu in XS and LG breakpoints

The benefits of this idea is twofold:
* It puts Openverse in a better position with regards to privacy by making the toggle more visible
* It's the first step towards placing settings in a single menu once user profile-related actions are needed in future features.

I personally would like to consider the implementation of this middle/long-term component. What do you think?

### LINKED ISSUE #4309: Add UI toggle for dark mode
> This issue is part of the Dark Mode project: #3592. Please see the [implementation plan](https://docs.openverse.org/projects/proposals/dark_mode/20240325-implementation_plan_dark_mode.html) for additional detail and context. 

> [!IMPORTANT]  
> This issue is blocked by #4306. This issue is also blocked from merge by #4308, which will add the `setColorMode` method (example name) called by this UI component to actually store the chosen value. This PR can be started prior to that one and/or nearly completed, but drafted, until the method exists.

Behind the feature flag added in #4306, add the new user interface element which toggles dark mode, designed in #4155. Supports choosing between “dark”, “light”, and “system” modes, with “system” as the default.

Also add a `TOGGLE_COLOR_SCHEME` analytics event, with a playload including the color mode preference chosen by the user. We will use this to assess usage of the toggle and dark, mode, generally. 

The actual functionality to store and use this value to change the color scheme is added in #4308. This issue purely adds the presentational component to our user interface and connects it to the method for setting the color scheme.

### LINKED ISSUE #4355: Remove uses of `openverse-storage` bucket
## Description

We use the `openverse-catalog` bucket for most of our catalog interactions, but locally we have the default bucket defined as `openverse-storage`. #4163 took some steps towards making `openverse-catalog` the default for catalog-related files in the ingestion server, and included adding `openverse-catalog` as a bucket which is created when starting the stack locally:

https://github.com/WordPress/openverse/blob/43d4d09cb3e9edb66f087e438f6714a0de514bd8/docker/minio/env.template#L8

Since `openverse-storage` and `openverse-catalog` serve the same functional purpose locally, and we only have one bucket that we use in production, we should change references from `openverse-storage` to `openverse-catalog` locally and remove the creation of the `openverse-storage` bucket.

This can be done by changing the catalog's bucket template to use `openverse-catalog` here:

https://github.com/WordPress/openverse/blob/12e7c87969077becfe997d493cf9065505441146/catalog/env.template#L106

And also removing the creation of the `openverse-storage` bucket here:

https://github.com/WordPress/openverse/blob/12e7c87969077becfe997d493cf9065505441146/catalog/env.template#L106

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #4309 by @zackkrida 
Fixes #4155 by @fcoveram 

## Description

This PR
- adds icon assets and i18n strings for theme switching
- updates the `VSelectField` component to hide the active choice
- creates the UI component for switching between color modes
  - wires the component to functionality implemented in #4810
  - adds the UI component to the footer based on whether the "dark_mode_ui_toggle" feature flag is enabled
- deletes the "force_dark_mode" feature flag as it is redundant
  - deletes usage and tests for the feature flag

## Testing Instructions

0. Check out the PR and run the dev server.
1. Enable the "dark_mode_ui_toggle" feature flag. You should see the theme selector in the footer.
2. Switch between light and dark theme. The site should update to show the your chosen color theme (regardless of the system theme). The icon in the footer should also update.
3. Switch between the OS light and dark theme. The text for the "System" choice in the theme selector should update.
4. Switch to the "System" theme.
5. Switch between the OS light and dark theme. The text for the "System" choice in the theme selector should update. The actual dark/light theme should also update. The icon in the footer should also update.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
This PR is drafted till #4810 is merged and labelled as "⛔️ status: blocked" (to prevent accidentally merging it). Once that is merged, it will be rebased and undrafted. Feel free to review in the meantime, I do not anticipate UI/functionality changes.

**Review by zackkrida — DISMISSED** [review]
Lovely! There are a few small issues I'm noticing:

- The "system" mode icon doesn't reflect the user's preference on SSR, it is always light.
- There's an icon sizing/spacing issue:
image
- For the first issue, perhaps making the component clientonly would fix it

I really like how you're displaying the parenthetical of what the actual system value is, nice touch!

**Comment by dhruvkb** [comment]
@zackkrida that is so weird, I'm not seeing the select field sizing issue on any major browser! This is Safari, Arc (Chromium) and Firefox:

image

**Comment by zackkrida** [comment]
@dhruvkb it looks like removing `overflow-hidden` from the VSelectField wrapper div fixes the collapsing issue. The problem makes sense to me: a flex child with overflow-hidden and two absolutely-positioned children _would_ collapse, as I understand. 

I'm seeing it in Chrome and Firefox on Fedora. In any case, I think we can safely remove the overflow hiding.

**Review by obulat — CHANGES_REQUESTED** [review]
Nice to be able to change the theme from the UI!

I have 2 blocking requests:
1. The `VThemeSelect` should not detect the user's color scheme. It should only use the value from the UI store, and update it.
`app.vue` (and `error.vue`) as the entrypoints to the application would be the best place for the detection of the user's color scheme. We update the UI store layout properties (breakpoint and width) there.

2. The `select` inside the `VSelectField` component does not set the `outline` style or width on `focus-visible`, but we do set its color. So with the default values, the focus ring has a white outline. Adding a `focus-visible:outline-none` to the `select` element could fix this white ring around the pink one:
Screenshot 2024-09-03 at 9 07 58 AM

**Comment by dhruvkb** [comment]
1. Will implement as soon as possible.
2. I cannot see the white outline. 

Firefox:
Screenshot 2024-09-03 at 12 34 19 PM

Chrome:
Screenshot 2024-09-03 at 12 34 33 PM

**Review by obulat — APPROVED** [review]
The functionality is perfect ✨ It's nice that the composable encapsulates handling of the color mode and we don't have to update the pages.

In dark mode, I can see a ring around the select field focus border in Arc, Chrome and Safari. Firefox is the only browser that displays the focus border correctly. I'm not blocking on this because this is a problem that existed with the language select, and should have a separate issue.

**Pull request merged**
