### PR TITLE
Add the ToS to the navigation bar

### LINKED ISSUE #3564: Add a terms of service page to the frontend
## Description

We presently have terms of service defined for our API here: https://docs.openverse.org/terms_of_service.html

We recently received an external request for information about the terms of service for our frontend. While the question came in the context of scraping our data from the frontend, it would be useful for us to establish a document similar to the one for our API which specify the terms of use we're expecting there as well. Many of the same conditions could apply in the cases where it makes sense to.

## Additional context

Might be related to #2171

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #3564 by @AetherUnbound

## Description

This PR adds a link to the Terms of Service (using the name "Terms") to the navigation bar. This is a stopgap measure while we do a larger reorganization of the navigation menu.

There might be something else I'm missing with this PR, frontend folks - please let me know if that's the case!

## Testing Instructions

I've updated the playwright snapshots. I _think_ I've done everything that's necessary for testing!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
Awesome PR with updated snapshots 🎉
You will also need to update the storybook snapshots that test header and footer in isolation. `just frontend/test:storybook -u` is probably the command that does so.

**Comment by AetherUnbound** [comment]
Thanks @obulat for that tip! I'll add it to the [frontend documentation on testing as well](https://docs.openverse.org/frontend/guides/test.html) (that's what I was following 😄)

**Comment by AetherUnbound** [comment]
I'm...not sure how to proceed now 😅

**Comment by sarayourfriend** [comment]
@AetherUnbound What are you stuck on? The failing Playwright test in CI might be a flaky test failure, in which case [follow this from the comment above](https://docs.openverse.org/general/test.html#flaky-tests).

**Review by obulat — APPROVED** [review]

**Review by dhruvkb — APPROVED** [review]
I can't see any difference in `frontend/test/storybook/visual-regression/v-image-cell.spec.ts-snapshots/v-image-cell-intrinsic-focused-xl-linux.png` but if CI passes then it's okay I guess?

Might I suggest two explorations?

- updating this PR branch with `main`
- dropping that file from the PR and seeing if tests continue to pass

**Comment by AetherUnbound** [comment]
I was able to rebase on main, but re-running storybook locally is adding _even more_ changes that don't seem like they're significant 😕 The fact that CI is passing here on main after a rebase makes me think things are fine, so I'm just going to merge this!

**Pull request merged**
