### PR TITLE
Update pnpm from 7.17.1 to 8.12.1

### LINKED ISSUE #1052: Upgrade to pnpm@8
## Problem

Our frontend JavaScript dependency manager, pnpm, has [released a new major version](https://github.com/pnpm/pnpm/releases/tag/v8.0.0). The old version will be supported for a few months but will not recieve major updates or support.

## Description

We should upgrade to pnpm 8. All we have to do, from the migration guide, is regenerate our lock file:

> Before updating pnpm to v8 in your CI, regenerate your pnpm-lock.yaml. To upgrade your lockfile, run pnpm install and commit the changes. Existing dependencies will not be updated; however, due to configuration changes in pnpm v8, some missing peer dependencies may be added to the lockfile and some packages may get deduplicated.
> You can commit the new lockfile even before upgrading Node.js in the CI, as pnpm v7 already supports the new lockfile format.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes
Fixes #1052 by @zackkrida 

## Description

This PR updates pnpm to v8, per a warning I've been seeing in the console:

```
   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 7.17.1 → 8.12.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.12.1   │
   │     Run "corepack prepare pnpm@8.12.1 --activate" to update.     │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯
```

I was able to run the frontend locally and it seemed okay! Not sure if there's anything else I need to do here :open_mouth:

## Testing Instructions

Run `just f` and make sure the frontend installs dependencies and runs okay (I think? This may also require the corepack command above too)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
`--frozen-lockfile` flag causes errors when building frontend.
Unfortunately, I had to also remove the bundle size workflow because it hard-codes the install script with `--frozen-lockfile`:

https://github.com/preactjs/compressed-size-action/blob/8a15fc9a36a94c8c3f7835af11a4924da7e95c7c/src/index.js#L63

**Review by obulat — APPROVED** [review]
We had opened a PR for updating pnpm, but got the same build errors due to `--offline` and `--frozen-lockfile` flags not working as expected. I hoped that this issue would be fixed, but it's still present, so I think it's best to remove offline installs and update pnpm.

Unfortunately, I had to also remove the bundle size workflow because it hard-codes the install script with --frozen-lockfile:

https://github.com/preactjs/compressed-size-action/blob/8a15fc9a36a94c8c3f7835af11a4924da7e95c7c/src/index.js#L63

I also set the priority to "high" because it's inconvenient to change pnpm versions between this branch and others.

**Comment by AetherUnbound** [comment]
Oh, thank you for taking care of that @obulat!

**Review by dhruvkb — COMMENTED** [review]
If the `install` step is not offline, the `pnpm fetch` step on L34 becomes redundant. Other than that, all checks are passing so I guess this change should be fine 👍.

I don't know how I feel about losing the `bundle_size.yml` workflow, it didn't do much unless we were adding or removing dependencies, which doesn't happen often.

**Review by dhruvkb — APPROVED** [review]
LGTM, removing the `fetch` step makes what's happening in the `Dockerfile` much more clear.

**Pull request merged**
