### PR TITLE
Fix whitespace bug that only affected Chrome

### LINKED ISSUE #503: Remove unused and potentially risky `srText` from VBrand component
## Problem

The VBrand component has a prop called `srText` that a) allows you to change the text the screen reader would read for the Openverse logo and brand mark and b) has documentation that suggests we might one day set the text to empty.

1. When would we ever want to set it to empty? Wouldn't that be an a11y issue?
2. Under what circumstances do we need to be able to change this?

Generally my sense about this is [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). The prop seems risky to me (and the documentation potentially gives bad advice, I'm not sure) and we don't use it anywhere.

Is there a specifically planned usage for this prop @WordPress/openverse-frontend? 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### LINKED ISSUE #2596: Extra White-Space in responsive mode while scrolling
## Description
In Mobile responsive mode, there are extra whitespace after the Footer section while scrolling down. The issue is when we search for an image with a name. After the search result appear we see it.

## Reproduction

Provide detailed steps to reproduce the bug.
1. Go to https://openverse.org
2. Go to Responsive mobile device mode
3. In the search bar, search with a name, (eg: nature)
4. Go down with scrolling,
5. After the footer section, you should see an extra whitespace there.

## Screenshots

nature-Openverse

[Video Link] (https://drive.google.com/file/d/1nN7UdXsYI9kDurTxR_wMQf9Y0VIbjjVs/view?usp=sharing)

## Environment

Tested environment setup information below.

- Device: Mac
- OS: Monterey
- Browser: Chrome

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2596 by @nayanchamp7
Fixes #503 by @sarayourfriend 

## Description

This PR adds static position to the SR-only text employed by `VBrand`. The absolute positioning of the text due to the `sr-only` class was tripping Chrome somehow, leading to whitespace below the page equal in height to the search-results grid's inherent size.

## Testing Instructions

0. Check out the PR and run the dev server.
1. Search for some text.
2. Scroll to the bottom of the page.
3. There should not be any white space.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
really nice discovery

**Review by krysal — APPROVED** [review]
Great!

**Comment by zackkrida** [comment]
I'm going to try and fix the test here and then merge.

**Review by obulat — DISMISSED** [review]
Kudos for finding the reason, @dhruvkb ! I would not have looked for it inside the component :) 

My suggestion is to remove the "srText" span completely, and use an `aria-label` on the wrapping component. This would also fix https://github.com/WordPress/openverse/issues/503

**Comment by zackkrida** [comment]
I have updated this PR to:

- Use an aria-label instead of making the SR text static
- To fix the test to verify the position of the correct scrolling element
- Some simplifications of the VBrand component and the navigation test utilities

I want to merge and deploy this ASAP given the nature of the bug, so I'd appreciate a retroactive review from @dhruvkb, @obulat, @krysal, and/or @AetherUnbound 😄

**Pull request merged**
