### PR TITLE
Fix `add_license_url` DAG for last items

### LINKED ISSUE #4318: Some recently updated images are missing `license_url` in the `meta_data` field
## Description

On 2024-05-08 UTC the `batched_update` DAG was [triggered](https://airflow.openverse.org/dags/batched_update/grid?dag_run_id=manual__2024-05-08T21%3A00%3A20%2B00%3A00)[^1] to fill the `license_url` in the `meta_data` field with its corresponding value for rows `WHERE license = 'by' AND license_version = '2.0'`, and it reported a successful end on 2024-05-09, 17:00:18 UTC **updating 746,571 records**. However, after triggering a run of the `add_license_url` DAG on 2024-05-10, it [reported](https://airflow.openverse.org/dags/add_license_url/grid?dag_run_id=manual__2024-05-10T14%3A42%3A33%2B00%3A00&tab=logs&task_id=get_license_groups) the same row number missing said license, which indicates that some workflows may not be filling this field or are overwriting it.

**Flicker** is confirmed to be on the set of rows missing this value.

```sql
SELECT source, provider, created_on, updated_on FROM image 
 WHERE license = 'by' AND license_version = '2.0' AND meta_data->>'license_url' IS NULL LIMIT 2;

+--------+----------+-------------------------------+-------------------------------+
| source | provider | created_on                    | updated_on                    |
|--------+----------+-------------------------------+-------------------------------|
| flickr | flickr   | 2020-04-28 07:20:32.183578+00 | 2024-05-12 03:13:46.696867+00 |
| flickr | flickr   | 2020-04-28 07:08:30.821693+00 | 2024-05-12 03:13:46.696867+00 |
+--------+----------+-------------------------------+-------------------------------+
```

If there are more, it is to be confirmed. It is known the Flickr DAG was running those days, as well as Europeana, the Finnish Museum, Wikimedia Commons, and the Metropolitan Museum.

<figure>

<br>
<figcaption>Screenshot of DAG reports on Thursday, May 9th. Time is in VET.</figcaption>
</figure>

[^1]: Link only available to maintainers.

## Additional context

Discovered while working on #3885.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #4318 by @krysal 

## Description

When checking on a few items remaining, I noticed the `license_url` was already present in the `meta_data` column with the value of `NULL`. These caused the DAG to have virtually no effect on how the update statement was written; at the merge, the `NULL` value replaced the actual value. Fortunately, this has an easy fix.

## Testing Instructions

1. Download [this CSV](https://gist.github.com/krysal/1ccc4c2f4c963596581638758d69bdf1)  of sample rows
2. Load it into the catalog DB 
	1. Copy the file into the upstream DB container: `docker cp /path/to/images_missing_md_license_url.csv [container-id]:/tmp/sample_rows.csv`
	2. Connect with pgcli: `just catalog/pgcli`
	3. Import the file into the table: `COPY image FROM '/tmp/sample_rows.csv' DELIMITER ',' CSV HEADER;`
4. Enable the `batched_update` DAG and run the `add_license_url` DAG
5. Wait for completion and check the DB, the returned number should be 0:
```sql
SELECT COUNT(*) FROM image WHERE meta_data->>'license_url' IS NULL;
```

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog PRs) or the media properties generator (`ov just catalog/generate-docs media-props` for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by stacimc** [comment]
@krysal Can you expand the testing instructions for how you're loading this csv into the catalog DB? The provided csv is not formatted the way our sample data is, so it's not possible to overwrite the `sample_image.csv` and just upload it that way.

**Comment by AetherUnbound** [comment]
Going to draft this until @krysal is back from AFK and has an opportunity to respond about the testing instructions.

**Comment by krysal** [comment]
> @krysal Can you expand the testing instructions for how you're loading this csv into the catalog DB? The provided csv is not formatted the way our sample data is, so it's not possible to overwrite the `sample_image.csv` and just upload it that way.

Oops, I imported it using TablePlus and thought it would be similarly simple with terminal commands, but it turned out not like that when the columns don't match 😅 My bad! I updated the file with a more suitable one and added the instructions for importing it now.

**Review by stacimc — APPROVED** [review]
LGTM, thanks for updating that! Worked well and confirmed that the meta_data for a few of the updated rows looks as expected.

**Pull request merged**
