### PR TITLE
Set `ov` workdir to current working directory

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description

This makes `ov` contextual to the working directory, so you can rely on your host CWD inside `ov`. This works because the Openverse repository is mapped with the literal directory path from your host (rather than to a distinct container path), so the CWD will exist in the container, so long as `ov` is run from within the repository.

I considered making this conditional by testing whether `$(pwd)` is actually a subpath of `OPENVERSE_PROJECT`, but running `ov` outside of the repository seems weird to try to explicitly support :thinking: 

## Testing Instructions

Think of something you often do that is CWD contextual. Maybe, for example, running a just recipe from withing a subproject's directory. Or maybe using `pnpm exec`. Or `pdm run`. Now cd to the directory and prefix it with `ov`. Start with `pwd` and you'll see it work directly, hopefully. This also mostly only matters if you have `ov` on your PATH, but it should also work if you evoke it using a direct reference (e.g,, `../ov` from inside `/api`).

```
$ cd frontend && ov pwd
/path/to/openverse/frontend

$ cd ../api && ov pwd
/path/to/openverse/api
```

Then try other stuff that would be context dependent:
```
$ cd api && ov pdm info
PDM version:
  2.15.4
Python Interpreter:
  /opt/pdm/venvs/api-UJMDzYmD-3.11/bin/python (3.11)
Project Root:
  /home/sara/projects/openverse/api
Local Packages:

```

etc...

You get the idea, hopefully!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`./ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`./ov just catalog/generate-docs media-props`
      for the catalog or `./ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by stacimc** [comment]
With these changes applied, I'm getting the error `python3: can't open file '//docker/dev_env/exec.py': [Errno 2] No such file or directory` every time I try to run any just recipe with `ov`, even ones that work on `main`.

Steps I'm doing:
* Run `./ov clean && ./ov init` on main
* Run `./ov just catalog/pgcli` and see that it works
* Check out branch, run `./ov clean && ./ov init`
* Run `./ov just catalog/pgcli` and see the error

**Comment by sarayourfriend** [comment]
Fascinating! I think I was seeing a bunch of false positives when using `$CWD`, which seems to be context dependent, rather than the actual working directory :thinking:

I'm not sure why it worked on my desktop, but I get the same error on my laptop. The fix was to use `pwd` to get the actual working directory (`$CWD` seems to resolve to different things depending on the environment, not sure), and then to use an absolute reference to the `exec.py` script.

Can you try again, Staci? I've updated the testing instructions for things that will absolutely prove it works instead of false positives that I had before (whoops!)

**Review by stacimc — APPROVED** [review]
🥳 That's fixed it! LGTM :)

**Review by AetherUnbound — APPROVED** [review]
LGTM and works great!

**Pull request merged**
