### PR TITLE
Change text color to secondary on content-heavy pages

### LINKED ISSUE #5119: Text-heavy pages should use `text-secondary` color for text
## Problem

The current value of text color in the dark mode is hard to read due to the contrast being too high. 

## Description

The text-heavy pages should replace `text-default` with `text-secondary` class for text colors.

### LINKED ISSUE #5151: Update the color of `text-secondary`
## Problem

During the last monthly call (Nov 6th), we talked about the color feeling of `text-secondary` in content-heavy pages in light theme and how the lighter shade feels too soft for reading, as part of #5148 

We decided to make the `text-secondary` color darker in light theme while keeping the lighter version in dark theme.

## Description

Change `text-secondary` from `gray-9` to `gray-12` in light theme. The outcome uses the same gray shade in both `text` and `text-secondary`.

The Figma's Design Library variables were updated with this change.

Screenshot of Figma variables of Openverse Design Library

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #5119 by @obulat
Fixes #5151 by @fcoveram 

## Description

This PR changes the content pages to use `text-secondary` for the body text, while retaining `text-default` for the headings.

## Testing Instructions

Visit the content pages and see that the text should be a little lighter and less contrasted with the background.

I'll update the snapshots once @fcoveram approves the new designs.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by fcoveram — APPROVED** [review]
It looks great 🚀

**Comment by dhruvkb** [comment]
Thanks @fcoveram! I'll update the visual regression testing snapshots then.

**Comment by fcoveram** [comment]
I created [this ticket](https://github.com/WordPress/openverse/issues/5151) requesting the update of `text-secondary`.

**Comment by dhruvkb** [comment]
@fcoveram changing the `text-secondary` color to `gray-12` impacts the whole application, not just the text-heavy pages. Can you check out this branch and see if it looks good to you?

For example on this page the search query, artist name, duration, genre/category and license icons have all gotten darker.

Screenshot 2024-11-08 at 3 20 25 PM

**Comment by fcoveram** [comment]
Just for the record, during yesterday's community meeting, I agreed with @dhruvkb's [idea](https://wordpress.slack.com/archives/C02012JB00N/p1731338307048429?thread_ts=1731338003.923889&cid=C02012JB00N) to limit the use of a darker shade as `text-secondary` in text-heavy pages. So let's continue with that 👍

**Comment by dhruvkb** [comment]
Thanks for discovering this @obulat.

**Review by obulat — APPROVED** [review]
Awesome! ✨ 
It's interesting that the old snapshots look okay for me, but when I look at the same colors in the app, my eyes get tired very quickly :)

**Pull request merged**
