### PR TITLE
Fix focus rings

### LINKED ISSUE #1252: Focus ring has an extra border if an element has a transparent border
## Description

The `focus-slim-filled` Tailwind class should add a white outline and a pink ring around it. This works for element that don't have a border. However, for elements that have a border (even transparent), the background seems to be seeding through and shows up as a ring of that color between the white and the pink rings.

## Reproduction

1. Go to https://docs.openverse.org/storybook/?path=/story/meta-focus--slim-filled
2. In the inspector,  replace `bg-pink` for the `div` with ` bg-dark-charcoal border border-tx`.
3. Focus the box.
4. See error: there is a dark-charcoal ring inside the pink ring.

## Screenshots

Screenshot 2023-04-17 at 12 13 29 PM

## Additional context

I thought that we could fix it by not having a border on `filled` buttons. However, this becomes a problem for buttons that change variant based on the `pressed` property. This was [reported](https://github.com/WordPress/openverse/pull/1132#pullrequestreview-1385429851) by @panchovm for the Filters button: it changes width because bordered button is  2px wider in the current implementation.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1252 by @obulat

## Description

This PR adds border to all buttons, and changes the way `focus-slim-filled` sets the focus rings for elements with a border.

A box-shadow or an inset border is not rendered over the border, and because the button borders are transparent, the background bleeds through and looks like a ring between the white and the pink rings, the color of the background. You can see it in this commit: https://github.com/WordPress/openverse/pull/1253/commits/de3a25c0a4d87d0640890e0e2ba78f912c1b3427

Screenshot 2023-04-20 at 12 59 48 PM

I tried to use `bg-clip: background-box` to fix the background bleeding through the border. However, this way the white inner ring is only 1px wide (the width of the border), and the mockups in Figma show 1.5px. This is why I had to use an `after` pseudo-element that is the same size of the element, but has a 1.5px white border.

For elements that don't have a border, I renamed the old implementation of `focus-slim-filled` to `focus-slim-bordered-filled`.

The snapshots of the pages changed because the `filled` buttons are now 2px wider do to the added borders.

## Testing Instructions

The buttons should look correctly in the Storybook and the app.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@obulat Is this PR blocked?

**Comment by obulat** [comment]
> @obulat Is this PR blocked?

Unblocked now that the tests are passing :) But the other PRs that touch the `filled` buttons are blocked by this PR.

**Review by panchovm — APPROVED** [review]
It looks good ✨ Great improvement

**Review by dhruvkb — APPROVED** [review]
LGTM code-wise, would defer to @panchovm's design feedback because it adds a new category of focus styles that were not present in the [original design](https://github.com/WordPress/openverse/issues/479#issuecomment-1439707096).

**Pull request merged**
