### PR TITLE
Correctly set up constant fields in API responses

### LINKED ISSUE #3034: Fix the API documentation set up for the constant fields
## Problem

Oembed endpoint returns several constant values that are not derived from the Image model.
They are set up as `ReadOnlyField`s.
```py
    version = serializers.ReadOnlyField(
        help_text="The oEmbed version number, always set to 1.0.",
        default="1.0",
    )
```
DRF-spectacular is trying to find `version` field in the `Image` model, and throws a warning when it cannot:

```
/api/api/serializers/image_serializers.py: Warning [ImageViewSet > OembedSerializer]: could not resolve field on model <class 'api.models.image.Image'> with path "version". This is likely a custom field that does some unknown magic. Maybe consider annotating the field/property? Defaulting to "string". (Exception: Image has no field named 'version')
```
## Description
Update the serializer to use a `serializers.SerializerMethodField`:

```py
version = serializers.SerializerMethodField(help_text="The oEmbed version number, always set to 1.0.")

@staticmethod
def get_version() -> Literal["1.0"]:
    return "1.0"
```

The list of fields that need to be updated:

`OembedSerializer`: `type`, `version`
`ProviderSerializer`: `logo_url`

## Alternatives

Leave the fields as they are, the warnings don't break the documentation and the default can be fine.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #3034 by @obulat

## Description

This PR replaces `ReadOnlyField`s with `SerializerMethodField`s that return constant values for values that never change and are not derived from models:
`OEmbedSerializer`: `version`, `type`
`ProviderSerializer`: `logo_url`

This makes the documentation a little bit clearer and fixes the warnings in logs.

Currently, `logo_url` type is given as `string`, but it always returns `null`. The updated version shows `string or null`. I tried setting it to "only null", but spectacular still throws a warning that it couldn't get the type of the value. `string or null` is more accurate than `string`.
Provider serializer logo url type

### OEmbed serializer
Currently, the documentation says that these values are "default", making it seem like a different value is also possible.
OEmbed Serializer current

In this PR, the documentation says "Value: 1.0", making it clear that it's only a single value.
OEmbed Serializer updated

## Testing Instructions

If you run the app on `main` (`just up`), and open the documentation (e.g. http://0.0.0.0:50280/v1/#tag/audio/operation/audio_stats), you should see the warnings mentioned in the related issue in the Docker logs.
These warnings should not be visible in this PR. The documentation for these fields should be updated to match snapshots in the PR description.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
While the change to the documentation is good, something feels off about using a "method" field to generate a constant value. One alternative might be to create a custom field but that seems like over-engineering. 

Approving because I don't know a better way.

**Comment by obulat** [comment]
Added args that are discarded (`*args`) to the `get_type` and `get_version` functions to fix `TypeError: OembedSerializer.get_version() takes 0 positional arguments but 1 was given` error that's causing error in the oembed endpoint: [490095d](https://github.com/WordPress/openverse/pull/3035/commits/490095d62d3cc20d1e4dcc870c698cd144c5ea22)

**Comment by sarayourfriend** [comment]
[The swagger docs say, regarding "null"](https://swagger.io/docs/specification/data-models/data-types/) (TIL):

> Note that there is no null type; instead, the [nullable](https://swagger.io/docs/specification/data-models/data-types/#null) attribute is used as a modifier of the base type.

So a field cannot _only_ be null, it seems, and within spec.

For the static fields, I wrote this custom field that seems to work:

```
class StaticField(serializers.Field):
    Value = TypeVar("Value")

    def __new__(cls, value, **kwargs):
        decorated = extend_schema_field({"type": "string", "nullable": True} if value is None else type(value))(cls)
        return super().__new__(decorated, value, **kwargs)

    def __init__(self, value: Value, **kwargs):
        self.value = value
        kwargs["source"] = "*"
        kwargs["read_only"] = True

        super().__init__(**kwargs)

    def to_representation(self):
        return self.value
```

The `__new__` method is necessary to pull the type from the passed value (or set it to a nullable string, if the value is None). `extend_schema_field` comes from `drf_spectacular.utils`. Not sure whether it's necessary, the method fields work just fine, but if you want something a little more "magical", there you go :slightly_smiling_face:

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Comment by obulat** [comment]
> but if you want something a little more "magical", there you go 🙂

Thank you for the implementation and sharing the info on `nullability` 😄  I think we can go with what we have here, and change if needed later, if this starts to cause problems

**Pull request merged**
