### PR TITLE
Remove internal__index param

### PR DESCRIPTION
**Pull request by stacimc**
## Fixes

Fast follow to #2209

## Description

The `internal__index` query param was added in #2073 with the intention of using it in an index readiness check during the data refresh. #2209 instead implemented this check by querying the ES index directly, instead of going through the API (which would have required more complexity to handle authentication).

Consequently the `internal__index` param is no longer needed and can be removed. This PR reverts #2073. Pinging @dhruvkb and @zackkrida to confirm that there are definitely no other intended use cases for this param.

## Testing Instructions

Tests should all pass. You should also try making a few authenticated and unauthenticated API requests just to smoke test.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by krysal — CHANGES_REQUESTED** [review]
The param will still be used for the [Search Relevancy Sandbox](https://docs.openverse.org/projects/proposals/search_relevancy_sandbox/index.html) project. Although we need to define better security policies for it.

**Comment by stacimc** [comment]
Thanks for letting me know, @krysal! I'll go ahead and close the PR.

**Comment by dhruvkb** [comment]
@statimc another reason for going via the API instead of directly checking ES was that we could validate the optimal end result of getting search results from the API. Checking ES directly leaves the possibility of some snag after the ES layer preventing results from being delivered.

**Comment by zackkrida** [comment]
@dhruvkb since the implementation as-written in #2209 will catch the incident which inspired it, I think we could move ahead with that PR as-is. We have many other ways of checking if the API and ES are communicating appropriately. 

@stacimc has had to reimplement that PR a few times and I think the current set of tradeoffs are preferable since they allow us to bypass all the authentication work connecting directly to the API would require.

**Pull request closed without merging**
