### PR TITLE
Improve image grid

### LINKED ISSUE #547: Image results grid improvement
## Problem
The current image result view does not display the CC-license icons on `sm` breakpoint. The last mockup shared showed the icons below each image in a 2 columns grid, but there is an ongoing proposal for supporting 3d model content that needs to be taken into account.

### Issues related
* Problem detected: WordPress/openverse#563
* 3d model support proposal: WordPress/openverse#558
* WordPress/openverse#561 

### Mobile
https://user-images.githubusercontent.com/895819/172160157-e260adfb-9c50-4d92-aee5-757fff81b26f.mp4

### Desktop
https://user-images.githubusercontent.com/895819/172160850-0b90336b-a6d8-4502-9c29-d3814126c3cd.mp4

## Description
On mobile, the layout displays images on a single column grid where each image has its cc-license icons below. The image component has three states: resting, hover, and focus. The video attached above shows the first and third ones, and the style changes are the focus ring and a color shift in the icons area from `dark-charcoal-70` to `dark-charcoal`.

Since WordPress/openverse#558 proposal suggests new hover styles, the image component inherits the cc-icons area change. On the other hand and time ago, I had the idea of reviewing the row height of the current grid as it looks good on big screens but tight on laptop sizes. See the image below of the current layout.

CleanShot 2022-06-06 at 13 11 17@2x

I was playing with different heights, and I like how `200px` for the row height looks like. It will show three full rows, acknowledging its relativity due to device sizes, and considering that the WordPress header will be removed, the page will look clean and highlights more the content results.

See the image below and please share your thoughts.

Image results (Macbook pro 13)

## Design file
Figma: [Image results grid improvement](https://www.figma.com/file/bfe7wowCpMxsle7vHBAVMe/Image-results-grid-improvement?node-id=0%3A1)

### LINKED ISSUE #563: Search results do not display the image license without hovering
## Description

The search result page on "Images" and "All Content" views on mobile does not display license names, only their icons.
Here is a sample mockup of how the license names should be displayed: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1548%3A21328

## Reproduction

1. Search for images on mobile.
2. You can only see the license icons on hover. You should always be able to see license icons and license names below the images.

## Screenshots

Screen Shot 2022-05-02 at 12 13 54 PM

## Environment

 - Device: mobile

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### LINKED ISSUE #2712: Tall images get poorly cropped and their license icons are hidden
## Description

If an image in the related results in the single result page is sufficiently tall, it will be cropped quite poorly and the license icons get positioned outside the bounds so as to be hidden.

## Reproduction

1. Visit this single result: https://openverse.org/image/61f31a70-5484-4233-95ab-9298e78ebee8

Minette and Minet | Openverse

2. Scroll down to related images.
3. See the first thumbnail (for this single result: https://openverse.org/image/5de92826-07e8-4a42-b627-831bed30010a). The thumbnail is cropped into a small part of the original image in such a way that it is impossible to know what it actually is.

image

4. Hover over this result. See that the license icons are not visible (as they are outside the bounds of the thumbnail box).

### LINKED ISSUE #2768: Image grid padding calculation issue
## Description

In our "masonry-style" grid on image-only searches, there is a funky bug with calculating the image sizes. Some tall, vertical images are having their heights calculated incorrectly. This results in incorrect spacing and shifting in the hover state of these images:

Observe the misalignment in the left cat:
CleanShot 2023-08-01 at 12 43 14@2x

And the computed height of an "incorrect" image:
CleanShot 2023-08-01 at 12 43 42@2x

Compared to a correct:
CleanShot 2023-08-01 at 12 43 37@2x

This calculation is one of the trickier parts of the frontend code to understand.

## Reproduction

1. Make an image only search on Openverse.org
2. Hover over multiple images until you notice a hover state which is positioned incorrectly. Typically on portrait-oriented images

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #547 by @fcoveram
Fixes #2768 by @zackkrida 
Fixes #2712 by @dhruvkb 
Fixes #563 by @obulat 

## Description

This PR improves the image grid on the image search page, making more images fit in a single row.

Previously, the grid was using a ["padding hack"](https://css-tricks.com/aspect-ratio-boxes/). This PR updates the implementation to use the now widely supported [`aspect-ratio`](https://web.dev/aspect-ratio/).

Updating the image layout from using absolute positioning to CSS grid allowed to fix the padding of the license element on vertical images, as well as to put the license elements below the image on `xs` mobile screens.

The tests were updated to add another set of breakpoints to use: `xs` (instead of `sm`) for mobile and `xl` for desktop. I think that all of the `mobileAndDesktop` should move to this set of tests in the future because `xs` is more representative of the mobile layout than `sm`.

### `xl`
Screenshot 2023-09-05 at 6 36 35 AM

### `lg`

Screenshot 2023-09-05 at 6 38 31 AM

### `md`

Screenshot 2023-09-05 at 6 39 10 AM

### `sm`

Screenshot 2023-09-05 at 6 39 56 AM

### `xs`
Screenshot 2023-09-05 at 6 40 54 AM

## Testing Instructions

Run `just install`, `just frontend/run dev:only`.
Search for "cat" images.
Notice that the image grid rows contain more images now. For `xl` screen (1280px), there should be 5-6 images in a row, compared to 4-5 currently.
The smallest screen should show the license icons below the image, even without hovering on the image.
Find the vertical photo of the cat in #2768 and see that the license icons are displayed with correct paddings within the container.

Screenshot 2023-09-05 at 7 13 20 AM

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by fcoveram** [comment]
I see the image component with the cc icons in `hover` correctly, but the new row's height value described in #547 is not being addressed. If the PR's intention is to fix the image component, then we should rename it to avoid confusion with image grid change

**Review by dhruvkb — APPROVED** [review]
I like the changes! `aspect-ratio` is less hacky and it needs less code to work 👍 .

**Review by krysal — APPROVED** [review]
Very nice improvement! I was afraid by the number of files changed but glad it's mostly snapshots.

It's not clear to me if we want to display the license name for images. I don't see them here, but mockups don't have them either. Can you clarify the situation with #563? I'm approving regardless.

**Comment by obulat** [comment]
> It's not clear to me if we want to display the license name for images. I don't see them here, but mockups don't have them either. Can you clarify the situation with #563? I'm approving regardless.

I've updated the issue title to match the requirements described in the issue comments. The main thing to implement was to display the license (icons in the design, not the names) below the images on mobile.

**Pull request merged**
