### PR TITLE
Add AUDIO_INTERACTION event

### LINKED ISSUE #1083: Analytics event: `AUDIO_INTERACTION`
## Description

The goal is to 

- add the type for event `AUDIO_INTERACTION` to the `Events` type.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/types/analytics.ts#L12

- fire this event from the appropriate location in the codebase using the `useAnalytics` composable.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/composables/use-analytics.ts#L11

## Reference

https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/rfcs/analytics/20221006-implementation_plan_frontend.md?plain=1#L377

## Additional information

- [RFC](https://github.com/WordPress/openverse/blob/main/rfcs/analytics/20221006-implementation_plan_frontend.md#events)
- [Example usage in `VHomeGallery.vue`](https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/components/VHomeGallery/VHomeGallery.vue#L128-L134)

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1083 by @dhruvkb 

## Description

This PR adds `AUDIO_INTERACTION` event which is fired when the user pauses, plays or seeks on an audio:
- in the All content view (the audio box layout)
- in the Audio search view (the audio row layout)
- in the single audio result page's main audio (the audio full layout)
- in the related audio (the audio row layout)
- on the global audio player (you have to use a very narrow screen to see it).

To make sure that this event is not very bad for performance, this PR adds a `debounced` event, which is only fired every 500 ms.

## Testing Instructions

Open all of the components listed in the description above and try interacting with the audio. You should see the event logged in the console. Try clicking really fast - you should only see events every 500ms.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — COMMENTED** [review]
I started to review this yesterday and ran out of time to test locally, but I have a couple comments on the code. I will try to test it locally today and approve if it works.

**Comment by sarayourfriend** [comment]
@obulat Similar to https://github.com/WordPress/openverse/pull/2423, does this still need a debounce? Based on the reasoning in that PR I don't think we'd need it here either.

**Comment by zackkrida** [comment]
@AetherUnbound I want to remove the debounce here; I'll update the PR today.

**Comment by zackkrida** [comment]
I've removed the debounce and will add a Playwright test to interact with the audio and record the events.

**Comment by zackkrida** [comment]
@obulat this is the only analytics PR I didn't finish last week. I've removed the debounce and kept the branch up to date with `main`, but I'm seeing a number of test failures that I didn't have a chance to explore. 

Could you resume work on this PR this week?

**Review by zackkrida — APPROVED** [review]
LGTM! It's working perfectly on every page, with keyboard controls, or with the mouse.

**Pull request merged**
