### PR TITLE
Fix DAG docstrings so they no longer produce improper HTML

### LINKED ISSUE #4750: `airflow_log_cleanup_workflow` module docs are invalid markdown
## Description

The following two lines produce invalid markdown due to the angle brackets used to surround the type annotations:

https://github.com/WordPress/openverse/blob/97dba8e4e53c888cf854dd940272489bc146399d/catalog/dags/maintenance/airflow_log_cleanup_workflow.py#L19-L20

This causes an issue for e.g., prettier parsing the DAG docs file:

```
documentation/_serve/catalog/reference/DAGs.html
[error] documentation/_serve/catalog/reference/DAGs.html: SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1292:40)
[error]   1290 | <p><code class="docutils literal notranslate"><span class="pre">--conf</span></code> options:</p>
[error]   1291 | <ul class="simple">
[error] > 1292 | <li><p>maxLogAgeInDays:<INT> - Optional</p></li>
[error]        |                                        ^^^^
[error]   1293 | <li><p>enableDelete:<BOOLEAN> - Optional</p></li>
[error]   1294 | </ul>
[error]   1295 | </section>
```

Changing these to use some other syntax to annotate the type would solve this. The angle bracket syntax isn't used anywhere else, and the types do not correspond to JSON types, which is the input format, nor exactly match Python type names, so I'm not sure if this is following some specific but unfamiliar to me syntax for annotation.

## Fix

We can fix this by changing these to use parenthesis.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #4750 by @sarayourfriend

## Description

This PR fixes a few instances of brackets within the DAG docstrings that would produce invalid HTML in the resulting document that gets rendered for the documentation site.

## Testing Instructions

Run the following, and HTML should be output (without raising any errors):

1. `ov just documentation/live`
1. `ov pnpm exec prettier documentation/_serve/catalog/reference/DAGs.html`

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by krysal — COMMENTED** [review]
I couldn't build the documentation locally with the instructions, not even after doing a `./ov clean && ./ov init`. I got the following error:

```
INFO: The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
WARNING: Project requires a python version of ==3.11.*, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /opt/pdm/venvs/documentation-QbEAfFES-3.11
[PdmUsageError]: Command 'sphinx-autobuild' is not found in your PATH.
error: Recipe `live` failed on line 72 with exit code 1
```

Did this happen to you at some point by any chance?

**Review by dhruvkb — APPROVED** [review]

**Comment by stacimc** [comment]
I'm experiencing the same issue as @krysal 🤔

**Comment by AetherUnbound** [comment]
Hmm, could it be an issue on OSX? @dhruvkb @obulat @zackkrida are you all able to confirm?

**Comment by zackkrida** [comment]
Same issue on Fedora!

```shell
> ov just documentation/live
rm -rf _serve/ _build
pdm run sphinx-autobuild -b html . _serve/ --port 50230
INFO: The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
WARNING: Project requires a python version of ==3.11.*, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /opt/pdm/venvs/documentation-QrgCiFGL-3.11
[PdmUsageError]: Command 'sphinx-autobuild' is not found in your PATH.
error: Recipe `live` failed on line 72 with exit code 1
```

**Comment by AetherUnbound** [comment]
Ahhh okay, y'all may need to run `ov just documentation/install` first 😄 that fixed it for me!

**Pull request merged**
