### PR TITLE
Update banner spacing and add rounded corners

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Related to #2015 by @zackkrida 

## Description

Updates the banner styles to have padding and rounded edges.

## Testing Instructions

Check out some localhost page(s) with banners, like:

localhost:8443/ar?referrer=creativecommons.org
localhost:8443/search-help?referrer=creativecommons.org

CleanShot 2023-05-16 at 19 56 26@2x
CleanShot 2023-05-16 at 19 56 01@2x

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by fcoveram** [comment]
Here is an idea: One alert banner with four variants, and one customized banner.

Screenshot of two Figma components: Alert and customized banner

The alert banner has four variants (Info, Warning, Success, Error) and the customized banner is in dark charcoal and allows changing the icon as in the former types.

These two banners are due to having yellow and white backgrounds, and since Openverse is mostly white, I prioritized a style without border color and rely on icon taxonomy to convey the banner's purpose. In that vein, the color contrast requirement is met between icon and banner background color.

Our current case shows banners in the homepage, but I think we can address cases like Openverse is not working correctly. See the right side of the image below.

image

Reaching consistency is hard as the component needs to work over two different backgrounds, but if we use the customized dark banner for some cases, we can handle the alerts confidently.

---

What do you think of this idea? Pinging @dhruvkb for visibility

**Comment by zackkrida** [comment]
@fcoveram this PR was only focused on the spacing and rounded corners you mentioned previously, but I love your designs for an alert system! That would also require very little work—it is only a matter of small styling adjustments. Could you move those designs to their own issue for additional discussion?

**Comment by dhruvkb** [comment]
I like the alerts, but that would increase the scope of the PR considerably. It would be best to spin it out into its own issue.

**Comment by fcoveram** [comment]
Sorry for extending the PR scope, last comments in #2015 mention style specs and that's what the design shared is about.

Putting aside the alert variants, the style specs for the dark banner are:

### Small (for `xs`, `sm`, `md`)

* Height: auto
* Text: "Caption regular" style
* [Info icon](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=5415-22320&t=CYqeVdY1QxK0e3Y4-4) in `24px` size
* [Close icon](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=5415-21554&t=CYqeVdY1QxK0e3Y4-4) in `24px` size
* Padding: `12px` for top and bottom; `8px` for left and right
* Margin: `8px` for top, left, and right. Margin bottom is 0.
* Gap between icons and texts: `8px`.
* Gap between banners: `8px`.
* Close action and link do not have hover style

### Large (for `lg`, `xl`, `2xl`)

* Height: auto
* Text: "Paragraph small" style
* [Info icon](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=5415-22320&t=CYqeVdY1QxK0e3Y4-4) in `24px` size
* [Close icon](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=5415-21554&t=CYqeVdY1QxK0e3Y4-4) in `24px` size
* Padding: `16px` for all sides.
* Margin: `8px` for top, left, and right. Margin bottom is 0.
* Gap between icons and texts: `8px`.
* Gap between banners: `8px`.
* Close action and link do not have hover style

Here is the [Figma file](https://www.figma.com/file/nxkoGOzG5vnTpZgYpi4LsQ/Alert-banner?type=design&node-id=22-13656) where mockups for all breakpoints are. The banner doesn't exist in the Design Library yet.

**Comment by zackkrida** [comment]
Thanks, @fcoveram! This PR now uses 8px for the banner gap and top/side margins and is ready for review. We'll implement the dark banner styles and/or the alert styles in a separate PR.

**Review by dhruvkb — APPROVED** [review]
LGTM, tested extensively and couldn't find any problems except for a known issue #1159 with a prepared fix #2128.

**Pull request merged**
