### PR TITLE
Update the homepage dark color

### LINKED ISSUE #4936: Darker homepage in dark theme
## Problem
As pointed out by @dhruvkb and @obulat in the main design ticket (#3959) for the Dark Mode project (#3592), the homepage feels brighter compared to the rest of the UI.

Although the color picked (`bg-fill-complementary` = `pink-9`) corresponds to its light version in the shade scale, there is room for improving the color perception and make the page to feel less brighter.

## Proposal

Before describing the change, here is the idea that I like most.

Openverse homepage in dark mode in XS and XL breakpoins

### Surface lightness

I shared the pink-filled homepage with a designer friend, and she commented something that dove into @dhruvkb and @obulat points.

A dark input over a lighter background is unusual in dark themes. The design approach was inverting the lightness of background and surface to mirror the current color scheme. The relationship of background and search input changes from yellow-to-white (heading to the highest lightness) to pink-to-dark (heading to the lowest lightness).

This change doesn't feel natural. From a lightness perspective, the dark input is "pushed back" to the bottom, making the pink background brighter towards the surface. On the other hand, this effect does not happen in the search results because the UI background is dark and the proportion of pink is fewer.

The same lightness reversion of background and input happens when changing from homepage to search results in the current light mode, but a gray input over white background is more common and therefore, familiar.

I made other tests with a darker pink for the background, but outcome feels detached of the palette used in the rest of the pages. [Here are](https://www.figma.com/design/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?node-id=2271-23443&m=dev) those tests if you want to take a look.

### Flat border

I also think we can remove the colored border in the announcement banner to make it more simple. The gradient previously made was to stand out the component and be consistent with the glowing theme switcher in the footer, but after reviewing #4922, I think we can simplify it.

Openverse homepage in light mode zooming in the announcement banner

Openverse homepage in dark mode zooming in the announcement banner

---

What do you think of this idea?

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #4936 by @fcoveram

## Description

This PR changes the color of the homepage in dark mode to match the mockups. This also changes the color of the generic error page, you can see the updated version in the changed snapshots.

## Testing Instructions

Run the app and go to http://localhost:8443
Change the app theme to dark
Check that the colors are correct, or suggest improvements.
Also check the error page by going to http://localhost:8443/non-existent-page. Note that this page's design will need to be updated, but in this PR only the colors are updated to match the home page.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Barring any design changes from @fcoveram, I think this looks great! :shipit:

**Comment by zackkrida** [comment]
@obulat looks like potential flake in an audio test

**Comment by obulat** [comment]
> @obulat looks like potential flake in an audio test

It's #4981. Working on it

**Comment by fcoveram** [comment]
Most elements look good. But as per [this comment](https://github.com/WordPress/openverse/issues/4936#issuecomment-2371128358), I have pending updating the design file. Once the file is done, do you think it is better to include those changes in this PR or close this one and open a follow-up one?

**Comment by obulat** [comment]
> Most elements look good. But as per [this comment](https://github.com/WordPress/openverse/issues/4936#issuecomment-2371128358), I have pending updating the design file. Once the file is done, do you think it is better to include those changes in this PR or close this one and open a follow-up one?

I think it would be best to draft this PR, and update it once the design changes are ready. Would that be okay? Could you also ping here when the design changes are ready?

**Comment by fcoveram** [comment]
Sure. No problem!

**Review by fcoveram — COMMENTED** [review]
All styles look correct. I just noticed a few missed elements that might not be part of this PR. Feel free to skip those so I can create issues as follow-up improvements.

### Focus ring in search action

Search action in focus state

I recently updated the focus ring of search action to grow inwards rather than outwards to keep the ring style consistent with the search input.

### Border in switcher popover

Switcher popover in dark mode

The popover of media switcher misses the border color. It exists in both light and dark mode. It's crucial to keep the element over the background layer.

### Hover state of close action in drawer

Screenshot of close action in switcher drawer

The hover state of close action in switcher drawer doesn't show the transparent background color. It seems that it doesn't follow the styles of "[Icon transparent](https://www.figma.com/design/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=4658-12376&node-type=frame&m=dev)" component. 
 
### Other focus styles

| Double ring in white | Blue ring |
|:---|:---|
| Link to Creative Commons in focus state | Link to WordPress site in focus state |

--- 

All the rest looks good. So please let me know which points don't belong to this PR to report them in new issues

**Comment by obulat** [comment]
@fcoveram, I rebased this PR onto the one that fixes the links focus outline colors ([Fix link focus rings](https://github.com/WordPress/openverse/pull/4958)). That PR fixes the last two problems (Other focus styles).

In this PR, I:
- updated the border color for the content switcher popover to `border-overlay`
Screenshot 2024-10-17 at 12 56 59 PM

- updated the close button hover state background color
Screenshot 2024-10-17 at 12 52 17 PM

- updated the search bar focus state to move the ring inside

Screenshot 2024-10-17 at 12 50 14 PM

If the link focus rings are okay, could you also approve #4958, @fcoveram ?

**Review by fcoveram — APPROVED** [review]
It looks great 👏 ✨ 🚀

**Pull request merged**
