### PR TITLE
Add project labels

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

This PR adds a few new project-related labels, based on a [discussion in our Make WP slack about project-related automation](https://wordpress.slack.com/archives/C02012JB00N/p1681228425809849?thread_ts=1681227888.069269&cid=C02012JB00N).

The labels are:

- [🧭 project: thread](https://github.com/WordPress/openverse/labels/%F0%9F%A7%AD%20project%3A%20thread) - this reused the existing `project` label so our [project tracker](https://github.com/orgs/WordPress/projects/70/views/1) still works
- [🧭 project: proposal](https://github.com/WordPress/openverse/labels/%F0%9F%A7%AD%20project%3A%20proposal)
- [🧭 project: implementation plan](https://github.com/WordPress/openverse/labels/%F0%9F%A7%AD%20project%3A%20implementation%20plan)

## Testing Instructions

Check the above links!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Nice!

**Comment by sarayourfriend** [comment]
The new labels are good, but we'll also need a label for general discussion PRs that aren't related to projects to automatically add those the discussion board as well. For example the #887 PR was a discussion that followed the decision-making process but is not related to a project so is neither a project proposal nor implementation plan.

**Comment by AetherUnbound** [comment]
Ah, @sarayourfriend we already have a discussion label: https://github.com/WordPress/openverse/labels/%F0%9F%92%AC%20talk%3A%20discussion

Defined here: https://github.com/WordPress/openverse/blob/0176e7454726a628d6290699f81cf7620a16799c/automations/data/labels.yml#L140-L142

**Comment by sarayourfriend** [comment]
Oops, of course we do :sweat_smile:

**Review by sarayourfriend — APPROVED** [review]

**Pull request merged**
