### PR TITLE
Switch local API dev server to use gunicorn instead of django runserver

### LINKED ISSUE #2814: Switch local API dev server to use `gunicorn --reload` instead of Django's `runserver`
## Problem

Stems from #2566 

`runserver` does not support critical features we will need after converting the app to ASGI:

1. Actually running the ASGI app in full asynchrony
2. Multiple workers (to test production configuration)

We're also making the configuration slightly more complex by moving to ASGI, relying on gunicorn and uvicorn workers.

## Description

To anticipate these complexities and make the local development environment (a) behave more like production and (b) require fewer changes when switching to full ASGI, swap out `manage.py runserver` for `gunicorn --reload`. Once we switch to ASGI in #2790, we'll either continue using gunicorn for development (with multiple workers) or can switch to `uvicorn --reload`.

`runserver` handles static file serving locally, while `gunicorn` and `uvicorn` won't know what to do. In production we rely on nginx to handle this. We could set up Nginx locally to front the API service, but to keep this simple, it's easier to conditionally add the static route handler that `runserver` uses to the API's urls configuration. See [these changes](https://github.com/WordPress/openverse/blob/980ef96e0e16fc758f78be9f2aadf595f75948f6/api/conf/urls/__init__.py#L43-L44) as an example (which require supporting changes for the `ENVIRONMENT` variable and changes to the static file configuration generally, all present in that commit).

## Additional context

Something along these lines will be necessary for ASGI conversion anyway. Doing this as a separate issue again reduces

### PR DESCRIPTION
**Pull request by ashiramin**
## Fixes

Fixes #2814 by @sarayourfriend 

## Description

- Swapped out `manage.py runserver` for `gunicorn --reload` in docker-compose 

## Testing Instructions

Update `api/.env` to have `ENVIRONMENT=local` or recreate `api/.env` (`rm api/.env && cp api/env.template api/.env`). Then run `just dc stop web && just dc stop nginx && just build web && just api/up` and confirm the API responds and static files work (visit `/admin` and confirm the page has styles). Confirm the Nginx image still has static files by visiting the Nginx service locally at `http://0.0.0.0:50270/admin`. This proves the static files are still correctly copied over from the Django image.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by ashiramin** [comment]
@sarayourfriend Kept it in draft state for now. Are there any other changes I need to make?

**Review by sarayourfriend — COMMENTED** [review]
I think this looks good to me. I haven't tested it locally yet, but will do so today. I think we could leave out the `--bind` parameter, I expected that to be handled by the `gunicorn.conf`, but I could be wrong.

**Comment by sarayourfriend** [comment]
Okay, everything looks good, just three things, only one of which is significant:

1. We can remove the `--bind` option, it is indeed covered by `gunicorn.conf.py`
2. We should consider adding `-w 1` so that we only run a single worker locally. There's no benefit to running 4 and it just makes the logs more confusing to follow.
3. Static files are not working because there are additional changes to make it work. The changes required are:
  - Update the default `ENVIRONMENT` variable to `local` in `api/env.docker`: https://github.com/WordPress/openverse/blob/980ef96e0e16fc758f78be9f2aadf595f75948f6/api/env.docker#L8
  - Update the static file settings: https://github.com/WordPress/openverse/blob/980ef96e0e16fc758f78be9f2aadf595f75948f6/api/conf/settings/static.py
  - Remove `STATIC_ROOT` declaration in `api/Dockerfile` when it runs `python manage.py collectstatic` (not strictly necessary but helps clean things up a bit).

**Comment by ashiramin** [comment]
@sarayourfriend Made the changes you requested and was able to test that static files are not 404ing locally

**Review by sarayourfriend — APPROVED** [review]
LGTM, thanks for the contribution @ashiramin. I've gone ahead and added testing instructions but in the future please add them once a PR is marked ready for review. It makes it much easier for maintainers to review PRs :pray:

**Comment by ashiramin** [comment]
@sarayourfriend Thank you for doing this and for reminding me about testing instructions. I'll do this next time :)

**Review by dhruvkb — APPROVED** [review]
LGTM, sorry I took so long to review it!

**Pull request merged**
