### PR TITLE
Update feature_request.md label template to remove priority and aspect

### PR DESCRIPTION
**Pull request by zackkrida**
Removes priority and aspect labels from the feature request template.

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM. At this point, since we are removing these, even `improvement` could be dubious considering it could be an "internal" improvement as well :slightly_smiling_face:

**Review by AetherUnbound — APPROVED** [review]
Agreed on the improvement note, I think that can go too :slightly_smiling_face:

**Comment by zackkrida** [comment]
I'm fine with removing improvement, just trying to think of how we could reasonably get a list of all of our feature requests without it, if we ever wanted that 🤔

**Comment by dhruvkb** [comment]
I vote for keeping the "goal: improvement" label, hard to assume an outsider would be raising an internal improvement feature request. If a contributor were opening it, they might be able to change the label to whatever they deem appropriate.

**Pull request merged**
