### PR TITLE
Media results null check

### LINKED ISSUE #2833: Media results not checked for`undefined` before decoding
## Description

Sometimes a request for related media returns `undefined` in the `results`. This causes an error when we try to map `decodeMediaData` over the `results` array:
https://github.com/WordPress/openverse/blob/1673c0ec30a4ccc575519267e9de186a952cac04/frontend/src/data/media-service.ts#L102-L104

A simple solution could be to add ` ?? []` to the results. This will replace the `undefined` value in results with an empty array, which can be used in the `map` here:
```
results: (res.data.results ?? []).map((item) =>
```

## Sentry issue

[OPENVERSE-FRONTEND-1AG](https://openverse.sentry.io/issues/4368424583/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'map')
  at key (./src/data/media-service.ts:102:33)
  at Generator.next (<anonymous>)
```

### PR DESCRIPTION
**Pull request by akhilsrivatsa**
## Fixes

Related to #2833 by @sentry-io

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by akhilsrivatsa** [comment]
@obulat @krysal Please check.

**Review by obulat — APPROVED** [review]
Thank you for your contribution, @akhilsrivatsa 👍

**Review by sarayourfriend — APPROVED** [review]
LGTM, thanks!

@obulat do you know when this happens? Is it when there are no related results? I'm surprised it doesn't return an empty list for that rather than nothing :thinking:

**Comment by obulat** [comment]
> @obulat do you know when this happens? Is it when there are no related results? I'm surprised it doesn't return an empty list for that rather than nothing 🤔

@dhruvkb added a note on the issue about it: https://github.com/WordPress/openverse/issues/2833#issuecomment-1714924279
I'll edit this PR description from "Fixes" to "Related to" so that the issue stays open and we can fix the underlying API issue.

**Pull request merged**
