### PR TITLE
Remove workflows for automation of old projects

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Related to #1931 by @krysal 

## Description

We discussed removing all dependencies on old projects in [today's meeting](https://make.wordpress.org/openverse/2023/06/06/community-meeting-recap-2023-06-06/). Once merged, we should be able to close the following GH projects:
- [Openverse](https://github.com/orgs/WordPress/projects/3)
- [Openverse PRs](https://github.com/orgs/WordPress/projects/8)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
My only concern with removing these and the old boards is that the `project_automation.yml` has some crucial pieces of automation for the old board which we haven't added to the new one, namely that issues with closed PRs get moved from "In progress" to the backlog automatically. If we're okay dealing with that case manually for the time being, then this should be fine to do. I believe that the new project board handles the other case where an issue in the backlog or "to do" will be automatically moved to "in progress" when an associated PR is opened.

**Review by zackkrida — APPROVED** [review]
>  that issues with closed PRs get moved from "In progress" to the backlog automatically. If we're okay dealing with that case manually for the time being, then this should be fine to do. 

I'm okay with us having to do this manually. LGTM!

**Comment by krysal** [comment]
@AetherUnbound Having the old boards around is only causing confusion, so I see more harm in keeping them than removing them at this point.

@zackkrida The linked issue, `#1931`, will keep open for that, and I can archive the projects after merging this.

Thank you both for the reviews.

**Comment by krysal** [comment]
This projects are now closed.
> - [Openverse](https://github.com/orgs/WordPress/projects/3)
> - [Openverse PRs](https://github.com/orgs/WordPress/projects/8)

**Pull request merged**
