### PR TITLE
Remove the default `medium-old` size from buttons

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #1187 by @obulat

## Description

This PR makes the `size` prop for `VButton` required, and adds a value to all of the components that used the previously-default value of `medium-old`.

## Testing Instructions

Check that the buttons look fine. The sizes will probably change, @fcoveram, could you verify that the buttons use the correct size?

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
@obulat if you don't mind I'm going to draft this while the VR tests are failing. Do you want a preliminary review from @fcoveram before they are fixed?

**Comment by obulat** [comment]
> @obulat if you don't mind I'm going to draft this while the VR tests are failing. Do you want a preliminary review from @fcoveram before they are fixed?

Thank you for drafting it, I should be doing that for PRs that fail VR tests :)
I marked the PR as ready now that the tests pass. I do want @fcoveram's review especially for the VNoResult's buttons, and the text buttons. Should we replace the old `text` variant with `filled-transparent` variant? (One of those buttons is the "Clear filters" text button on the filters sidebar on desktop.

**Review by AetherUnbound — APPROVED** [review]
LGTM, I don't see any references to medium-old remaining :smile:

**Review by zackkrida — APPROVED** [review]
LGTM!

**Comment by fcoveram** [comment]
> review the VNoResult’s buttons, and the text buttons.

Which button is the “VNoResult”? and which are the “text buttons”?

> Should we replace the old text variant with filled-transparent variant? (One of those buttons is the “Clear filters” text button on the filters sidebar on desktop.

Can you point out all the text variants?

I would appreciate a more specific review, otherwise I can't assess the time request for this review and might end up scanning all buttons in all pages.

**Comment by obulat** [comment]
@fcoveram , here is the list of buttons that use the "old" variants.

## `plain` `VButton`s
`plain` `VButton` variant only adds a focus ring, all other styles are added by the component itself
### `VIconButton`
### `VLogoButton`
Screenshot 2023-05-18 at 7 23 53 PM

### "Clear filters" in `VSearchGridFilter`
Screenshot 2023-05-18 at 7 08 49 PM

###  License explanation button with the question mark

Screenshot 2023-05-18 at 7 10 24 PM

### The external sources buttons inside the external sources popover

Screenshot 2023-05-18 at 7 12 55 PM
Screenshot 2023-05-18 at 7 12 25 PM

## `text` `VButton`s

###  "Clear" button in the Recent searches popover/modal
Screenshot 2023-05-18 at 7 21 01 PM

Screenshot 2023-05-18 at 7 13 53 PM
Screenshot 2023-05-18 at 7 12 43 PM

###  "Clear filters" button in the Content settings modal footer

Screenshot 2023-05-18 at 7 30 09 PM

## Other
The "external sources" button that opens the sources popover uses a special variant because it it a white button with dark-charcoal border when resting, and dark-charcoal when hovered.

Screenshot 2023-05-18 at 7 35 13 PM
Screenshot 2023-05-18 at 7 35 22 PM

**Pull request merged**
