### PR TITLE
Updated content link

### LINKED ISSUE #2083: Enable content link for no results and add pill in switcher popover item
## Problem

Currently, Openverse doesn't allow users to land on the meta search page from "All content" results when a search query doesn't bring results. The media link button shows a disabled state and we're missing the opportunity to show external sources.

## Description

We can improve this flow by applying three changes

### Enable the content type link

In "All content" results, content type link needs to show a "No results" label in the result area, and look and behave as described in #2078. The page should look like the following mockup.

All content results page with the content type link enabled

### Add a variant to the status pill ([Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=1753-3893&t=upKy3Stkw8fpuYiH-4))

'
The [pill component](https://docs.openverse.org/storybook/?path=/story/components-vpill--default-story&globals=backgrounds.grid:false) has a new variant and the following new styles:
* Height: `24px`
* Text style: `Time` style with `uppercase` text transformation
* Paddings: `8px` for left and right
* "No results" variant with "dark charcoal 10" as background

### Switcher item ([Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=3835-10885&t=upKy3Stkw8fpuYiH-4))

The [component](https://docs.openverse.org/storybook/?path=/story/components-vcontentswitcher-vsearchtypes--default-story&globals=backgrounds.grid:false) doesn't change any space or visual style for the resting, hover, and focus status, but check icon replaces the status pill when the content type is selected. See the prototype gif below.

Cursor pointer showing the status of popover items of switcher

## Additional context
* [Figma file](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=923-11742&t=2CbcKXAHD8lM0e5u-4)
* New design for content link component (#2078)

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #2078 by @fcoveram 
Fixes #2083 by @fcoveram 

## Description

This PR updates the `VContentLink` component to match the styles in the linked issue.
Content link is always enabled, even if there are no results (as per #2083).

I also added the `aria-label` to the button to improve the screen reader experience. Currently, it lacks a period between "See all images" and "... results", so it's not easy to understand. The new labels for images are:
```
 zero: "No images found for {query}. Try an external search source.",
count: "See {localeCount} image found for {query}|See {localeCount} images found for {query}",
countMore: "See over {localeCount} images found for {query}",
```
There are similar labels for audio.
I am a bit worried that having two content links at the top might make screen reader users think that all of the results consist of these two links, and not try to navigate on to the mixed view.

## Testing Instructions

Check that the content link on the All results view matches the mockups.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
Confirmed that I can see the changes to the `VContentLink` locally! (The term `john de mark` gives me image results but not audio ones, for others who may want to test the non-disabling buttons).

**Review by fcoveram — CHANGES_REQUESTED** [review]
I notice the following visual errors:
* The [large](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4799-12386&t=sEvEVd6P3WFAYNjM-4) variant of component should be `72px` height
* From `sm` and beyond the component should be [large](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4799-12386&t=sEvEVd6P3WFAYNjM-4). [Here are mockups](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=22-13656) for all breakpoints.
* In small variant, space between media type and results labels should be `4px`
* In hover and focus, results label changes from "dark charcoal 70" to "dark charcoal"

Regarding the aria-label script, I'm not sure about the "Try an external search source." sentence. The metasearch action is far from the navigation and, in my overall understanding, labels should aim to provide the same information to all users, and this content is not visually conveyed. I might be wrong in this last point

**Comment by obulat** [comment]
> Regarding the aria-label script, I'm not sure about the "Try an external search source." sentence. The metasearch action is far from the navigation and, in my overall understanding, labels should aim to provide the same information to all users, and this content is not visually conveyed. I might be wrong in this last point

This makes a lot of sense, you're right. I'll remove that part of the sentence.

**Review by fcoveram — COMMENTED** [review]
All styles look correct ✨ 🚀 

I just noticed that header cuts out the focus ring in `xs` and `sm`. Not sure if it belongs to this PR's scope so feel free to dismiss it.

keyboard navigation from header to content area in mobile device. Focus ring is visible

**Comment by obulat** [comment]
> I just noticed that header cuts out the focus ring in `xs` and `sm`. Not sure if it belongs to this PR's scope so feel free to dismiss it.

We have removed the top padding (from the `h1` element) in the header spacing improvements PR, and the header has a z-index of 40 (which it has to do because the header should be "higher" than the lower part of the site). To solve this we could add a small padding to the top of the main content. I'm not sure if we should prioritize this, though, because not many users would use small screen with a keyboard.

**Review by fcoveram — APPROVED** [review]
It looks great 🚀

**Pull request merged**
