### PR TITLE
Fix 404 rendering with relative CSS references

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

CSS is broken on the docs site for 404s that aren't on the root: https://docs.openverse.org/api/not_real.html

This is caused by CSS references rendered relative to the file on disk. Because GitHub is serving the same static page on sub-paths in the URL, the CSS reference breaks.

## Description

This [sphinx plugin (sphinx-notfound)](https://sphinx-notfound-page.readthedocs.io) that @obulat found fixes this precise issue by rendering a 404.html for you with absolute URLs. I deleted the existing 404.md because the content of that page was no more or less descriptive or helpful than the default one provided by the plugin.

## Testing Instructions

Run `just documentation/build` and confirm that `documentation/_build/404.html` has absolute rather than relative references for the CSS files in `head`. You can also pull the 404.html page from the preview by visiting `/404.html` relative to the preview link in the comment below and check there to avoid building it locally.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Works really well! Thank you for fixing this so quickly!

**Review by dhruvkb — APPROVED** [review]
@AetherUnbound had suggested the same plugin in her review of https://github.com/WordPress/openverse/pull/2064#pullrequestreview-1419253498. Should've listened and been more thorough in reviewing that PR, sorry.

@sarayourfriend would you mind reverting some other changes in that PR that were specifically made to facilitate that `404.md` file?

**Comment by sarayourfriend** [comment]
@dhruvkb Do you mean removing the fieldlist option or was there more you wanted removed?

**Comment by dhruvkb** [comment]
I didn't mean any one change in particular, just that other related changes from that PR to be reverted because what they facilitated was the now-gone `404.md` file.

**Pull request merged**
