### PR TITLE
Update Nuxt to v3.13.1

### PR DESCRIPTION
**Pull request by obulat**
## Description

This PR re-adds the changes for updating Nuxt to v3.13.1. I removed the changes related to i18n for easier testing.

Vue also had to be updated to the one matching this Nuxt version.
The patch release [fixed](https://github.com/nuxt/nuxt/pull/28700) the `serverDir` in `nuxt.config`, so I reverted the changes to folders for now.
I also added the recommended [workaround](https://nuxt.com/blog/v3-13#vue-typescript-changes) for `vue-router` types.

## Testing Instructions

The CI should pass, and the app should work as expected. Since the server folder was moved, it is important to check that the server routes work as usual (/healthcheck, /robots)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
Drafting because there are typing problems that we've previously seen and couldn't identify the origin: the component doesn't have `$route` property in this PR

**Comment by zackkrida** [comment]
@obulat just curious why the pinia reversion was necessary. This looks good though

**Comment by obulat** [comment]
> @obulat just curious why the pinia reversion was necessary. This looks good though

Just to minimize the number of changes in  one PR, to make reverting easier if necessary

**Review by zackkrida — APPROVED** [review]
LGTM. I appreciate the constrained scope.

**Pull request merged**
