### PR TITLE
Add a redirect on 503 to frontend nginx

### LINKED ISSUE #2993: Add access request logging to Nuxt
## Problem

We have no server request access logging set up for Nuxt, which makes investigating frontend incidents very difficult.

## Description

Add access request logging using a middleware. This one-log-per-request middleware should match what Django provides out of the box: timestamps, request path etc.

## Additional context

This is a hot-fix before we implement a full-fledged Nuxt server logging solution.

### LINKED ISSUE #2996: Handle Plausible outages
## Problem

When Plausible server was out on August 28th, we received reports of many 5xx responses from Nuxt. This was misleading because there was no degradation of Openverse frontend for the user (the analytics requests are not blocking and don't break anything in the UI if they fail).

## Description

We should re-write the response header in case Plausible returns 503. Here's is the example of rewriting for 504 errors:

https://github.com/WordPress/openverse/blob/6408b4234241046816c8e68a2bb73226a0c6821d/frontend/nuxt.config.ts#L337-L344

In case the error message contains "service unavailable", we should add the error message to the message that is logged to the console. I think we don't event need to check if it's prod or dev environment, as we might want to see the message logged everywhere.

```
if (err.message.toLowerCase().includes("service unavailable")) { 
       res.writeHead(424, { "Content-Type": "text/plain" }) 
       res.end(`Plausible unavailable: ${e.message}`) 
     } 
```

Note: I am not sure about the shape of the `err` object here. In Cloudflare, I can only see the "Edge status code" and "Origin status code", both equal to "503 Service Unavailable"

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2996 by @obulat

## Description

This PR rewrites the error code when Plausible is unavailable (503) to a 424 error to allow us to count frontend 5xx errors separately from Plausible 5xx errors.

## Testing Instructions

I don't know how to test this.

I tried adding the following patch:
```
Subject: [PATCH] Add a redirect on 503 to frontend nginx
---
Index: frontend/nginx.conf.template
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/frontend/nginx.conf.template b/frontend/nginx.conf.template
--- a/frontend/nginx.conf.template	(revision 19cde7cdff2d8b785ebb4dee50966a37be5dd4eb)
+++ b/frontend/nginx.conf.template	(date 1712906826225)
@@ -73,7 +73,8 @@
     resolver $OPENVERSE_NGINX_DNS_RESOLVER;
     set $plausible_event_url $OPENVERSE_NGINX_PLAUSIBLE_EVENT_URL;
     location = /api/event {
-        proxy_pass $plausible_event_url;
+        return 503;
+        # proxy_pass $plausible_event_url;
         proxy_set_header Host plausible.io;
         proxy_buffering on;
         proxy_http_version 1.1;
```
And running `just frontend/up` and `just frontend/dev` (or `just frontend/build` & `just frontend/start`), but the event was still sent. I also updated the Plausible settings in the `nuxt.config` to use the local url instead of plausible.io, but could not mock a 503 error.
@sarayourfriend, do you know how we could test this?

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
FWIW I'm able to verify that a 424 is received locally with the following diff:

```diff
diff --git a/frontend/nginx.conf.template b/frontend/nginx.conf.template
index 6a963b9e8..eababc474 100644
--- a/frontend/nginx.conf.template
+++ b/frontend/nginx.conf.template
@@ -73,7 +73,7 @@ server {
     resolver $OPENVERSE_NGINX_DNS_RESOLVER;
     set $plausible_event_url $OPENVERSE_NGINX_PLAUSIBLE_EVENT_URL;
     location = /api/event {
-        proxy_pass $plausible_event_url;
+        # proxy_pass $plausible_event_url;
         proxy_set_header Host plausible.io;
         proxy_buffering on;
         proxy_http_version 1.1;
@@ -81,6 +81,7 @@ server {
         proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Forwarded-Host  $host;
+        return 503;
 
         proxy_intercept_errors on;
         error_page 503 = @custom_424;  # Redirect 503 errors when Plausible is down

```

image

**Comment by obulat** [comment]
> FWIW I'm able to verify that a 424 is received locally with the following diff:
> 
> ```diff
> diff --git a/frontend/nginx.conf.template b/frontend/nginx.conf.template
> index 6a963b9e8..eababc474 100644
> --- a/frontend/nginx.conf.template
> +++ b/frontend/nginx.conf.template
> @@ -73,7 +73,7 @@ server {
>      resolver $OPENVERSE_NGINX_DNS_RESOLVER;
>      set $plausible_event_url $OPENVERSE_NGINX_PLAUSIBLE_EVENT_URL;
>      location = /api/event {
> -        proxy_pass $plausible_event_url;
> +        # proxy_pass $plausible_event_url;
>          proxy_set_header Host plausible.io;
>          proxy_buffering on;
>          proxy_http_version 1.1;
> @@ -81,6 +81,7 @@ server {
>          proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
>          proxy_set_header X-Forwarded-Proto $scheme;
>          proxy_set_header X-Forwarded-Host  $host;
> +        return 503;
>  
>          proxy_intercept_errors on;
>          error_page 503 = @custom_424;  # Redirect 503 errors when Plausible is down
> ```

Thank you, @AetherUnbound !
I'll mark this PR as ready for review, then :)

**Review by AetherUnbound — APPROVED** [review]
LGTM and makes sense!

**Review by zackkrida — APPROVED** [review]
:+1:

**Pull request merged**
