### PR TITLE
Convert the report content popover to a modal

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #3582 by @obulat

## Description

This PR replaces the report content popover with a modal that matches the updated [designs in Figma](https://www.figma.com/design/chRWINXqyRzYRPZOJOJHuD/Modal-popover-for-report-and-license-definition?node-id=22-13656&m=dev).

### Previous version of the content report
Content report popover

### Updated version of the content report
Content report modal

Note: this PR does not touch the license explanation modal because the nested modal handling requires more changes.

## Testing Instructions

1. Run the app. Go to a single result page and click on the "Report content" button. The form should open in a modal and should look/work correctly.
2. Check that the report page (e.g. http://0.0.0.0:8443/image/cfa45160-a7be-4911-9b9f-4e66678ec7f7/report) looks correctly

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (`ov just catalog/generate-docs` for catalog
      PRs) or the media properties generator (`ov just catalog/generate-docs media-props`
      for the catalog or `ov just api/generate-docs` for the API) where applicable.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
LGTM with one exception. I think closing the modal needs to reset the report status to allow for multiple reports. While an unlikely use case, it's possible an image ought to be reported for multiple cases.

Also, small aside: should the modal close on an external click? It doesn't currently.

**Comment by obulat** [comment]
I set the modal to close on click outside. I'm not entirely sure that this is best: if the users are trying to enter the text in the report text area, they might accidentally close the modal, and reset the state, which would be annoying.

I've also updated the user experience when submitting the reports:

1. After the report is submitted, the modal shows the status (sent/failed) and is automatically closed after 3 seconds (arbitrary amount, seems enough to read the text)
2. The DMCA form opens in a new tab. That's why the status modal is not dismissed automatically, users have to click X to close it.
3. The media Openverse URL is pre-filled in the DMCA form

@fcoveram, do you think any of these changes should be reverted

**Review by fcoveram — CHANGES_REQUESTED** [review]
I noticed the following

### Small variant

I don't see the popover's small variant on `xs`

### Spacing

There is an inconsistent spacing that I think it was set to align the close button with the main content area, but it ended up misaligning the latter.

| Outter padding | Content padding |
|:---|:---|
| Screenshot of popover from browser inspector with notes on outer paddings | Screenshot of popover from browser inspector with notes on inner paddings |

The design has two areas: header and content. Header is where title and close actions are, and content is for the main info. Header area has different spacings to visually align the cross icon with the right side of the text, whereas content area has equal spacings except on the top side.

Here is an screenshot from Figma

Mockup of popover with spacing notes

This approach comes from other previous reports where popover's content overflows the container due to device height. For those cases, the content area is scrollable.

Popover with scroll in content area

(copied from #3582)

If the above exceeds the dev efforts planned, we can then equal the spacings in header and content areas. But it adds value implementing them separately to avoid overflow cases.

Let me know what you think.

**Comment by fcoveram** [comment]
Regarding @zackkrida's points

>… I think closing the modal needs to reset the report status to allow for multiple reports…

> …should the modal close on an external click? It doesn't currently.

I agree with both suggestions

And on @obulat's ping

> 1. After the report is submitted, the modal shows the status (sent/failed) and is automatically closed after 3 seconds (arbitrary amount, seems enough to read the text)
> 2. The DMCA form opens in a new tab. That's why the status modal is not dismissed automatically, users have to click X to close it.
> 3. The media Openverse URL is pre-filled in the DMCA form

All good with points 2 and 3, but for point 1, I'm drawn to keep the message open so closing it is an intentional action.

In that vein, I would apply the spacing approach [reviewed](https://github.com/WordPress/openverse/pull/4701#pullrequestreview-2250052833) previously in the success message. The current looks tight in the bottom area.

Success message reporting content with a spacing note

**Review by zackkrida — APPROVED** [review]
LGTM! Excellent improvements.

**Pull request merged**
