### PR TITLE
Remove potentially problematic `do_not_wait_for`

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Related to the recent API outage we had.

## Description

This is the main place in our code where we create asyncio tasks that could potentially be the tasks in question in the "Task was destroyed" errors related to the recent outage.

I don't know for sure that these are the problem, but the approach with `do_not_wait_for` is not necessary for our thumbnails endpoint to be sufficiently performant.

Even if this doesn't address whatever the problem was, I'd call this a code quality improvement by simplify the code and removing something potentially arcane and confusing that isn't strictly necessary.

## Testing Instructions

CI should pass. Everything changed here is tested in unit tests.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.
- [N/A] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
Am I understanding correctly that by changing `do_not_wait_for` to `await`, we are losing that functionality that allows us to not care for the outcome of a async task?

This PR LGTM, and I'm all for deleting code that could be the cause of a problem but I want to know if we're trading performance for it.

**Comment by sarayourfriend** [comment]
Yes, you're correct in that understanding. From a performance perspective, this probably accounts for milliseconds of difference in the response time of our longest route. By percentage, I don't think this could be a meaningful increase in the time it takes to process the request. It therefore also isn't necessarily a meaningful performance _improvement_ either (another good reason to remove it).

We are technically reducing the performance of the endpoint _strictly_ speaking, but there are better ways to defer tasks to "sometime in the near future" than what we've done here (like a message queue or maybe async Django signals) if we want to revisit this again (or if we _need_ to, if this PR turns out to cause it's own problems).

**Comment by dhruvkb** [comment]
💯 For sure, I'm sure the performance implication of the change would be extremely small, I just wanted to confirm if I was understanding correctly. I still can't fully wrap my heads around the async parts of the API so thanks for clarifying.

**Review by AetherUnbound — APPROVED** [review]
LGTM! A good call regardless, as you mention 🙂

**Pull request merged**
